[build-system]
requires = ["poetry==1.0.8"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "dnd-helper"
description = ""
authors = ["Dmitry Bozhenko"]
version = "1.0.0"

[tool.poetry.dependencies]
python = "3.9.7"
Django = "^3.1.7"
django-multiselectfield = "^0.1.12"
pillow = "^8.1.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.7.0"
ipython = "^7.21.0"
flake8 = "^3.8.3"
mypy = "^0.812"

[tool.black]
include = '\.py$'
skip-string-normalization = true
target-version = ['py38']
