# Generated by Django 5.1.6 on 2025-02-23 20:22

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.avatar',),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.encounter',),
        ),
        migrations.CreateModel(
            name='GridMap',
            fields=[],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.gridmap',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.party',),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[],
            options={
                'verbose_name': 'Player character',
                'verbose_name_plural': 'Player characters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.playercharacter',),
        ),
    ]
