# Generated by Django 5.1.6 on 2025-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_alter_encounter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.encounter',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.party',),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[],
            options={
                'verbose_name': 'Player character',
                'verbose_name_plural': 'Player characters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.playercharacter',),
        ),
    ]
