# Generated by Django 5.2.1 on 2025-05-09 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                (
                    'monster_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='base.monster',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
            },
            bases=('base.monster',),
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.avatar',),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[],
            options={
                'verbose_name': 'Encounter',
                'verbose_name_plural': 'Encounters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.encounter',),
        ),
        migrations.CreateModel(
            name='GridMap',
            fields=[],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.gridmap',),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.party',),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[],
            options={
                'verbose_name': 'Player character',
                'verbose_name_plural': 'Player characters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.playercharacter',),
        ),
    ]
