# Generated by Django 5.2.1 on 2025-05-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_combatantmonster_armor_class_and_more'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                (
                    'monster_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='base.monster',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
            },
            bases=('base.monster',),
        ),
    ]
