# Generated by Django 5.1.4 on 2025-02-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('printer', '0002_alter_avatar_options_alter_gridmap_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.avatar',),
        ),
        migrations.CreateModel(
            name='GridMap',
            fields=[],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('printer.gridmap',),
        ),
    ]
