# Generated by Django 5.2.1 on 2025-05-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monster',
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[],
            options={
                'verbose_name': 'Monster',
                'verbose_name_plural': 'Monsters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.monster',),
        ),
    ]
