# Generated by Django 4.0.2 on 2022-02-12 16:09

from django.db import migrations, models
import django.db.models.deletion
import printer.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='encounter_icons', verbose_name='базовая картинка')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Количество однотипных')),
                ('number_color', models.CharField(choices=[('white', 'Белый'), ('red', 'Красный'), ('black', 'Чёрный')], default=printer.constants.ColorsStyle['RED'], max_length=5, verbose_name='Цвет номера')),
                ('width', models.PositiveSmallIntegerField(default=200, verbose_name='Ширина')),
                ('number_position', models.CharField(choices=[('top-left', 'Вверху слева'), ('top-right', 'Вверху справа'), ('bottom-left', 'Внизу слева'), ('bottom-right', 'Внизу справа'), ('center', 'По центру')], default=printer.constants.Position['TOP_LEFT'], max_length=12, verbose_name='Класс позиции номера на картинке')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
            },
        ),
        migrations.CreateModel(
            name='PrintableObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                ('type', models.CharField(blank=True, choices=[('ITEM', 'Магический предмет'), ('AT_WILL', 'Неограниченный талант'), ('DAYLY', 'Талант на день'), ('ENCOUNTER', 'Талант на сцену')], max_length=9, null=True, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='PrintableObjectItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=15, null=True, verbose_name='Название')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('p_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='printer.printableobject')),
            ],
            options={
                'verbose_name': 'Аттрибут',
                'verbose_name_plural': 'Аттрибуты',
            },
        ),
    ]
