# Generated by Django 3.2.9 on 2021-12-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='PrintableObject',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=40, verbose_name='Название')),
                (
                    'type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('ITEM', 'Магический предмет'),
                            ('AT_WILL', 'Неограниченный талант'),
                            ('DAYLY', 'Талант на день'),
                            ('ENCOUNTER', 'Талант на сцену'),
                        ],
                        max_length=9,
                        null=True,
                        verbose_name='Тип объекта',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='PrintableObjectItems',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                (
                    'title',
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name='Название'
                    ),
                ),
                (
                    'description',
                    models.CharField(max_length=256, verbose_name='Описание'),
                ),
                (
                    'p_object',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='printer.printableobject',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Аттрибут',
                'verbose_name_plural': 'Аттрибуты',
            },
        ),
    ]
