# Generated by Django 4.1.6 on 2023-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printableobject',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ITEM', 'Магический предмет'),
                    ('AT_WILL', 'Неограниченный талант'),
                    ('DAILY', 'Талант на день'),
                    ('ENCOUNTER', 'Талант на сцену'),
                ],
                max_length=9,
                null=True,
                verbose_name='Тип объекта',
            ),
        ),
    ]
