# Generated by Django 5.1.7 on 2025-03-16 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=20, null=True, verbose_name='Name'),
                ),
                (
                    'top_left_x',
                    models.PositiveSmallIntegerField(verbose_name='Top left x'),
                ),
                (
                    'top_left_y',
                    models.PositiveSmallIntegerField(verbose_name='Top left y'),
                ),
                (
                    'bottom_right_x',
                    models.PositiveSmallIntegerField(verbose_name='Bottom right x'),
                ),
                (
                    'bottom_right_y',
                    models.PositiveSmallIntegerField(verbose_name='Bottom right y'),
                ),
                (
                    'map',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='printer.gridmap',
                        verbose_name='Map',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
