# Generated by Django 5.1.4 on 2024-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantplace',
            name='is_unconscious',
        ),
        migrations.AddField(
            model_name='participantplace',
            name='rotation',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (90, 90), (180, 180), (270, 270), (360, 360)],
                default=0,
            ),
        ),
    ]
