# Generated by Django 5.1.4 on 2024-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridMap',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'base_image',
                    models.ImageField(
                        blank=True, null=True, upload_to='maps', verbose_name='Карта'
                    ),
                ),
            ],
        ),
    ]
