# Generated by Django 5.1.6 on 2025-02-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'verbose_name': 'Avatar', 'verbose_name_plural': 'Avatars'},
        ),
        migrations.AlterModelOptions(
            name='gridmap',
            options={'verbose_name': 'Map', 'verbose_name_plural': 'Maps'},
        ),
    ]
