# Generated by Django 5.1.7 on 2025-03-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantplace',
            name='is_updated',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
