# Generated by Django 5.2 on 2025-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantplace',
            old_name='number',
            new_name='number_in_cell',
        ),
        migrations.AddField(
            model_name='participantplace',
            name='displayed_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number'),
        ),
    ]
