# Generated by Django 4.0.1 on 2022-01-30 13:24

from django.db import migrations, models

import printer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[('white', 'Белый'), ('red', 'Красный'), ('black', 'Чёрный')],
                default=printer.constants.ColorsStyle['RED'],
                max_length=5,
                verbose_name='Цвет номера',
            ),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='number_position',
            field=models.CharField(
                choices=[
                    ('top-left', 'Вверху слева'),
                    ('top-right', 'Вверху справа'),
                    ('bottom-left', 'Внизу слева'),
                    ('bottom-right', 'Внизу справа'),
                    ('center', 'По центру'),
                ],
                default=printer.constants.Position['TOP_LEFT'],
                max_length=12,
                verbose_name='Класс позиции номера на картинке',
            ),
        ),
    ]
