# Generated by Django 5.1.4 on 2025-01-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_class_default_powers_subclass_default_powers'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Avatar',
        ),
    ]
