# Generated by Django 5.1.4 on 2024-12-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_gridmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmap',
            name='name',
            field=models.CharField(
                default='Карта', max_length=30, verbose_name='Название'
            ),
        ),
    ]
