# Generated by Django 5.1.4 on 2025-01-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_rename_participant_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='base_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='avatars', verbose_name='Base image'
            ),
        ),
    ]
