# Generated by Django 5.2 on 2025-04-12 19:39

import django.db.models.deletion
from django.db import migrations, models

import printer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_participantplace_is_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('none', 'Пусто'),
                    ('gray', 'Серый'),
                    ('black', 'Чёрный'),
                ],
                default='red',
                max_length=5,
                verbose_name='Number color',
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='grid_color',
            field=models.CharField(
                choices=[
                    ('none', 'Пусто'),
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('gray', 'Серый'),
                    ('black', 'Чёрный'),
                ],
                default=printer.constants.ColorStyle['NONE'],
                max_length=5,
                verbose_name='Grid color',
            ),
        ),
        migrations.CreateModel(
            name='MapZone',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'top_left_x',
                    models.PositiveSmallIntegerField(verbose_name='Top left x'),
                ),
                (
                    'top_left_y',
                    models.PositiveSmallIntegerField(verbose_name='Top left y'),
                ),
                (
                    'color',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('none', 'Пусто'),
                            ('white', 'Белый'),
                            ('green', 'Зелёный'),
                            ('red', 'Красный'),
                            ('gray', 'Серый'),
                            ('black', 'Чёрный'),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name='Color',
                    ),
                ),
                (
                    'map',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='zones',
                        to='printer.gridmap',
                        verbose_name='Map',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
