# Generated by Django 5.1.7 on 2025-03-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='style',
            field=models.CharField(
                choices=[
                    ('thick', 'Толстый'),
                    ('dashed', 'Чёрточки'),
                    ('dotted', 'Точки'),
                    ('double', 'Двойной'),
                    ('none', 'Пустой'),
                ],
                default='dotted',
                max_length=6,
                verbose_name='Style',
            ),
            preserve_default=False,
        ),
    ]
