# Generated by Django 5.1.6 on 2025-02-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_alter_avatar_options_alter_gridmap_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='cells_on_longest_side',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Cells on longest side'
            ),
        ),
    ]
