# Generated by Django 5.2 on 2025-04-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_rename_number_participantplace_number_in_cell_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EncounterIcons',
        ),
    ]
