# Generated by Django 5.2.1 on 2025-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='auto_mode',
            field=models.BooleanField(default=True),
        ),
    ]
