# Generated by Django 3.1.7 on 2021-10-12 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_auto_20211012_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintableObjectItems',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                (
                    'title',
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name='Название'
                    ),
                ),
                (
                    'description',
                    models.CharField(max_length=100, verbose_name='Описание'),
                ),
                (
                    'p_object',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='printer.printableobject',
                    ),
                ),
            ],
        ),
    ]
