# Generated by Django 5.1.4 on 2024-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_gridmap_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmap',
            name='cols',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Количество столбцов'
            ),
        ),
        migrations.AddField(
            model_name='gridmap',
            name='rows',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Количество строк'
            ),
        ),
    ]
