# Generated by Django 5.1.7 on 2025-03-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_zone_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='map',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='zones',
                to='printer.gridmap',
                verbose_name='Map',
            ),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='Name'
            ),
        ),
    ]
