# Generated by Django 4.0 on 2021-12-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'printer',
            '0003_encountericons_number_position_encountericons_width_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[('BLACK', 'Black'), ('RED', 'Red'), ('WHITE', 'White')],
                default='RED',
                max_length=5,
                verbose_name='Цвет номера',
            ),
        ),
    ]
