# Generated by Django 3.1.7 on 2021-10-12 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_printableobjectitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printableobjectitems',
            options={'verbose_name': 'Аттрибут', 'verbose_name_plural': 'Аттрибуты'},
        ),
        migrations.AlterField(
            model_name='printableobjectitems',
            name='p_object',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='printer.printableobject',
            ),
        ),
    ]
