# Generated by Django 5.1.4 on 2025-01-17 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_class_default_powers_subclass_default_powers'),
        ('printer', '0003_alter_avatar_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='npc',
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={'avatar__isnull': True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='avatar',
                to='base.npc',
                verbose_name='Non player character',
            ),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='pc',
            field=models.OneToOneField(
                blank=True,
                limit_choices_to={'avatar__isnull': True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='avatar',
                to='base.playercharacter',
                verbose_name='Player character',
            ),
        ),
    ]
