# Generated by Django 5.2 on 2025-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_alter_encountericons_number_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='zone_types',
                        verbose_name='Base image',
                    ),
                ),
                (
                    'length',
                    models.PositiveSmallIntegerField(default=3, verbose_name='Length'),
                ),
                (
                    'width',
                    models.PositiveSmallIntegerField(default=3, verbose_name='Width'),
                ),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
            },
        ),
    ]
