# Generated by Django 5.2 on 2025-04-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_delete_encountericons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='grid_color',
            field=models.CharField(
                choices=[
                    ('none', 'Пусто'),
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('gray', 'Серый'),
                    ('black', 'Чёрный'),
                ],
                default='NONE',
                max_length=5,
                verbose_name='Grid color',
            ),
        ),
    ]
