# Generated by Django 5.2 on 2025-04-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapzone',
            name='zone',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='printer.zone',
                verbose_name='Zone type',
            ),
        ),
    ]
