# Generated by Django 4.0 on 2021-12-20 12:25

from django.db import migrations, models

import printer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_alter_encountericons_number_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[('black', 'Black'), ('red', 'Red'), ('white', 'White')],
                default=printer.constants.ColorsStyle['RED'],
                max_length=5,
                verbose_name='Цвет номера',
            ),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='number_position',
            field=models.CharField(
                choices=[
                    ('bottom-left', 'bottom-left'),
                    ('bottom-right', 'bottom-right'),
                    ('center', 'center'),
                    ('top-left', 'top-left'),
                    ('top-right', 'top-right'),
                ],
                default=printer.constants.Position['TOP_LEFT'],
                max_length=12,
                verbose_name='Класс позиции номера на картинке',
            ),
        ),
    ]
