# Generated by Django 5.1.7 on 2025-03-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_zone_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='color',
            field=models.CharField(
                blank=True,
                choices=[
                    ('none', 'Пусто'),
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('black', 'Чёрный'),
                ],
                max_length=20,
                null=True,
                verbose_name='Color',
            ),
        ),
        migrations.AlterField(
            model_name='zone',
            name='style',
            field=models.CharField(
                blank=True,
                choices=[
                    ('thick', 'Толстый'),
                    ('dashed', 'Чёрточки'),
                    ('dotted', 'Точки'),
                    ('double', 'Двойной'),
                    ('none', 'Пустой'),
                ],
                max_length=6,
                null=True,
                verbose_name='Style',
            ),
        ),
    ]
