# Generated by Django 5.2 on 2025-04-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_mapzone_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridmap',
            name='zones',
            field=models.ManyToManyField(
                through='printer.MapZone', to='printer.zone', verbose_name='Zones'
            ),
        ),
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Name'
            ),
        ),
        migrations.AlterField(
            model_name='mapzone',
            name='map',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='map_zones',
                to='printer.gridmap',
                verbose_name='Map',
            ),
        ),
        migrations.AlterField(
            model_name='mapzone',
            name='zone',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='map_zones',
                to='printer.zone',
                verbose_name='Zone type',
            ),
        ),
    ]
