# Generated by Django 5.2 on 2025-04-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_gridmap_zones_zone_name_alter_mapzone_map_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='length',
            new_name='default_length',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='width',
            new_name='default_width',
        ),
        migrations.AddField(
            model_name='mapzone',
            name='custom_length',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapzone',
            name='custom_width',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Width'),
            preserve_default=False,
        ),
    ]
