# Generated by Django 5.1.4 on 2024-12-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_alter_encountericons_number_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                (
                    'base_image',
                    models.ImageField(
                        blank=True, null=True, upload_to='maps', verbose_name='Карта'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantPlace',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('row', models.SmallIntegerField(default=-1)),
                ('col', models.SmallIntegerField(default=-1)),
                ('is_unconscious', models.BooleanField(default=False)),
                (
                    'map',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='printer.gridmap',
                    ),
                ),
                (
                    'participant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='printer.participant',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='gridmap',
            name='participants',
            field=models.ManyToManyField(
                blank=True, through='printer.ParticipantPlace', to='printer.participant'
            ),
        ),
    ]
