# Generated by Django 5.1.4 on 2025-01-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_alter_participantplace_col_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridmap',
            name='cols',
        ),
        migrations.RemoveField(
            model_name='gridmap',
            name='rows',
        ),
        migrations.AddField(
            model_name='gridmap',
            name='cells_on_longest_side',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gridmap',
            name='height',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gridmap',
            name='width',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='base_image',
            field=models.ImageField(
                blank=True,
                height_field='height',
                null=True,
                upload_to='maps',
                verbose_name='Карта',
                width_field='width',
            ),
        ),
    ]
