# Generated by Django 5.1.4 on 2025-01-08 09:12

import django.db.models.deletion
from django.db import migrations, models

import printer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_remove_gridmap_cols_remove_gridmap_rows_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encountericons',
            options={'verbose_name': 'Icon', 'verbose_name_plural': 'Icons'},
        ),
        migrations.AlterModelOptions(
            name='printableobject',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AlterModelOptions(
            name='printableobjectitems',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='base_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='encounter_icons',
                verbose_name='Base image',
            ),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('black', 'Чёрный'),
                ],
                default=printer.constants.ColorsStyle['RED'],
                max_length=5,
                verbose_name='Number color',
            ),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='number_position',
            field=models.CharField(
                choices=[
                    ('top-left', 'Вверху слева'),
                    ('top-right', 'Вверху справа'),
                    ('bottom-left', 'Внизу слева'),
                    ('bottom-right', 'Внизу справа'),
                    ('center', 'По центру'),
                ],
                default=printer.constants.Position['TOP_LEFT'],
                max_length=12,
                verbose_name='Number position',
            ),
        ),
        migrations.AlterField(
            model_name='encountericons',
            name='width',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='base_image',
            field=models.ImageField(
                blank=True,
                height_field='height',
                null=True,
                upload_to='maps',
                verbose_name='Base image',
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='grid_color',
            field=models.CharField(
                choices=[
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('black', 'Чёрный'),
                ],
                default=printer.constants.ColorsStyle['WHITE'],
                max_length=5,
                verbose_name='Grid color',
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='height',
            field=models.PositiveSmallIntegerField(verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='name',
            field=models.CharField(
                default='Карта', max_length=30, verbose_name='Title'
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='participants',
            field=models.ManyToManyField(
                blank=True,
                through='printer.ParticipantPlace',
                to='printer.participant',
                verbose_name='Participants',
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='width',
            field=models.PositiveSmallIntegerField(verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='base_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='participants',
                verbose_name='Base image',
            ),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='col',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Column'),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='map',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='places',
                to='printer.gridmap',
                verbose_name='Map',
            ),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='participant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='places',
                to='printer.participant',
                verbose_name='Participant',
            ),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='rotation',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 0), (90, 90), (180, 180), (270, 270)],
                default=0,
                verbose_name='Rotation',
            ),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='row',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Row'),
        ),
        migrations.AlterField(
            model_name='printableobject',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='printableobject',
            name='type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ITEM', 'Магический предмет'),
                    ('AT_WILL', 'Неограниченный талант'),
                    ('DAILY', 'Талант на день'),
                    ('ENCOUNTER', 'Талант на сцену'),
                ],
                max_length=9,
                null=True,
                verbose_name='Object type',
            ),
        ),
        migrations.AlterField(
            model_name='printableobjectitems',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='printableobjectitems',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='printableobjectitems',
            name='p_object',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='printer.printableobject',
                verbose_name='Object',
            ),
        ),
        migrations.AlterField(
            model_name='printableobjectitems',
            name='title',
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name='Title'
            ),
        ),
    ]
