# Generated by Django 5.1.4 on 2024-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0007_participant_participantplace_gridmap_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='base_image',
            field=models.ImageField(
                blank=True, null=True, upload_to='participants', verbose_name='Карта'
            ),
        ),
    ]
