# Generated by Django 5.1.4 on 2025-01-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_alter_encountericons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='width',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Width'),
        ),
    ]
