# Generated by Django 5.2 on 2025-04-13 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_alter_mapzone_custom_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapzone',
            name='custom_opacity',
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
        migrations.AddField(
            model_name='zone',
            name='default_opacity',
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
    ]
