# Generated by Django 5.1.4 on 2024-12-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0008_alter_participant_base_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantplace',
            name='map',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='places',
                to='printer.gridmap',
            ),
        ),
        migrations.AlterField(
            model_name='participantplace',
            name='participant',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='places',
                to='printer.participant',
            ),
        ),
    ]
