# Generated by Django 5.1.4 on 2025-01-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_alter_gridmap_height_alter_gridmap_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='height',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='width',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Width'),
        ),
    ]
