# Generated by Django 5.2 on 2025-04-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_mapzone_custom_opacity_zone_default_opacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapzone',
            name='color',
        ),
    ]
