# Generated by Django 5.1.4 on 2024-12-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0009_alter_participantplace_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='base_size',
            field=models.SmallIntegerField(
                choices=[
                    (-1, 'Крошечный'),
                    (0, 'Маленький'),
                    (1, 'Средний'),
                    (2, 'Большой'),
                    (3, 'Огромный'),
                ],
                default=1,
                verbose_name='Size',
            ),
        ),
    ]
