# Generated by Django 5.1.4 on 2025-01-11 13:29

from django.db import migrations, models

import printer.constants


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0010_alter_gridmap_height_alter_gridmap_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encountericons',
            name='number_color',
            field=models.CharField(
                choices=[
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('none', 'Пусто'),
                    ('black', 'Чёрный'),
                ],
                default=printer.constants.ColorsStyle['RED'],
                max_length=5,
                verbose_name='Number color',
            ),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='grid_color',
            field=models.CharField(
                choices=[
                    ('white', 'Белый'),
                    ('green', 'Зелёный'),
                    ('red', 'Красный'),
                    ('none', 'Пусто'),
                    ('black', 'Чёрный'),
                ],
                default=printer.constants.ColorsStyle['NONE'],
                max_length=5,
                verbose_name='Grid color',
            ),
        ),
    ]
