# Generated by Django 5.2 on 2025-04-13 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0010_remove_mapzone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantplace',
            name='opacity',
            field=models.FloatField(
                choices=[(0, 0), (1, 1), (0.5, 0.5)],
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
        migrations.AlterField(
            model_name='mapzone',
            name='custom_opacity',
            field=models.FloatField(
                choices=[(0, 0), (0.5, 0.5), (1, 1)],
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
        migrations.AlterField(
            model_name='zone',
            name='default_opacity',
            field=models.FloatField(
                choices=[(0, 0), (0.5, 0.5), (1, 1)],
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
    ]
