# Generated by Django 5.2 on 2025-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0012_alter_participantplace_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantplace',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
