# Generated by Django 5.2 on 2025-04-19 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0014_alter_mapzone_custom_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapzone',
            name='custom_opacity',
            field=models.FloatField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name='Opacity',
            ),
        ),
    ]
