# Generated by Django 5.2 on 2025-04-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedNames',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=30, unique=True, verbose_name='Name'),
                ),
            ],
            options={
                'verbose_name': 'Banned name',
                'verbose_name_plural': 'Banned names',
            },
        ),
        migrations.CreateModel(
            name='NPCName',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=30, unique=True, verbose_name='Name'),
                ),
                (
                    'name_type',
                    models.CharField(
                        choices=[('first', 'Имя'), ('last', 'Фамилия')],
                        max_length=10,
                        verbose_name='Type',
                    ),
                ),
                (
                    'sex',
                    models.CharField(
                        blank=True,
                        choices=[('M', 'Муж'), ('F', 'Жен'), ('N', 'Н/Д')],
                        max_length=1,
                        null=True,
                        verbose_name='Sex',
                    ),
                ),
                ('race', models.ManyToManyField(to='base.race', verbose_name='Races')),
            ],
            options={
                'verbose_name': 'Name',
                'verbose_name_plural': 'Names',
            },
        ),
    ]
