# Generated by Django 5.1.4 on 2025-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_race_options'),
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedNames',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=30, unique=True, verbose_name='Name'),
                ),
            ],
            options={
                'verbose_name': 'Banned name',
                'verbose_name_plural': 'Banned names',
            },
        ),
        migrations.DeleteModel(
            name='BannedNamesVariants',
        ),
        migrations.AlterModelOptions(
            name='npcname',
            options={'verbose_name': 'Name', 'verbose_name_plural': 'Names'},
        ),
        migrations.AlterField(
            model_name='npcname',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='npcname',
            name='name_type',
            field=models.CharField(
                choices=[('first', 'Имя'), ('last', 'Фамилия')],
                max_length=10,
                verbose_name='Type',
            ),
        ),
        migrations.AlterField(
            model_name='npcname',
            name='race',
            field=models.ManyToManyField(to='base.race', verbose_name='Races'),
        ),
        migrations.AlterField(
            model_name='npcname',
            name='sex',
            field=models.CharField(
                blank=True,
                choices=[('M', 'Муж'), ('F', 'Жен'), ('N', 'Н/Д')],
                max_length=1,
                null=True,
                verbose_name='Sex',
            ),
        ),
    ]
