# Generated by Django 4.0.2 on 2022-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_npc_base_attack_ability'),
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npcname',
            name='race',
            field=models.ManyToManyField(to='base.Race', verbose_name='Расы'),
        ),
    ]
