# Generated by Django 5.2 on 2025-04-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.armor',),
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[],
            options={
                'verbose_name': 'Armor type',
                'verbose_name_plural': 'Armor types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.armortype',),
        ),
        migrations.CreateModel(
            name='ArmsSlotItem',
            fields=[],
            options={
                'verbose_name': 'Hand item/shield',
                'verbose_name_plural': 'Hand items/shields',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.armsslotitem',),
        ),
        migrations.CreateModel(
            name='MagicArmItemType',
            fields=[],
            options={
                'verbose_name': 'Magic shield/arms slot item type',
                'verbose_name_plural': 'Magic shield/arms slot item types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.magicarmitemtype',),
        ),
        migrations.CreateModel(
            name='MagicArmorType',
            fields=[],
            options={
                'verbose_name': 'Magic armor type',
                'verbose_name_plural': 'Magic armor types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.magicarmortype',),
        ),
        migrations.CreateModel(
            name='MagicItemType',
            fields=[],
            options={
                'verbose_name': 'Magic item type',
                'verbose_name_plural': 'Magic item types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.magicitemtype',),
        ),
        migrations.CreateModel(
            name='MagicWeaponType',
            fields=[],
            options={
                'verbose_name': 'Magic weapon type',
                'verbose_name_plural': 'Magic weapon types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.magicweapontype',),
        ),
        migrations.CreateModel(
            name='SimpleMagicItem',
            fields=[],
            options={
                'verbose_name': 'Magic item',
                'verbose_name_plural': 'Magic items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.weapon',),
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[],
            options={
                'verbose_name': 'Weapon type',
                'verbose_name_plural': 'Weapon types',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.weapontype',),
        ),
    ]
