from base.objects import npc_classes, races

races_tuple = (
    races.BladelingRace,
    races.BugbearRace,
    races.DevaRace,
    races.DoppelgangerRace,
    races.DragonbornRace,
    races.DrowRace,
    races.DuergarRace,
    races.DwarfRace,
    races.EladrinRace,
    races.ElfRace,
    races.GenasiEarthsoulRace,
    races.GenasiFiresoulRace,
    races.GenasiStormsoulRace,
    races.GenasiWatersoulRace,
    races.GenasiWindsoulRace,
    races.GithzeraiRace,
    races.GnollRace,
    races.GnomeRace,
    races.GoblinRace,
    races.GoliathRace,
    races.HalfelfRace,
    races.HalflingRace,
    races.HalforcRace,
    races.HamadryadRace,
    races.HobgoblinRace,
    races.HumanRace,
    races.KalashtarRace,
    races.KenkuRace,
    races.KoboldRace,
    races.MinotaurRace,
    races.MulRace,
    races.OrcRace,
    races.PixieRace,
    races.SatyrRace,
    races.ShadarKaiRace,
    races.ShifterLongteethRace,
    races.ShifterRazorclawRace,
    races.Thri_kreenRace,
    races.TieflingRace,
    races.VrylokaRace,
    races.WarforgedRace,
    races.WildenRace,
)

race_classes = {cls.slug.name: cls for cls in races_tuple}


npc_klasses = {
    cls.slug.value: cls
    for cls in (
        npc_classes.ArtificerClass,
        npc_classes.AvengerClass,
        npc_classes.BarbarianClass,
        npc_classes.BardClass,
        npc_classes.DruidClass,
        npc_classes.FighterClass,
        npc_classes.InvokerClass,
        npc_classes.PaladinClass,
        npc_classes.PriestClass,
        npc_classes.RangerMarksmanClass,
        npc_classes.RangerMeleeClass,
        npc_classes.RogueClass,
        npc_classes.RunepriestClass,
        npc_classes.SeekerClass,
        npc_classes.ShamanClass,
        npc_classes.SorcererClass,
        npc_classes.SwordmageClass,
        npc_classes.VampireClass,
        npc_classes.WardenClass,
        npc_classes.WarlockClass,
        npc_classes.WarlordClass,
        npc_classes.WizardClass,
    )
}
