from base.objects import races

races_tuple = {
    races.BladelingRace,
    races.BugbearRace,
    races.DevaRace,
    races.DoppelgangerRace,
    races.DragonbornRace,
    races.DrowRace,
    races.DuergarRace,
    races.DwarfRace,
    races.EladrinRace,
    races.ElfRace,
    races.GenasiEarthsoulRace,
    races.GenasiFiresoulRace,
    races.GenasiStormsoulRace,
    races.GenasiWatersoulRace,
    races.GenasiWindsoulRace,
    races.GithzeraiRace,
    races.GnollRace,
    races.GnomeRace,
    races.GoblinRace,
    races.GoliathRace,
    races.HalfelfRace,
    races.HalflingRace,
    races.HalforcRace,
    races.HamadryadRace,
    races.HobgoblinRace,
    races.HumanRace,
    races.KalashtarRace,
    races.KenkuRace,
    races.KoboldRace,
    races.MinotaurRace,
    races.MulRace,
    races.OrcRace,
    races.PixieRace,
    races.SatyrRace,
    races.ShadarKaiRace,
    races.ShifterLongteethRace,
    races.ShifterRazorclawRace,
    races.Thri_kreenRace,
    races.TieflingRace,
    races.VrylokaRace,
    races.WarforgedRace,
    races.WildenRace,
}

race_classes = {cls.slug.name: cls for cls in races_tuple}
