# Generated by Django 3.1.7 on 2021-03-05 19:27

import base.models.mixins.attacks
import base.models.mixins.attributes
import base.models.mixins.defences
import base.models.mixins.skills
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('armor_type', models.SmallIntegerField(choices=[(10, 'Тканевый'), (20, 'Кожаный'), (30, 'Шкурный'), (40, 'Кольчуга'), (50, 'Чешуйчатый'), (60, 'Латный')], verbose_name='Тип')),
                ('armor_class', models.SmallIntegerField(default=0, verbose_name='Класс доспеха')),
                ('enchantment', models.SmallIntegerField(default=0, verbose_name='Улучшение')),
                ('speed_penalty', models.SmallIntegerField(default=0, verbose_name='Штраф скорости')),
                ('skill_penalty', models.SmallIntegerField(default=0, verbose_name='Штраф навыков')),
            ],
            options={
                'verbose_name': 'Доспех',
                'verbose_name_plural': 'Доспехи',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SmallIntegerField(choices=[(10, 'Апостол'), (20, 'Артефактор'), (30, 'Бард'), (35, 'Вампир'), (40, 'Варвар'), (50, 'Военачальник'), (60, 'Воин'), (70, 'Волшебник'), (80, 'Друид'), (90, 'Жрец'), (95, 'Ловчий'), (100, 'Каратель'), (110, 'Колдун'), (120, 'Мечник-маг'), (130, 'Паладин'), (140, 'Плут'), (150, 'Рунный жрец'), (160, 'Следопыт (Дальнобойный)'), (170, 'Следопыт (Рукопашник)'), (180, 'Хранитель'), (190, 'Чародей'), (200, 'Шаман')], unique=True, verbose_name='Название')),
                ('power_source', models.CharField(choices=[('MARTIAL', 'Воинский'), ('DIVINE', 'Духовный'), ('ARCANE', 'Магический'), ('PRIMAL', 'Первородный'), ('PSIONIC', 'Псионический'), ('SHADOW', 'Теневой')], max_length=7, null=True, verbose_name='Источник силы')),
                ('subclasses', models.SmallIntegerField(default=0, verbose_name='Количество подклассов')),
                ('fortitude_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус стойкости')),
                ('reflex_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус реакции')),
                ('will_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус воли')),
                ('trained_skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACROBATICS', 'Акробатика'), ('ATHLETICS', 'Атлетика'), ('INSIGHT', 'Внимательность'), ('THIEVERY', 'Воровство'), ('ENDURANCE', 'Выносливость'), ('INTIMIDATE', 'Запугивание'), ('STREETWISE', 'Знание улиц'), ('HISTORY', 'История'), ('ARCANA', 'Магия'), ('BLUFF', 'Обман'), ('DIPLOMACY', 'Переговоры'), ('DUNGEONEERING', 'Подземелья'), ('NATURE', 'Природа'), ('PERCEPTION', 'Проницательность'), ('RELIGION', 'Религия'), ('STEALTH', 'Скрытность'), ('HEAL', 'Целительство')], max_length=154, null=True, verbose_name='Тренированные навыки')),
                ('available_armor_types', multiselectfield.db.fields.MultiSelectField(choices=[(10, 'Тканевый'), (20, 'Кожаный'), (30, 'Шкурный'), (40, 'Кольчуга'), (50, 'Чешуйчатый'), (60, 'Латный')], default=10, max_length=17, verbose_name='Ношение доспехов')),
                ('available_shield_types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')], max_length=11, null=True, verbose_name='Ношение щитов')),
                ('available_weapon_categories', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Простое рукопашное'), (2, 'Воинское рукопашное'), (3, 'Превосходное рукопашное'), (4, 'Простое дальнобойное'), (5, 'Воинское дальнобойное'), (6, 'Превосходное дальнобойное')], max_length=11, null=True, verbose_name='Владение категориями оружия')),
                ('hit_points_per_level', models.PositiveSmallIntegerField(default=8, verbose_name='Хитов за уровень')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='FunctionalTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('min_level', models.SmallIntegerField(default=0, verbose_name='Минимальный уровень')),
                ('armor_class_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус КД')),
                ('fortitude_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус стойкости')),
                ('reflex_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус реакции')),
                ('will_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус воли')),
                ('save_bonus', models.SmallIntegerField(default=2, verbose_name='Бонус спасбросков')),
                ('action_points_bonus', models.SmallIntegerField(default=1, verbose_name='Дополнительные очки действия')),
                ('hit_points_per_level', models.SmallIntegerField(default=8, verbose_name='Хиты за уровень')),
            ],
            options={
                'verbose_name': 'Функциональный шаблон',
                'verbose_name_plural': 'Фунециональные шаблоны',
            },
        ),
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('enchantment', models.SmallIntegerField(default=0, verbose_name='Улучшение')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('frequency', models.CharField(choices=[('PASSIVE', 'Пассивный'), ('AT_WILL', 'Неограниченный'), ('ENCOUNTER', 'На сцену'), ('DAYLY', 'На день')], max_length=9, verbose_name='Частота использования')),
                ('action_type', models.CharField(choices=[('STANDARD', 'Стандартное действие'), ('MINOR', 'Малое действие'), ('FREE', 'Свободное действие'), ('MOVEMENT', 'Действие движения'), ('PROVOKED', 'Провоцированное действие'), ('INTERRUPT', 'Немедленное прерывание'), ('REACTION', 'Немедленный ответ'), ('NO_ACTION', 'Нет действия')], default='STANDARD', max_length=9, null=True, verbose_name='Действие')),
                ('level', models.SmallIntegerField(default=0, verbose_name='Уровень')),
                ('attack_attribute', models.CharField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=12, null=True, verbose_name='Атакующая характеристика')),
                ('attack_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус атаки')),
                ('defence', models.CharField(blank=True, choices=[('ARMOR_CLASS', 'КД'), ('FORTITUDE', 'Стойкость'), ('REFLEX', 'Реакция'), ('WILL', 'Воля')], max_length=11, null=True, verbose_name='Против защиты')),
                ('effect_type', multiselectfield.db.fields.MultiSelectField(choices=[('NONE', ''), ('ZONE', 'Зона'), ('CONJURATION', 'Иллюзия'), ('HEALING', 'Исцеление'), ('RELIABLE', 'Надежный'), ('CHARM', 'Очарование'), ('POLYMORPH', 'Превращение'), ('SLEEP', 'Сон'), ('STANCE', 'Стойка'), ('FEAR', 'Страх'), ('TELEPORTATION', 'Телепортация'), ('RATTLING', 'Ужасающий'), ('INVIGORATING', 'Укрепляющий')], default='NONE', max_length=108, verbose_name='Тип эффекта')),
                ('damage_type', multiselectfield.db.fields.MultiSelectField(choices=[('NONE', ''), ('THUNDER', 'Звук'), ('RADIANT', 'Излучение'), ('ACID', 'Кислота'), ('NECROTIC', 'Некротическая энергия'), ('FIRE', 'Огонь'), ('PSYCHIC', 'Психическая энергия'), ('COLD', 'Холод'), ('LIGHTNING', 'Электричество'), ('POISON', 'Яд')], default='NONE', max_length=69, verbose_name='Тип урона')),
                ('dice_number', models.SmallIntegerField(default=1, verbose_name='Количество кубов')),
                ('damage_dice', models.SmallIntegerField(blank=True, choices=[(4, 'k4'), (6, 'k6'), (8, 'k8'), (10, 'k10'), (12, 'k12'), (20, 'k20'), (100, 'k100')], null=True, verbose_name='Кость урона')),
                ('accessory_type', models.CharField(blank=True, choices=[('IMPLEMENT', 'Инструмент'), ('WEAPON', 'Оружие')], max_length=9, null=True, verbose_name='Тип вооружения')),
                ('range_type', models.CharField(choices=[('MELEE_WEAPON', 'Рукопашное оружие'), ('MELEE_DISTANCE', 'Рукопашное (дистанция)'), ('MELEE_TOUCH', 'Рукопашное касание'), ('MELEE_RANGED_WEAPON', 'Рукопашное или дальнобойное оружие'), ('PERSONAL', 'Персональный'), ('RANGED_WEAPON', 'Дальнобойное оружие'), ('RANGED_DISTANCE', 'Дальнобойное (дистанция)'), ('RANGED_SIGHT', 'Дальнобойное (видимость)'), ('CLOSE_BURST', 'Ближняя вспышка'), ('CLOSE_BLAST', 'Ближняя волна'), ('AREA_BURST', 'Зональная вспышка'), ('AREA_WALL', 'Стена')], default='PERSONAL', max_length=19, verbose_name='Дальность')),
                ('range', models.SmallIntegerField(default=1, verbose_name='Дальность')),
                ('burst', models.SmallIntegerField(default=0, verbose_name='Площадь')),
                ('hit_effect', models.TextField(blank=True, null=True, verbose_name='Попадание')),
                ('miss_effect', models.TextField(blank=True, null=True, verbose_name='Промах')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='Эффект')),
                ('trigger', models.TextField(blank=True, null=True, verbose_name='Триггер')),
                ('requirement', models.TextField(blank=True, null=True, verbose_name='Требование')),
                ('target', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цель')),
                ('functional_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='base.functionaltemplate', verbose_name='Функциональный шаблон')),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='base.class', verbose_name='Класс')),
                ('parent_power', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.power', verbose_name='Родительский талант')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('prof_bonus', models.SmallIntegerField(default=2, verbose_name='Бонус владения')),
                ('group', multiselectfield.db.fields.MultiSelectField(choices=[('CROSSBOW', 'Арбалет'), ('MACE', 'Булава'), ('POLEARM', 'Древковое'), ('PICK', 'Кирка'), ('SPEAR', 'Копьё'), ('BOW', 'Лук'), ('LIGHT_BLADE', 'Лёгкий клинок'), ('HAMMER', 'Молот'), ('STAFF', 'Посох'), ('SLING', 'Праща'), ('AXE', 'Топор'), ('HEAVY_BLADE', 'Тяжелый клинок'), ('FLAIL', 'Цеп')], max_length=89, verbose_name='Группа оружия')),
                ('category', models.SmallIntegerField(choices=[(1, 'Простое рукопашное'), (2, 'Воинское рукопашное'), (3, 'Превосходное рукопашное'), (4, 'Простое дальнобойное'), (5, 'Воинское дальнобойное'), (6, 'Превосходное дальнобойное')], verbose_name='Категория')),
                ('dice_number', models.SmallIntegerField(default=1, verbose_name='Количество кубов')),
                ('damage_dice', models.SmallIntegerField(blank=True, choices=[(4, 'k4'), (6, 'k6'), (8, 'k8'), (10, 'k10'), (12, 'k12'), (20, 'k20'), (100, 'k100')], null=True, verbose_name='Кость урона')),
                ('properties', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('HIGH_CRIT', 'Высококритичное'), ('OFF_HAND', 'Дополнительное'), ('REACH', 'Досягаемость'), ('LOAD_MINOR', 'Зарядка малым'), ('LOAD_FREE', 'Зарядка свободным'), ('LIGHT_THROWN', 'Лёгкое метательное'), ('SMALL', 'Маленький'), ('HEAVY_THROWN', 'Тяжелое метательное'), ('VERSATILE', 'Универсальное')], max_length=87, null=True, verbose_name='Свойства')),
                ('handedness', models.CharField(choices=[('ONE', 'Одноручное'), ('TWO', 'Двуручное')], default='ONE', max_length=3, verbose_name='Одноручное/Двуручное')),
                ('range', models.SmallIntegerField(default=0, verbose_name='Дальность')),
            ],
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('enchantment', models.SmallIntegerField(default=0, verbose_name='Улучшение')),
                ('weapon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.weapontype', verbose_name='Тип оружия')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BUGBEAR', 'Багбир'), ('VRYLOKA', 'Врылока'), ('HAMADRYAD', 'Гамадриада'), ('GITHZERAI', 'Гитзерай'), ('GNOLL', 'Гнолл'), ('GNOME', 'Гном'), ('GOBLIN', 'Гоблин'), ('GOLIATH', 'Голиаф'), ('DWARF', 'Дварф'), ('DEVA', 'Дев'), ('GENASI_WINDSOUL', 'Дженази, ветер'), ('GENASI_WATERSOUL', 'Дженази, вода'), ('GENASI_EARTHSOUL', 'Дженази, земля'), ('GENASI_FIRESOUL', 'Дженази, огонь'), ('GENASI_STORMSOUL', 'Дженази, шторм'), ('WILDEN', 'Дикарь'), ('DOPPELGANGER', 'Доппельгангер'), ('DRAGONBORN', 'Драконорожденный'), ('DROW', 'Дроу'), ('DUERGAR', 'Дуэргар'), ('KALASHTAR', 'Калаштар'), ('KENKU', 'Кенку'), ('KOBOLD', 'Кобольд'), ('WARFORGED', 'Кованый'), ('BLADELING', 'Лезвие'), ('MINOTAUR', 'Минотавр'), ('MUL', 'Мул'), ('ORC', 'Орк'), ('PIXIE', 'Пикси'), ('HALFORC', 'Полуорк'), ('HALFLING', 'Полурослик'), ('HALFELF', 'Полуэльф'), ('SATYR', 'Сатир'), ('TIEFLING', 'Тифлинг'), ('THRI_KREEN', 'Три-крин'), ('HOBGOBLIN', 'Хобгоблин'), ('HUMAN', 'Человек'), ('SHADAR_KAI', 'Шадар-Кай'), ('SHIFTER_RAZORCLAW', 'Шифтер, бритволапый'), ('SHIFTER_LONGTEETH', 'Шифтер, длиннозубый'), ('ELADRIN', 'Эладрин'), ('ELF', 'Эльф')], max_length=17, unique=True, verbose_name='Название')),
                ('speed', models.PositiveSmallIntegerField(default=6, verbose_name='Скорость')),
                ('const_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Обязательные бонусы характеристик')),
                ('var_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Выборочные бонусы характеристик')),
                ('size', models.CharField(choices=[('TINY', 'Крошечный'), ('SMALL', 'Маленький'), ('AVERAGE', 'Средний'), ('BIG', 'Большой'), ('LARGE', 'Огромный')], default='AVERAGE', max_length=7, verbose_name='Размер')),
                ('vision', models.CharField(choices=[('NORMAL', 'Обычное'), ('TWILIGHT', 'Сумеречное'), ('DARK', 'Тёмное')], default='TWILIGHT', max_length=8, verbose_name='Зрение')),
                ('fortitude_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус стойкости')),
                ('reflex_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус реакции')),
                ('will_bonus', models.SmallIntegerField(default=0, verbose_name='Бонус воли')),
                ('skill_bonuses', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACROBATICS', 'Акробатика'), ('ATHLETICS', 'Атлетика'), ('INSIGHT', 'Внимательность'), ('THIEVERY', 'Воровство'), ('ENDURANCE', 'Выносливость'), ('INTIMIDATE', 'Запугивание'), ('STREETWISE', 'Знание улиц'), ('HISTORY', 'История'), ('ARCANA', 'Магия'), ('BLUFF', 'Обман'), ('DIPLOMACY', 'Переговоры'), ('DUNGEONEERING', 'Подземелья'), ('NATURE', 'Природа'), ('PERCEPTION', 'Проницательность'), ('RELIGION', 'Религия'), ('STEALTH', 'Скрытность'), ('HEAL', 'Целительство')], max_length=154, null=True, verbose_name='Бонусы навыков')),
                ('available_weapon_types', models.ManyToManyField(blank=True, to='base.WeaponType', verbose_name='Владение оружием')),
            ],
            options={
                'verbose_name': 'Раса',
                'verbose_name_plural': 'Расы',
            },
        ),
        migrations.CreateModel(
            name='PowerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('ATTACK', 'Атака'), ('SPECIAL', 'Особенность'), ('HIT', 'Попадание'), ('MISS', 'Промах'), ('REQUIREMENT', 'Требование'), ('TRIGGER', 'Триггер'), ('EFFECT', 'Эффект')], max_length=11, null=True)),
                ('subclass', models.SmallIntegerField(choices=[], default=0, verbose_name='Подкласс')),
                ('description', models.TextField(verbose_name='Описание')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.power', verbose_name='Талант')),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powers', to='base.race', verbose_name='Раса'),
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subclass', models.SmallIntegerField(choices=[], default=0, verbose_name='Подкласс')),
                ('sex', models.CharField(choices=[('M', 'Муж'), ('F', 'Жен'), ('N', 'Н/Д')], max_length=1, verbose_name='Пол')),
                ('level', models.PositiveSmallIntegerField(verbose_name='Уровень')),
                ('base_strength', models.SmallIntegerField(verbose_name='Сила (базовая)')),
                ('base_constitution', models.SmallIntegerField(verbose_name='Телосложение (базовое)')),
                ('base_dexterity', models.SmallIntegerField(verbose_name='Ловкость (базовая)')),
                ('base_intelligence', models.SmallIntegerField(verbose_name='Интеллект (базовый)')),
                ('base_wisdom', models.SmallIntegerField(verbose_name='Мудрость (базовая)')),
                ('base_charisma', models.SmallIntegerField(verbose_name='Харизма (базовая)')),
                ('var_bonus_attr', models.CharField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=12, null=True, verbose_name='Выборочный бонус характеристики')),
                ('level4_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 4 уровне')),
                ('level8_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 8 уровне')),
                ('level14_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 14 уровне')),
                ('level18_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 18 уровне')),
                ('level24_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 24 уровне')),
                ('level28_bonus_attrs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('STRENGTH', 'Сила'), ('CONSTITUTION', 'Телосложение'), ('DEXTERITY', 'Ловкость'), ('INTELLIGENCE', 'Интеллект'), ('WISDOM', 'Мудрость'), ('CHARISMA', 'Харизма')], max_length=60, null=True, verbose_name='Бонус характеристики на 28 уровне')),
                ('trained_skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ACROBATICS', 'Акробатика'), ('ATHLETICS', 'Атлетика'), ('INSIGHT', 'Внимательность'), ('THIEVERY', 'Воровство'), ('ENDURANCE', 'Выносливость'), ('INTIMIDATE', 'Запугивание'), ('STREETWISE', 'Знание улиц'), ('HISTORY', 'История'), ('ARCANA', 'Магия'), ('BLUFF', 'Обман'), ('DIPLOMACY', 'Переговоры'), ('DUNGEONEERING', 'Подземелья'), ('NATURE', 'Природа'), ('PERCEPTION', 'Проницательность'), ('RELIGION', 'Религия'), ('STEALTH', 'Скрытность'), ('HEAL', 'Целительство')], max_length=154, null=True, verbose_name='Тренированные навыки')),
                ('shield', models.CharField(blank=True, choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')], max_length=5, null=True, verbose_name='Щит')),
                ('armor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.armor', verbose_name='Доспехи')),
                ('functional_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.functionaltemplate', verbose_name='Функциональный шаблон')),
                ('implements', models.ManyToManyField(blank=True, to='base.Implement', verbose_name='Инструменты')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class', verbose_name='Класс')),
                ('powers', models.ManyToManyField(blank=True, to='base.Power')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.race', verbose_name='Раса')),
                ('weapons', models.ManyToManyField(blank=True, to='base.Weapon', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCS',
            },
            bases=(base.models.mixins.defences.DefenceMixin, base.models.mixins.attacks.AttackMixin, base.models.mixins.attributes.AttributeMixin, base.models.mixins.skills.SkillMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImplementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Название')),
                ('inherited_weapon_type', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='implement_type', to='base.weapontype', verbose_name='На основании оружия')),
            ],
            options={
                'verbose_name': 'Тип инструмента',
                'verbose_name_plural': 'Типы инструментов',
            },
        ),
        migrations.AddField(
            model_name='implement',
            name='implement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.implementtype'),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(blank=True, max_length=30, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('npcs', models.ManyToManyField(to='base.NPC', verbose_name='Мастерские персонажи')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='available_implement_types',
            field=models.ManyToManyField(blank=True, to='base.ImplementType', verbose_name='Доступные инструменты'),
        ),
        migrations.AddField(
            model_name='class',
            name='available_weapon_types',
            field=models.ManyToManyField(blank=True, to='base.WeaponType', verbose_name='Владение оружием'),
        ),
    ]
