# Generated by Django 5.1.2 on 2024-11-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'base_armor_type',
                    models.SmallIntegerField(
                        choices=[
                            (0, 'Тканевый'),
                            (2, 'Кожаный'),
                            (3, 'Шкурный'),
                            (6, 'Кольчуга'),
                            (7, 'Чешуйчатый'),
                            (8, 'Латный'),
                        ],
                        verbose_name='Armor type',
                    ),
                ),
                (
                    'bonus_armor_class',
                    models.SmallIntegerField(
                        default=0,
                        help_text='For high level magic armor',
                        verbose_name='Additional armor class',
                    ),
                ),
                (
                    'speed_penalty',
                    models.SmallIntegerField(default=0, verbose_name='Speed penalty'),
                ),
                (
                    'skill_penalty',
                    models.SmallIntegerField(default=0, verbose_name='Skills penalty'),
                ),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
            },
        ),
        migrations.AlterModelOptions(
            name='magicitemtype',
            options={
                'verbose_name': 'Magic item type',
                'verbose_name_plural': 'Magic item types',
            },
        ),
        migrations.RemoveField(
            model_name='armor',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='armsslotitem',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='simplemagicitem',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='bonus',
        ),
    ]
