# Generated by Django 5.1.4 on 2024-12-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilitycondition',
            name='default_feats',
        ),
        migrations.AddField(
            model_name='skill',
            name='is_penalty_applied',
            field=models.BooleanField(default=False),
        ),
    ]
