# Generated by Django 5.1.3 on 2024-12-03 21:20

import django.db.models.deletion
from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='power',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    'frequency': base.constants.constants.PowerFrequencyEnum['PASSIVE'],
                    'level': 0,
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bonuses',
                related_query_name='bonus',
                to='base.power',
                verbose_name='Power',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='action_type',
            field=models.CharField(
                choices=[
                    ('STANDARD', 'Стандартное действие'),
                    ('MINOR', 'Малое действие'),
                    ('FREE', 'Свободное действие'),
                    ('MOVEMENT', 'Действие движения'),
                    ('PROVOKED', 'Провоцированное действие'),
                    ('INTERRUPT', 'Немедленное прерывание'),
                    ('REACTION', 'Немедленный ответ'),
                    ('NO_ACTION', 'Нет действия'),
                ],
                default=base.constants.constants.PowerActionTypeEnum['STANDARD'],
                help_text='Choose, if power frequency is not passive',
                max_length=9,
                null=True,
                verbose_name='Action type',
            ),
        ),
    ]
