# Generated by Django 4.0.1 on 2022-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='turn_number',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='Номер хода'
            ),
        ),
    ]
