# Generated by Django 3.1.7 on 2021-03-19 08:43

import django.db.models.deletion
from django.db import migrations, models


def migrate_targets(apps, schema_editor):
    PowerTarget = apps.get_model('base', 'PowerTarget')
    Power = apps.get_model('base', 'Power')
    for power in Power.objects.all():
        if power.target:
            try:
                target = PowerTarget.objects.get(target=power.target)
            except PowerTarget.DoesNotExist:
                target = PowerTarget(target=power.target)
                target.save()
            power.target_fkey = target
            power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerTarget',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'target',
                    models.CharField(max_length=50, unique=True, verbose_name='Цель'),
                ),
            ],
        ),
        migrations.AddField(
            model_name='power',
            name='target_fkey',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.powertarget',
                verbose_name='Цель',
            ),
        ),
        migrations.RunPython(migrate_targets),
    ]
