# Generated by Django 4.0.2 on 2022-02-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandsSlotItem',
        ),
        migrations.AddField(
            model_name='npc',
            name='no_hand',
            field=models.ForeignKey(
                blank=True,
                help_text="Armament that doesn't take hand slot",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='in_no_hands',
                to='base.weapon',
                verbose_name='No hand implement',
            ),
        ),
        migrations.CreateModel(
            name='HandsSlotItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('level', models.SmallIntegerField(default=0, verbose_name='Level')),
                (
                    'shield',
                    models.CharField(
                        blank=True,
                        choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')],
                        max_length=5,
                        null=True,
                        verbose_name='Shield',
                    ),
                ),
                (
                    'magic_item_type',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.magicitemtype',
                        verbose_name='Magic item type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Hand item/shield',
                'verbose_name_plural': 'Hand items/shields',
            },
        ),
        migrations.AlterField(
            model_name='NPC',
            name='hands_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='npc_hands',
                to='base.handsslotitem',
                verbose_name='Hands slot',
            ),
        ),
    ]
