# Generated by Django 5.1.4 on 2025-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='default_powers',
            field=models.ManyToManyField(
                blank=True, to='base.power', verbose_name='Default powers'
            ),
        ),
        migrations.AddField(
            model_name='subclass',
            name='default_powers',
            field=models.ManyToManyField(
                blank=True,
                related_name='subclasses_many',
                to='base.power',
                verbose_name='Default powers',
            ),
        ),
    ]
