# Generated by Django 3.0.5 on 2020-11-08 06:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='const_bonus_atrs',
        ),
        migrations.RemoveField(
            model_name='race',
            name='var_bonus_atrs',
        ),
        migrations.AddField(
            model_name='npc',
            name='var_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='race',
            name='const_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='race',
            name='var_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(
                choices=[
                    ('TINY', 'Крошечный'),
                    ('SMALL', 'Маленький'),
                    ('AVERAGE', 'Средний'),
                    ('BIG', 'Большой'),
                    ('LARGE', 'Огромный'),
                ],
                default='AVERAGE',
                max_length=10,
            ),
        ),
    ]
