# Generated by Django 5.1.3 on 2024-12-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='hit_points_per_level',
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name='Hit points per level'
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='hit_points_per_level_npc',
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name='Hit points per level'
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='surges',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Surges'),
        ),
    ]
