# Generated by Django 5.1.4 on 2025-02-13 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                (
                    'code',
                    models.CharField(max_length=10, unique=True, verbose_name='Code'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='BookSource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'book_number',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Book number'
                    ),
                ),
                (
                    'page_number',
                    models.PositiveSmallIntegerField(verbose_name='Page number'),
                ),
                (
                    'is_english',
                    models.BooleanField(default=False, verbose_name='Is English?'),
                ),
                (
                    'book',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.book',
                        verbose_name='Book',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Book source',
                'verbose_name_plural': 'Book sources',
                'unique_together': {
                    ('book', 'book_number', 'page_number', 'is_english')
                },
            },
        ),
    ]
