# Generated by Django 5.1.3 on 2024-12-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='prof_bonus',
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name='Prof bonus'
            ),
        ),
    ]
