# Generated by Django 5.1.4 on 2024-12-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='is_sociable',
            new_name='is_social',
        ),
    ]
