# Generated by Django 5.2.1 on 2025-05-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='range_type',
            field=models.CharField(
                choices=[
                    ('MELEE_WEAPON', 'Рукопашное оружие'),
                    ('MELEE', 'Рукопашное'),
                    ('RANGED', 'Дальнобойный'),
                    ('MELEE_RANGED_WEAPON', 'Рукопашное или дальнобойное оружие'),
                    ('RANGED_WEAPON', 'Дальнобойное оружие'),
                    ('BURST', 'Вспышка'),
                    ('BLAST', 'Волна'),
                    ('WALL', 'Стена'),
                    ('PERSONAL', 'Персональный'),
                ],
                default='PERSONAL',
                max_length=19,
                verbose_name='Range type',
            ),
        ),
    ]
