# Generated by Django 5.1.2 on 2024-11-17 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_armortype_alter_magicitemtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armortype',
            options={
                'verbose_name': 'Armor type',
                'verbose_name_plural': 'Armor types',
            },
        ),
        migrations.AlterModelOptions(
            name='powerproperty',
            options={
                'verbose_name': 'Power Property',
                'verbose_name_plural': 'Power Properties',
            },
        ),
    ]
