# Generated by Django 5.1.4 on 2024-12-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_npc_trained_skills_alter_npc_var_bonus_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitycondition',
            name='constraint',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='availability_condition',
                to='base.constraint',
            ),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('PERCEPTION', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('INSIGHT', 'Проницательность'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                    ('ARMOR_CLASS', 'КД'),
                    ('FORTITUDE', 'Стойкость'),
                    ('REFLEX', 'Реакция'),
                    ('WILL', 'Воля'),
                    ('SPEED', 'Скорость'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGE', 'Значение исцеления'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('ATTACK', 'Атака'),
                    ('DAMAGE', 'Урон'),
                ],
                max_length=13,
                null=True,
                verbose_name='Bonus type',
            ),
        ),
        migrations.AlterField(
            model_name='propertiescondition',
            name='type',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('SURGE', 'Значение исцеления'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('SPEED', 'Скорость'),
                ],
                max_length=12,
                verbose_name='Property type',
            ),
        ),
        migrations.CreateModel(
            name='ItemCondition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'constraint',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='item_condition',
                        to='base.constraint',
                    ),
                ),
            ],
        ),
    ]
