# Generated by Django 5.2 on 2025-05-04 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magicitemtype',
            options={
                'ordering': ('name',),
                'verbose_name': 'Magic item type',
                'verbose_name_plural': 'Magic item types',
            },
        ),
        migrations.AlterModelOptions(
            name='paragonpath',
            options={
                'ordering': ('title',),
                'verbose_name': 'Paragon path',
                'verbose_name_plural': 'Paragon paths',
            },
        ),
        migrations.AlterField(
            model_name='power',
            name='subclass',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'subclass_id__gt': 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.subclass',
                verbose_name='Subclass',
            ),
        ),
    ]
