# Generated by Django 3.1.7 on 2021-03-19 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210319_0843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powertarget',
            options={
                'verbose_name': 'Цель таланта',
                'verbose_name_plural': 'Цели талантов',
            },
        ),
        migrations.RemoveField(
            model_name='power',
            name='target',
        ),
    ]
