# Generated by Django 5.1.6 on 2025-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.SmallIntegerField(
                choices=[
                    (-1, 'Крошечный'),
                    (0, 'Маленький'),
                    (1, 'Средний'),
                    (2, 'Большой'),
                    (3, 'Огромный'),
                    (4, 'Гигантский'),
                ],
                default=1,
                verbose_name='Size',
            ),
        ),
    ]
