# Generated by Django 3.0.5 on 2020-11-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201108_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='charisma',
            new_name='base_charisma',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='constitution',
            new_name='base_constitution',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='dexterity',
            new_name='base_dexterity',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='intelligence',
            new_name='base_intelligence',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='strength',
            new_name='base_strength',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='wisdom',
            new_name='base_wisdom',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='powers',
        ),
        migrations.AddField(
            model_name='npc',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
