# Generated by Django 5.1.4 on 2024-12-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_is_sociable_race_is_social'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to={
                    'app_label': 'base',
                    'model__in': (
                        'race',
                        'class',
                        'subclass',
                        'functionaltemplate',
                        'paragonpath',
                        'feat',
                        'power',
                        'skill',
                    ),
                },
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AlterField(
            model_name='propertiescondition',
            name='type',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('SURGE', 'Значение исцеления'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('SPEED', 'Скорость'),
                    ('POWER_SOURCE', 'Источник силы'),
                ],
                max_length=12,
                verbose_name='Property type',
            ),
        ),
    ]
