# Generated by Django 4.0.1 on 2022-01-25 19:39

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_encounter_turn_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitem',
            name='slots',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('armor', 'Броня'),
                    ('head', 'Голова'),
                    ('ring', 'Кольца'),
                    ('feet', 'Обувь'),
                    ('weapon', 'Оружие'),
                    ('hands', 'Перчатки'),
                    ('waist', 'Пояс'),
                    ('arms', 'Предплечья/Щит'),
                    ('tatoo', 'Татуировка'),
                    ('wondrous_items', 'Чудесный предмет'),
                    ('neck', 'Шея'),
                ],
                max_length=70,
                null=True,
                verbose_name='Слоты',
            ),
        ),
    ]
