# Generated by Django 4.0.2 on 2022-02-12 17:07

from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_delete_handsslotitem_npc_no_hand_handsslotitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='handsslotitem',
            options={
                'verbose_name': 'Предмет на руки/щит',
                'verbose_name_plural': 'Предметы на руки/щиты',
            },
        ),
        migrations.AlterField(
            model_name='handsslotitem',
            name='shield',
            field=models.CharField(
                choices=[(0, '----------'), (1, 'Лёгкий щит'), (2, 'Тяжелый щит')],
                default=base.constants.constants.ShieldTypeIntEnum['NONE'],
                max_length=5,
                verbose_name='Shield',
            ),
        ),
    ]
