# Generated by Django 5.1.3 on 2024-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_class_hit_points_per_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='available_weapon_types',
            field=models.ManyToManyField(
                to='base.weapontype', verbose_name='Available weapon types'
            ),
        ),
    ]
