# Generated by Django 5.1.3 on 2024-12-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_weapontype_prof_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='dice',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (4, 'k4'),
                    (6, 'k6'),
                    (8, 'k8'),
                    (10, 'k10'),
                    (12, 'k12'),
                    (20, 'k20'),
                    (100, 'k100'),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='dice_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
