# Generated by Django 5.1.4 on 2024-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_bonus_subclass_fk_bonus_subclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Feat',
                'verbose_name_plural': 'Feats',
            },
        ),
    ]
