# Generated by Django 5.1.4 on 2025-01-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_class_default_powers_subclass_default_powers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcparty',
            name='npc_members',
            field=models.ManyToManyField(
                blank=True, to='base.npc', verbose_name='Non player characters'
            ),
        ),
        migrations.AlterField(
            model_name='pcparty',
            name='members',
            field=models.ManyToManyField(
                to='base.playercharacter', verbose_name='Player characters'
            ),
        ),
    ]
