# Generated by Django 5.1.7 on 2025-03-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='powers',
            field=models.ManyToManyField(
                blank=True, related_name='npcs', to='base.power', verbose_name='Powers'
            ),
        ),
    ]
