# Generated by Django 3.2.9 on 2021-12-08 18:16

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211207_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='damage_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('NONE', ''),
                    ('THUNDER', 'Звук'),
                    ('RADIANT', 'Излучение'),
                    ('ACID', 'Кислота'),
                    ('NECROTIC', 'Некротическая энергия'),
                    ('FIRE', 'Огонь'),
                    ('PSYCHIC', 'Психическая энергия'),
                    ('FORCE', 'Силовое поле'),
                    ('COLD', 'Холод'),
                    ('LIGHTNING', 'Электричество'),
                    ('POISON', 'Яд'),
                ],
                default='NONE',
                max_length=75,
                verbose_name='Тип урона',
            ),
        ),
    ]
