# Generated by Django 5.1.4 on 2024-12-18 08:29

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_availabilitycondition_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcondition',
            name='armor',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (0, 'Тканевый'),
                    (2, 'Кожаный'),
                    (3, 'Шкурный'),
                    (6, 'Кольчуга'),
                    (7, 'Чешуйчатый'),
                    (8, 'Латный'),
                ],
                default=0,
                max_length=11,
                verbose_name='Armor type',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='primary_hand_category',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                max_length=13,
                null=True,
                verbose_name='Primary hand category',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='primary_hand_group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('CROSSBOW', 'Арбалет'),
                    ('UNARMED', 'Безоружное'),
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('BOW', 'Лук'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('SLING', 'Праща'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=97,
                null=True,
                verbose_name='Primary hand group',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='primary_hand_type',
            field=models.ManyToManyField(
                blank=True,
                related_name='primary_hand_conditions',
                to='base.weapontype',
                verbose_name='Primary hand',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='secondary_hand_category',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                max_length=13,
                null=True,
                verbose_name='Primary hand category',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='secondary_hand_group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('CROSSBOW', 'Арбалет'),
                    ('UNARMED', 'Безоружное'),
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('BOW', 'Лук'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('SLING', 'Праща'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=11,
                null=True,
                verbose_name='Secondary hand group',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='secondary_hand_type',
            field=models.ManyToManyField(
                blank=True,
                related_name='secondary_hand_conditions',
                to='base.weapontype',
                verbose_name='Secondary hand',
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='shield',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, '----------'), (1, 'Лёгкий щит'), (2, 'Тяжелый щит')],
                default=0,
                max_length=5,
                verbose_name='Shield type',
            ),
            preserve_default=False,
        ),
    ]
