# Generated by Django 4.0.1 on 2022-01-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_magicitem_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleMagicItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('level', models.SmallIntegerField(default=0, verbose_name='Уровень')),
                (
                    'magic_item',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.magicitem',
                        verbose_name='Магический предмет',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NeckSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
    ]
