# Generated by Django 5.1.3 on 2024-12-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bonus_bonus_type_alter_power_damage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='const_ability_bonus',
            field=models.ManyToManyField(
                related_name='races_with_const',
                to='base.ability',
                verbose_name='Constant ability bonuses',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='var_ability_bonus',
            field=models.ManyToManyField(
                related_name='races',
                to='base.ability',
                verbose_name='Selective ability bonuses',
            ),
        ),
    ]
