# Generated by Django 5.1.6 on 2025-03-03 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_race_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Простое рукопашное'),
                            (2, 'Воинское рукопашное'),
                            (3, 'Превосходное рукопашное'),
                            (4, 'Простое дальнобойное'),
                            (5, 'Воинское дальнобойное'),
                            (6, 'Превосходное дальнобойное'),
                            (7, 'Инструмент'),
                        ],
                        unique=True,
                        verbose_name='Category',
                    ),
                ),
                ('is_ranged', models.BooleanField(null=True, verbose_name='Ranged')),
                (
                    'category',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Простое рукопашное'),
                            (2, 'Воинское рукопашное'),
                            (3, 'Превосходное рукопашное'),
                        ],
                        null=True,
                        unique=True,
                        verbose_name='Base category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Weapon category',
                'verbose_name_plural': 'Weapon categories',
                'ordering': (
                    'is_ranged',
                    models.Case(
                        models.When(name='AXE', then=models.Value('Топор')),
                        models.When(name='MACE', then=models.Value('Булава')),
                        models.When(
                            name='LIGHT_BLADE', then=models.Value('Лёгкий клинок')
                        ),
                        models.When(name='SPEAR', then=models.Value('Копьё')),
                        models.When(name='STAFF', then=models.Value('Посох')),
                        models.When(name='FLAIL', then=models.Value('Цеп')),
                        models.When(
                            name='HEAVY_BLADE', then=models.Value('Тяжелый клинок')
                        ),
                        models.When(name='HAMMER', then=models.Value('Молот')),
                        models.When(name='PICK', then=models.Value('Кирка')),
                        models.When(name='POLEARM', then=models.Value('Древковое')),
                        models.When(name='UNARMED', then=models.Value('Безоружное')),
                        models.When(name='SLING', then=models.Value('Праща')),
                        models.When(name='CROSSBOW', then=models.Value('Арбалет')),
                        models.When(name='BOW', then=models.Value('Лук')),
                        output_field=models.CharField(),
                    ),
                ),
            },
        ),
        migrations.AddField(
            model_name='weapontype',
            name='category_fk',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weaponcategory',
                verbose_name='Category',
            ),
        ),
    ]
