# Generated by Django 5.1.4 on 2024-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_condition_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityNew',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('INTELLIGENCE', 'Интеллект'),
                            ('DEXTERITY', 'Ловкость'),
                            ('WISDOM', 'Мудрость'),
                            ('STRENGTH', 'Сила'),
                            ('CONSTITUTION', 'Телосложение'),
                            ('CHARISMA', 'Харизма'),
                        ],
                        max_length=12,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
