# Generated by Django 5.1.4 on 2025-01-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pcparty_npc_members_alter_pcparty_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PCParty',
            new_name='Party',
        ),
    ]
