# Generated by Django 5.1.4 on 2024-12-26 15:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_availabilitycondition_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponstate',
            name='is_off_hand',
        ),
        migrations.AddField(
            model_name='weaponstate',
            name='handedness',
            field=models.CharField(
                choices=[
                    ('TWO', 'Двуручное'),
                    ('OFF_HAND', 'Дополнительное'),
                    ('FREE', 'Не занимает руки'),
                    ('ONE', 'Одноручное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                default=base.constants.constants.WeaponHandednessEnum['ONE'],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name='propertiescondition',
            name='type',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('SURGE', 'Значение исцеления'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('SPEED', 'Скорость'),
                    ('POWER_SOURCE', 'Источник силы'),
                    ('ROLE', 'Роль'),
                ],
                max_length=12,
                verbose_name='Property type',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                max_length=13,
                null=True,
                verbose_name='Weapon category',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('CROSSBOW', 'Арбалет'),
                    ('UNARMED', 'Безоружное'),
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('BOW', 'Лук'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('SLING', 'Праща'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=97,
                null=True,
                verbose_name='Weapon group',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='type',
            field=models.ManyToManyField(
                blank=True,
                related_name='primary_hand_conditions',
                to='base.weapontype',
                verbose_name='Weapon type',
            ),
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'shield',
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (0, '----------'),
                            (1, 'Лёгкий щит'),
                            (2, 'Тяжелый щит'),
                        ],
                        max_length=5,
                        null=True,
                        verbose_name='Shield type',
                    ),
                ),
                (
                    'armor',
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (0, 'Тканевый'),
                            (2, 'Кожаный'),
                            (3, 'Шкурный'),
                            (6, 'Кольчуга'),
                            (7, 'Чешуйчатый'),
                            (8, 'Латный'),
                        ],
                        max_length=11,
                        null=True,
                        verbose_name='Armor type',
                    ),
                ),
                (
                    'feat',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='item_states',
                        to='base.feat',
                    ),
                ),
                (
                    'primary_hand',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='primary_hands',
                        to='base.weaponstate',
                    ),
                ),
                (
                    'secondary_hand',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='secondary_hands',
                        to='base.weaponstate',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCondition',
        ),
    ]
