# Generated by Django 3.0.5 on 2020-11-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201108_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='level14_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='level18_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='level24_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='level28_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='level4_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='level8_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default=0,
                max_length=20,
            ),
        ),
    ]
