# Generated by Django 5.2.1 on 2025-05-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_magicitemtype_options_and_more'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombatantsMonster',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name='Участник сцены'),
                ),
                (
                    'armor_class',
                    models.PositiveSmallIntegerField(default=0, verbose_name='КД'),
                ),
                (
                    'fortitude',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Стойкость'
                    ),
                ),
                (
                    'reflex',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Реакция'),
                ),
                (
                    'will',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Воля'),
                ),
                (
                    'initiative',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Инициатива'
                    ),
                ),
                (
                    'number',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Количество однотипных'
                    ),
                ),
                (
                    'avatar',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'npc__isnull': True, 'pc__isnull': True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='printer.avatar',
                        verbose_name='Avatar',
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combatants_monsters',
                        to='base.encounter',
                        verbose_name='Сцена',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Участник сцены (Монстрятник)',
                'verbose_name_plural': 'Участники сцены (Монстрятник)',
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                (
                    'armor_class',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Armor class'
                    ),
                ),
                (
                    'fortitude',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Fortitude'
                    ),
                ),
                (
                    'reflex',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Reflex'),
                ),
                (
                    'will',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Will'),
                ),
                (
                    'initiative',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Initiative'
                    ),
                ),
                (
                    'avatar',
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={'npc__isnull': True, 'pc__isnull': True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='printer.avatar',
                        verbose_name='Avatar',
                    ),
                ),
                (
                    'source',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='base.booksource',
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name='Combatants',
        ),
    ]
