# Generated by Django 5.1.2 on 2024-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_armortype_options_alter_powerproperty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='armortype',
            name='minimal_enhancement',
            field=models.SmallIntegerField(
                default=0, verbose_name='Minimal enhancement'
            ),
        ),
    ]
