# Generated by Django 3.1.3 on 2021-01-26 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201203_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='classes',
            field=models.ManyToManyField(
                blank=True, to='base.Class', verbose_name='Классы'
            ),
        ),
        migrations.AddField(
            model_name='power',
            name='race',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.race',
                verbose_name='Раса',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('BARD', 'Бард'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER_MARKSMAN', 'Следопыт (Дальнобойный)'),
                    ('RANGER_MELEE', 'Следопыт (Рукопашник)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=15,
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
