# Generated by Django 5.2.1 on 2025-05-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_power_range_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='title',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ATTACK', 'Атака'),
                    ('OTHER', 'Другое'),
                    ('SPECIAL', 'Особенность'),
                    ('HIT', 'Попадание'),
                    ('MISS', 'Промах'),
                    ('REQUIREMENT', 'Требование'),
                    ('TRIGGER', 'Триггер'),
                    ('TARGET', 'Цель'),
                    ('EFFECT', 'Эффект'),
                ],
                max_length=11,
                null=True,
                verbose_name='Title',
            ),
        ),
    ]
