# Generated by Django 5.1.4 on 2025-02-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={
                'ordering': ('name',),
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.AlterModelOptions(
            name='booksource',
            options={
                'ordering': ('is_english', 'book', 'book_number', 'page_number'),
                'verbose_name': 'Book source',
                'verbose_name_plural': 'Book sources',
            },
        ),
    ]
