# Generated by Django 3.2.9 on 2021-12-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_power_damage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='implements',
        ),
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(
                blank=True, to='base.Weapon', verbose_name='Вооружение'
            ),
        ),
        migrations.DeleteModel(
            name='Implement',
        ),
    ]
