# Generated by Django 5.1.7 on 2025-03-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_npc_powers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='feats',
            field=models.ManyToManyField(
                blank=True, related_name='npcs', to='base.feat', verbose_name='Feats'
            ),
        ),
    ]
