# Generated by Django 5.1.4 on 2024-12-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_abilitynew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abilitynew',
            old_name='name',
            new_name='title',
        ),
    ]
