# Generated by Django 5.1.4 on 2024-12-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_itemcondition_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcondition',
            name='is_primary_hand_empty',
            field=models.BooleanField(
                default=False, verbose_name='Is primary hand empty'
            ),
        ),
        migrations.AddField(
            model_name='itemcondition',
            name='is_secondary_hand_empty',
            field=models.BooleanField(
                default=False, verbose_name='Is secondary hand empty'
            ),
        ),
    ]
