# Generated by Django 5.1.4 on 2025-01-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_pcparty_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='subclass_obj',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.subclass',
                verbose_name='Subclass',
            ),
        ),
    ]
