# Generated by Django 5.1.3 on 2024-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_race_const_ability_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Speed'),
        ),
    ]
