# Generated by Django 5.1.6 on 2025-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_weaponcategory_weapontype_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponcategory',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                ],
                null=True,
                verbose_name='Base category',
            ),
        ),
    ]
