# Generated by Django 5.1.6 on 2025-02-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20250222_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weaponstate',
            name='group',
        ),
    ]
