# Generated by Django 6.1 on 2026-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_alter_powerproperty_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='default_powers',
            field=models.ManyToManyField(
                blank=True,
                related_name='classes_with_one_as_default',
                to='base.power',
                verbose_name='Default powers',
            ),
        ),
    ]
