# Generated by Django 3.0.5 on 2020-11-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201108_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='level14_bonus_attr',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level18_bonus_attr',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level24_bonus_attr',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level28_bonus_attr',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level4_bonus_attr',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level8_bonus_attr',
        ),
    ]
