# Generated by Django 3.1.7 on 2021-03-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210319_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerproperty',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
