# Generated by Django 4.0.1 on 2022-01-26 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_simplemagicitem_neckslotitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='neck_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.neckslotitem',
                verbose_name='Предмет на шею',
            ),
        ),
    ]
