# Generated by Django 5.2.1 on 2025-05-09 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_combatantsmonster_monster_delete_combatants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombatantsPC',
            new_name='CombatantPC',
        ),
    ]
