# Generated by Django 5.1.3 on 2024-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_weapontype_brutal_weapontype_is_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='range',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
