# Generated by Django 5.1.4 on 2024-12-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_class_weapon_types_alter_subclass_weapon_types_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to={
                    'app_label': 'base',
                    'model__in': (
                        'race',
                        'class',
                        'functionaltemplate',
                        'paragonpath',
                        'magicitemtype',
                        'feat',
                    ),
                },
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.AlterField(
            model_name='constraint',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
