# Generated by Django 5.1.7 on 2025-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_npc_feats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='default_feats',
            field=models.ManyToManyField(
                blank=True,
                related_name='classes',
                to='base.feat',
                verbose_name='Default feats',
            ),
        ),
    ]
