# Generated by Django 5.1.2 on 2024-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_armortype_minimal_enhancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='armortype',
            name='name',
            field=models.CharField(
                default='Обычный', max_length=100, verbose_name='Title'
            ),
            preserve_default=False,
        ),
    ]
