# Generated by Django 4.0 on 2021-12-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211208_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
