# Generated by Django 3.1.3 on 2021-01-26 05:26

from django.db import migrations


def powers(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    for power in Power.objects.all():
        power.classes.add(power.klass)
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210126_0525'),
    ]

    operations = [migrations.RunPython(powers)]
