# Generated by Django 4.0 on 2021-12-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_armor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicalItem',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                (
                    'min_level',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Минимальный уровень'
                    ),
                ),
                (
                    'step',
                    models.PositiveSmallIntegerField(
                        default=5, verbose_name='Шаг повышения уровня'
                    ),
                ),
                (
                    'restrictions',
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name='Ограничения'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Магический предмет',
                'verbose_name_plural': 'Магические предметы',
            },
        ),
        migrations.AddField(
            model_name='power',
            name='magical_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.magicalitem',
                verbose_name='Магический предмет',
            ),
        ),
    ]
