# Generated by Django 5.1.4 on 2025-02-14 08:37

from django.db import migrations

book_mapping = {
    'КИ1': ('PHB', 1),
    'СИП': ('AV', 1),
    'ДР366': ('Dr', 366),
}


def fill_book_source(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    MagicItemType = apps.get_model('base', 'MagicItemType')
    Book = apps.get_model('base', 'Book')
    BookSource = apps.get_model('base', 'BookSource')
    for mit in MagicItemType.objects.filter(source__isnull=False):
        book_code, page = mit.source.replace('стр.', '').split('-')
        book_code, book_number = book_mapping[book_code.strip()]
        book = Book.objects.get(code=book_code)
        book_source, _ = BookSource.objects.get_or_create(
            book=book, book_number=book_number, page_number=int(page.strip())
        )
        mit.book_source = book_source
        mit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_magicitemtype_book_source'),
    ]

    operations = [migrations.RunPython(fill_book_source)]
