# Generated by Django 3.1.7 on 2021-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_powerproperty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='subclass',
            field=models.SmallIntegerField(
                choices=[], default=0, verbose_name='Подкласс'
            ),
        ),
    ]
