# Generated by Django 6.1 on 2026-08-14 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0005_alter_class_default_powers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armortype',
            name='skill_penalty',
        ),
        migrations.RemoveField(
            model_name='armortype',
            name='speed_penalty',
        ),
    ]
