# Generated by Django 5.1.3 on 2024-12-04 22:27

from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_race_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size',
            field=models.CharField(
                choices=[
                    ('TINY', 'Крошечный'),
                    ('SMALL', 'Маленький'),
                    ('AVERAGE', 'Средний'),
                    ('BIG', 'Большой'),
                    ('LARGE', 'Огромный'),
                ],
                default=base.constants.constants.SizeEnum['AVERAGE'],
                max_length=7,
                verbose_name='Size',
            ),
        ),
        migrations.AddField(
            model_name='race',
            name='vision',
            field=models.CharField(
                choices=[
                    ('NORMAL', 'Обычное'),
                    ('TWILIGHT', 'Сумеречное'),
                    ('DARK', 'Тёмное'),
                ],
                default=base.constants.constants.VisionEnum['NORMAL'],
                max_length=8,
                verbose_name='Vision',
            ),
        ),
    ]
