# Generated by Django 5.1.3 on 2024-12-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_weapontype_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='load',
            field=models.CharField(
                choices=[
                    ('FREE', 'Зарядка: Свободное действие'),
                    ('MINOR', 'Зарядка: Малое действие'),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='thrown',
            field=models.CharField(
                choices=[
                    ('LIGHT', 'Лёгкое метательное'),
                    ('HEAVY', 'Тяжёлое метательное'),
                ],
                max_length=5,
                null=True,
            ),
        ),
    ]
