# Generated by Django 5.1.4 on 2024-12-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_abilitynew_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='based_on_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.abilitynew',
            ),
        ),
    ]
