# Generated by Django 5.1.2 on 2024-11-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_armortype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armortype',
            name='bonus_armor_class',
            field=models.SmallIntegerField(
                default=0, verbose_name='Additional armor class'
            ),
        ),
    ]
