# Generated by Django 4.0.1 on 2022-01-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_npc_neck_slot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagicItem',
            new_name='MagicItemType',
        ),
        migrations.AlterModelOptions(
            name='magicitemtype',
            options={
                'verbose_name': 'Тип магического предмета',
                'verbose_name_plural': 'Типы магического предмета',
            },
        ),
    ]
