# Generated by Django 5.1.4 on 2025-01-27 15:14

from django.db import migrations, models

from base.constants.constants import PowerFrequencyIntEnum


def fill_frequency_int(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Power = apps.get_model('base', 'Power')
    for power in Power.objects.all():
        Power.frequency_int = PowerFrequencyIntEnum[Power.frequency].value
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_power_subclass_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='frequency_int',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Пассивный'),
                    (1, 'Неограниченный'),
                    (2, 'На сцену'),
                    (3, 'На день'),
                ],
                default=0,
                verbose_name='Usage frequency',
            ),
        ),
    ]
