# Generated by Django 5.1.6 on 2025-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_weaponstate_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='group',
        ),
        migrations.AddField(
            model_name='magicweapontype',
            name='weapon_groups_m2m',
            field=models.ManyToManyField(
                blank=True, to='base.weapongroup', verbose_name='Weapon group'
            ),
        ),
    ]
