# Generated by Django 5.2.1 on 2025-05-09 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_combatantspc_combatantpc'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CombatantsMonster',
            new_name='CombatantMonster',
        ),
    ]
