# Generated by Django 5.1.4 on 2024-12-27 08:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_bonus_source_alter_itemstate_primary_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstate',
            name='shield',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[(0, '----------'), (1, 'Лёгкий щит'), (2, 'Тяжелый щит')],
                max_length=5,
                null=True,
                verbose_name='Shield type',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='handedness',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('TWO', 'Двуручное'),
                    ('OFF_HAND', 'Дополнительное'),
                    ('FREE', 'Не занимает руки'),
                    ('ONE', 'Одноручное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                max_length=31,
                null=True,
            ),
        ),
    ]
