# Generated by Django 5.1.4 on 2025-01-27 15:14

from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_power_subclass_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='frequency_int',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Пассивный'),
                    (1, 'Неограниченный'),
                    (2, 'На сцену'),
                    (3, 'На день'),
                ],
                default=base.constants.constants.PowerFrequencyIntEnum['PASSIVE'],
                verbose_name='Usage frequency',
            ),
        ),
    ]
