# Generated by Django 5.1.4 on 2025-01-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_power_frequency_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='frequency',
        ),
    ]
