# Generated by Django 5.1.4 on 2024-12-27 20:44

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_itemstate_shield_alter_weaponstate_handedness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('PERCEPTION', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('INSIGHT', 'Проницательность'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                    ('ARMOR_CLASS', 'КД'),
                    ('FORTITUDE', 'Стойкость'),
                    ('REFLEX', 'Реакция'),
                    ('WILL', 'Воля'),
                    ('SPEED', 'Скорость'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGE', 'Значение исцеления'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('POWER_SOURCE', 'Источник силы'),
                    ('ROLE', 'Роль'),
                    ('SIZE', 'Размер'),
                    ('SPEED_PENALTY', 'Штраф скорости'),
                    ('SKILL_PENALTY', 'Штраф навыков'),
                    ('ATTACK', 'Атака'),
                    ('DAMAGE', 'Урон'),
                ],
                max_length=13,
                null=True,
                verbose_name='Bonus type',
            ),
        ),
        migrations.AlterField(
            model_name='propertiescondition',
            name='type',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('SURGE', 'Значение исцеления'),
                    ('INITIATIVE', 'Инициатива'),
                    ('POWER_SOURCE', 'Источник силы'),
                    ('SURGES', 'Количество исцелений'),
                    ('HIT_POINTS', 'Количество хитов'),
                    ('SIZE', 'Размер'),
                    ('ROLE', 'Роль'),
                    ('SPEED', 'Скорость'),
                    ('SKILL_PENALTY', 'Штраф навыков'),
                    ('SPEED_PENALTY', 'Штраф скорости'),
                ],
                max_length=13,
                verbose_name='Property type',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                max_length=13,
                null=True,
                verbose_name='Weapon category',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('CROSSBOW', 'Арбалет'),
                    ('UNARMED', 'Безоружное'),
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('BOW', 'Лук'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('SLING', 'Праща'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=97,
                null=True,
                verbose_name='Weapon group',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='handedness',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('OFF_HAND', 'Дополнительное'),
                    ('ONE', 'Одноручное'),
                    ('VERSATILE', 'Универсальное'),
                    ('TWO', 'Двуручное'),
                    ('FREE', 'Не занимает руки'),
                ],
                max_length=31,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='is_empty',
            field=models.BooleanField(
                blank=True, default=False, verbose_name='Is hand empty?'
            ),
        ),
    ]
