# Generated by Django 5.1.4 on 2024-12-23 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_skill_based_on_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='based_on',
        ),
    ]
