# Generated by Django 3.1.7 on 2021-03-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_power_subclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='parent_power',
        ),
    ]
