# Generated by Django 5.1.4 on 2025-02-14 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20250214_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicitemtype',
            name='source',
        ),
    ]
