# Generated by Django 5.1.3 on 2024-12-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_weapontype_load_alter_weapontype_thrown'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicweapontype',
            name='implement_type',
            field=models.ForeignKey(
                help_text='Does item has additional implement property?',
                limit_choices_to={'category': 'IMPLEMENT'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.weapontype',
                verbose_name='Implement type',
            ),
        ),
        migrations.AddField(
            model_name='magicweapontype',
            name='weapon_types',
            field=models.ManyToManyField(
                related_name='magic_weapons',
                to='base.weapontype',
                verbose_name='Weapon type',
            ),
        ),
    ]
