# Generated by Django 4.0 on 2021-12-13 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_magicalitem_power_magical_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='armor',
            name='magic_item',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.magicalitem',
                verbose_name='Магический предмет',
            ),
        ),
    ]
