# Generated by Django 4.0.1 on 2022-01-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_magicitem_magicitemtype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='magic_item',
            new_name='magic_item_type',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='magic_item',
            new_name='magic_item_type',
        ),
        migrations.RenameField(
            model_name='simplemagicitem',
            old_name='magic_item',
            new_name='magic_item_type',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='magic_item',
            new_name='magic_item_type',
        ),
        migrations.AlterUniqueTogether(
            name='weapon',
            unique_together={('magic_item_type', 'level', 'weapon_type')},
        ),
    ]
