# Generated by Django 4.0.2 on 2022-02-12 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_rename_handsslotitem_armsslotitem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='shield',
            new_name='shield_old',
        ),
        migrations.AlterField(
            model_name='npc',
            name='arms_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='npc_hands',
                to='base.armsslotitem',
                verbose_name='Arms slot',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hands_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='npc_arms',
                to='base.handsslotitem',
                verbose_name='Hands slot',
            ),
        ),
    ]
