# Generated by Django 3.0.5 on 2020-11-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201108_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='level14_bonus_attr',
            new_name='level14_bonus_attrs',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level18_bonus_attr',
            new_name='level18_bonus_attrs',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level24_bonus_attr',
            new_name='level24_bonus_attrs',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level28_bonus_attr',
            new_name='level28_bonus_attrs',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level4_bonus_attr',
            new_name='level4_bonus_attrs',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level8_bonus_attr',
            new_name='level8_bonus_attrs',
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_strength',
            field=models.PositiveSmallIntegerField(verbose_name='Сила (базовая)'),
        ),
    ]
