# Generated by Django 5.1.2 on 2024-11-17 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_armortype_bonus_armor_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='base_armor_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.armortype',
                verbose_name='Armor type',
            ),
        ),
    ]
