# Generated by Django 5.2.1 on 2025-05-09 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_combatantsmonster_combatantmonster'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatantmonster',
            name='monster',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='combatants_monsters',
                to='base.monster',
                verbose_name='Monster',
            ),
        ),
        migrations.AddField(
            model_name='encounter',
            name='monsters',
            field=models.ManyToManyField(
                blank=True,
                through='base.CombatantMonster',
                to='base.monster',
                verbose_name='Monsters',
            ),
        ),
        migrations.AddField(
            model_name='encounter',
            name='pcs',
            field=models.ManyToManyField(
                blank=True,
                through='base.CombatantPC',
                to='base.playercharacter',
                verbose_name='Player characters',
            ),
        ),
    ]
