# Generated by Django 3.1.7 on 2021-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_power_parent_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='subclass',
            field=models.SmallIntegerField(
                choices=[(0, '---------')], default=0, verbose_name='Подкласс'
            ),
        ),
    ]
