# Generated by Django 5.1.2 on 2024-11-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_armor_base_armor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='armor_type',
        ),
    ]
