# Generated by Django 5.1.6 on 2025-02-22 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20250222_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicweapontype',
            name='weapon_groups',
        ),
    ]
