# Generated by Django 4.0.1 on 2022-01-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_magic_item_armor_magic_item_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmsSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='FeetSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='HandsSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='HeadSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='RingsSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.CreateModel(
            name='WaistSlotItem',
            fields=[],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.simplemagicitem',),
        ),
        migrations.AlterModelOptions(
            name='magicitemtype',
            options={
                'verbose_name': 'Тип магического предмета',
                'verbose_name_plural': 'Типы магическогих предметов',
            },
        ),
        migrations.AlterModelOptions(
            name='simplemagicitem',
            options={
                'verbose_name': 'Магический предмет',
                'verbose_name_plural': 'Магические предметы',
            },
        ),
    ]
