# Generated by Django 3.1.3 on 2021-02-02 07:53

import multiselectfield.db.fields
from django.db import migrations

import base.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210126_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='effect_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('NONE', ''),
                    ('ZONE', 'Зона'),
                    ('CONJURATION', 'Иллюзия'),
                    ('HEALING', 'Исцеление'),
                    ('RELIABLE', 'Надежный'),
                    ('CHARM', 'Очарование'),
                    ('POLYMORPH', 'Превращение'),
                    ('SLEEP', 'Сон'),
                    ('STANCE', 'Стойка'),
                    ('FEAR', 'Страх'),
                    ('TELEPORTATION', 'Телепортация'),
                    ('RATTLING', 'Ужасающий'),
                    ('INVIGORATING', 'Укрепляющий'),
                    ('POISON', 'Яд'),
                ],
                default=base.constants.PowerEffectTypeEnum['NONE'],
                max_length=115,
                verbose_name='Тип эффекта',
            ),
        ),
    ]
