# Generated by Django 5.1.4 on 2024-12-12 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_constraint_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='constraint',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conditions',
                to='base.constraint',
            ),
        ),
        migrations.AlterField(
            model_name='condition',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
