# Generated by Django 5.2.1 on 2025-05-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_combatantmonster_monster_encounter_monsters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatantmonster',
            name='armor_class',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='fortitude',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='initiative',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='name',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='reflex',
        ),
        migrations.RemoveField(
            model_name='combatantmonster',
            name='will',
        ),
    ]
