# Generated by Django 4.0 on 2021-12-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_armor_level_armor_magic_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagicalItem',
            new_name='MagicItem',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='magical_item',
            new_name='magic_item',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='enchantment',
        ),
    ]
