# Generated by Django 5.1.4 on 2024-12-09 15:09

import django.db.models.deletion
from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_magicweapontype_implement_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicweapontype',
            name='implement_type',
            field=models.ForeignKey(
                help_text='Does item has additional implement property?',
                limit_choices_to={
                    'category': base.constants.constants.WeaponCategoryIntEnum[
                        'IMPLEMENT'
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.weapontype',
                verbose_name='Implement type',
            ),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subclasses',
                to='base.class',
                verbose_name='Class',
            ),
        ),
    ]
