# Generated by Django 3.0.5 on 2020-11-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201108_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
