# Generated by Django 5.1.4 on 2024-12-19 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_itemcondition_armor_alter_itemcondition_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='item_condition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.itemcondition',
                verbose_name='Item condition',
            ),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='distance',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Additional distance for melee weapons',
                verbose_name='Distance',
            ),
        ),
        migrations.AlterField(
            model_name='weaponstate',
            name='is_empty',
            field=models.BooleanField(default=False, verbose_name='Is hand empty'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='handedness',
            field=models.CharField(
                choices=[
                    ('OFF_HAND', 'Дополнительное'),
                    ('ONE', 'Одноручное'),
                    ('VERSATILE', 'Универсальное'),
                    ('TWO', 'Двуручное'),
                    ('FREE', 'Не занимает руки'),
                    ('DOUBLE', 'Двойное'),
                ],
                max_length=9,
                verbose_name='Handedness',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='range',
            field=models.PositiveSmallIntegerField(
                default=0, help_text='For ranged weapon', verbose_name='Range'
            ),
        ),
    ]
