# Generated by Django 5.1.4 on 2025-01-27 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_frequency_int_power_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='power',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'frequency': 0, 'level': 0},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bonuses',
                related_query_name='bonus',
                to='base.power',
                verbose_name='Power',
            ),
        ),
    ]
