# Generated by Django 3.1.7 on 2021-03-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210321_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='subclass',
            field=models.SmallIntegerField(
                choices=[(0, '---------')], default=0, verbose_name='Подкласс'
            ),
        ),
        migrations.AlterField(
            model_name='powerproperty',
            name='subclass',
            field=models.SmallIntegerField(
                choices=[(0, '---------')], default=0, verbose_name='Подкласс'
            ),
        ),
    ]
