# Generated by Django 5.1.7 on 2025-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_npc_trained_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='default_powers',
            field=models.ManyToManyField(
                blank=True,
                related_name='classes',
                to='base.power',
                verbose_name='Default powers',
            ),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='default_powers',
            field=models.ManyToManyField(
                blank=True,
                related_name='subclasses',
                to='base.power',
                verbose_name='Default powers',
            ),
        ),
    ]
