# Generated by Django 4.0 on 2021-12-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_magicalitem_magicitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='name',
        ),
    ]
