# Generated by Django 5.1.6 on 2025-02-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_magicweapontype_weapon_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magicweapontype',
            old_name='weapon_groups_m2m',
            new_name='weapon_groups',
        ),
    ]
