# Generated by Django 5.1.4 on 2024-12-12 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_condition_constraint_alter_condition_object_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='negated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='condition',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to={
                    'app_label': 'base',
                    'model__in': (
                        'race',
                        'class',
                        'subclass',
                        'functionaltemplate',
                        'paragonpath',
                        'feat',
                    ),
                },
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
    ]
