# Generated by Django 5.1.4 on 2024-12-09 19:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_magicweapontype_implement_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='available_armor_types',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (0, 'Тканевый'),
                    (2, 'Кожаный'),
                    (3, 'Шкурный'),
                    (6, 'Кольчуга'),
                    (7, 'Чешуйчатый'),
                    (8, 'Латный'),
                ],
                max_length=11,
                null=True,
                verbose_name='Available armor types',
            ),
        ),
        migrations.AddField(
            model_name='subclass',
            name='available_armor_types',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (0, 'Тканевый'),
                    (2, 'Кожаный'),
                    (3, 'Шкурный'),
                    (6, 'Кольчуга'),
                    (7, 'Чешуйчатый'),
                    (8, 'Латный'),
                ],
                max_length=11,
                null=True,
                verbose_name='Available armor types',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.SlugField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('ARTIFICER', 'Артефактор'),
                    ('BARD', 'Бард'),
                    ('BLADESINGER', 'Блэйдсингер'),
                    ('VAMPIRE', 'Вампир'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('WARPRIEST', 'Военный священник (жрец)'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('SEEKER', 'Ловчий'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('SWORDMAGE', 'Мечник-маг'),
                    ('MONK', 'Монах'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER', 'Следопыт'),
                    ('HEXBLADE', 'Хексблэйд (колдун)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=11,
            ),
        ),
    ]
