# Generated by Django 5.2.1 on 2025-05-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_combatantmonster_armor_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.booksource',
                verbose_name='Source',
            ),
        ),
    ]
