# Generated by Django 5.1.2 on 2024-11-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_armor_armor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='base_armor_type',
            new_name='armor_type',
        ),
    ]
