# Generated by Django 5.1.6 on 2025-02-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_weapon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'verbose_name': 'Encounter', 'verbose_name_plural': 'Encounters'},
        ),
        migrations.AlterModelOptions(
            name='playercharacter',
            options={
                'verbose_name': 'Player character',
                'verbose_name_plural': 'Player characters',
            },
        ),
    ]
