# Generated by Django 5.1.4 on 2024-12-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_bonus_bonus_type_alter_powerproperty_subclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='size_int',
            field=models.SmallIntegerField(
                choices=[
                    (-1, 'Крошечный'),
                    (0, 'Маленький'),
                    (1, 'Средний'),
                    (2, 'Большой'),
                    (3, 'Огромный'),
                ],
                default=1,
                verbose_name='Size',
            ),
        ),
    ]
