# Generated by Django 5.1.4 on 2024-12-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_condition_negated_alter_condition_content_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='content_type',
            field=models.ForeignKey(
                limit_choices_to={
                    'app_label': 'base',
                    'model__in': (
                        'race',
                        'class',
                        'subclass',
                        'functionaltemplate',
                        'paragonpath',
                        'feat',
                        'power',
                    ),
                },
                on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype',
            ),
        ),
        migrations.CreateModel(
            name='PropertiesCondition',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('STRENGTH', 'Сила'),
                            ('CONSTITUTION', 'Телосложение'),
                            ('DEXTERITY', 'Ловкость'),
                            ('INTELLIGENCE', 'Интеллект'),
                            ('WISDOM', 'Мудрость'),
                            ('CHARISMA', 'Харизма'),
                            ('SPEED', 'Скорость'),
                            ('INITIATIVE', 'Инициатива'),
                            ('SURGE', 'Значение исцеления'),
                            ('SURGES', 'Количество исцелений'),
                            ('ATTACK', 'Атака'),
                            ('DAMAGE', 'Урон'),
                        ],
                        max_length=12,
                        verbose_name='Property type',
                    ),
                ),
                (
                    'value',
                    models.PositiveSmallIntegerField(verbose_name='Property value'),
                ),
                (
                    'constraint',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.constraint',
                    ),
                ),
            ],
        ),
    ]
