# Generated by Django 4.0.2 on 2022-02-13 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_armsslotitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='hands_slot',
            new_name='gloves_slot',
        ),
    ]
