# Generated by Django 3.0.5 on 2020-11-08 13:28

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20201108_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racebonus',
            name='name',
        ),
        migrations.AlterField(
            model_name='class',
            name='fortitude_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус стойкости'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('BARD', 'Бард'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RANGER', 'Следопыт'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=20,
                unique=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='reflex_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус реакции'),
        ),
        migrations.AlterField(
            model_name='class',
            name='will_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус воли'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_charisma',
            field=models.PositiveSmallIntegerField(verbose_name='Харизма (базовая)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_constitution',
            field=models.PositiveSmallIntegerField(
                verbose_name='Телосложение (базовое)'
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_dexterity',
            field=models.PositiveSmallIntegerField(verbose_name='Ловкость (базовая)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_intelligence',
            field=models.PositiveSmallIntegerField(verbose_name='Интеллект (базовый)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='base_wisdom',
            field=models.PositiveSmallIntegerField(verbose_name='Мудрость (базовая)'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='hit_points_per_level',
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name='Хитов за уровень'
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.Class',
                verbose_name='Класс',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level14_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 14 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level18_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 18 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level24_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 24 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level28_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 28 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level4_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 4 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level8_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Бонус характеристики на 8 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='race',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.Race',
                verbose_name='Раса',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='sex',
            field=models.CharField(
                choices=[('M', 'М'), ('F', 'Ж'), ('N', '-')],
                max_length=1,
                verbose_name='Пол',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='var_bonus_attr',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=20,
                null=True,
                verbose_name='Выборочный бонус характеристики',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='const_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Обязательные бонусы характеристик',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='fortitude_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус стойкости'),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(
                choices=[
                    ('GNOME', 'Гном'),
                    ('GOLIATH', 'Голиаф'),
                    ('DWARF', 'Дварф'),
                    ('DEVA', 'Дев'),
                    ('DRAGONBORN', 'Драконорожденный'),
                    ('HALFORC', 'Полуорк'),
                    ('HALFLING', 'Полурослик'),
                    ('HALFELF', 'Полуэльф'),
                    ('TIEFLING', 'Тифлинг'),
                    ('HUMAN', 'Человек'),
                    ('SHIFTER', 'Шифтер'),
                    ('ELADRIN', 'Эладрин'),
                    ('ELF', 'Эльф'),
                ],
                max_length=20,
                unique=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='reflex_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус реакции'),
        ),
        migrations.AlterField(
            model_name='race',
            name='size',
            field=models.CharField(
                choices=[
                    ('TINY', 'Крошечный'),
                    ('SMALL', 'Маленький'),
                    ('AVERAGE', 'Средний'),
                    ('BIG', 'Большой'),
                    ('LARGE', 'Огромный'),
                ],
                default='AVERAGE',
                max_length=10,
                verbose_name='Размер',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='skill_bonuses',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('INSIGHT', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('PERCEPTION', 'Восприятие'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                ],
                max_length=154,
                null=True,
                verbose_name='Бонусы навыков',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Скорость'),
        ),
        migrations.AlterField(
            model_name='race',
            name='var_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Выборочные бонусы характеристик',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='will_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус воли'),
        ),
    ]
