# Generated by Django 3.1.7 on 2021-03-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210321_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackPowerProperty',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'attack_attribute',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('STRENGTH', 'Сила'),
                            ('CONSTITUTION', 'Телосложение'),
                            ('DEXTERITY', 'Ловкость'),
                            ('INTELLIGENCE', 'Интеллект'),
                            ('WISDOM', 'Мудрость'),
                            ('CHARISMA', 'Харизма'),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name='Атакующая характеристика',
                    ),
                ),
                (
                    'attack_bonus',
                    models.SmallIntegerField(default=0, verbose_name='Бонус атаки'),
                ),
                (
                    'defence',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('ARMOR_CLASS', 'КД'),
                            ('FORTITUDE', 'Стойкость'),
                            ('REFLEX', 'Реакция'),
                            ('WILL', 'Воля'),
                        ],
                        max_length=11,
                        null=True,
                        verbose_name='Против защиты',
                    ),
                ),
                (
                    'dice_number',
                    models.SmallIntegerField(
                        default=1, verbose_name='Количество кубов'
                    ),
                ),
                (
                    'damage_dice',
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (4, 'k4'),
                            (6, 'k6'),
                            (8, 'k8'),
                            (10, 'k10'),
                            (12, 'k12'),
                            (20, 'k20'),
                            (100, 'k100'),
                        ],
                        null=True,
                        verbose_name='Кость урона',
                    ),
                ),
                (
                    'accessory_type',
                    models.CharField(
                        blank=True,
                        choices=[('IMPLEMENT', 'Инструмент'), ('WEAPON', 'Оружие')],
                        max_length=9,
                        null=True,
                        verbose_name='Тип вооружения',
                    ),
                ),
            ],
        ),
    ]
