# Generated by Django 5.1.6 on 2025-02-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_encounter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armortype',
            name='book_source',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.booksource',
                verbose_name='Source',
            ),
        ),
    ]
