# Generated by Django 4.0.1 on 2022-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_npc_arms_slot_npc_feet_slot_npc_hands_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name_display',
            field=models.CharField(
                default='temp', max_length=19, verbose_name='Название'
            ),
            preserve_default=False,
        ),
    ]
