# Generated by Django 5.1.6 on 2025-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_weapon_groups_m2m_magicweapontype_weapon_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='role_int',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Атакующий'),
                    (2, 'Защитник'),
                    (3, 'Контроллер'),
                    (4, 'Лидер'),
                ],
                null=True,
                verbose_name='Role',
            ),
        ),
    ]
