# Generated by Django 5.1.2 on 2024-11-18 20:55

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_base_armor_type_armor_armor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicArmorType',
            fields=[
                (
                    'magicitemtype_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='base.magicitemtype',
                    ),
                ),
                (
                    'armor_type_slots',
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (0, 'Тканевый'),
                            (2, 'Кожаный'),
                            (3, 'Шкурный'),
                            (6, 'Кольчуга'),
                            (7, 'Чешуйчатый'),
                            (8, 'Латный'),
                        ],
                        max_length=11,
                        verbose_name='Armor type slots',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Magic armor type',
                'verbose_name_plural': 'Magic armor types',
            },
            bases=('base.magicitemtype',),
        ),
        migrations.RemoveField(
            model_name='armor',
            name='bonus_armor_class',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='skill_penalty',
        ),
        migrations.RemoveField(
            model_name='armor',
            name='speed_penalty',
        ),
        migrations.RemoveField(
            model_name='magicitemtype',
            name='properties',
        ),
    ]
