# Generated by Django 5.2.1 on 2025-05-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_monster_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
    ]
