# Generated by Django 5.1.4 on 2024-12-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_class_available_armor_types_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='available_armor_types',
            new_name='armor_types',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='available_shields',
            new_name='shields',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='available_weapon_categories',
            new_name='weapon_categories',
        ),
        migrations.RenameField(
            model_name='subclass',
            old_name='available_armor_types',
            new_name='armor_types',
        ),
    ]
