# Generated by Django 3.1.3 on 2021-02-02 08:33

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210202_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='available_shield_types',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')],
                max_length=11,
                null=True,
                verbose_name='Ношение щитов',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='shield',
            field=models.CharField(
                blank=True,
                choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')],
                max_length=5,
                null=True,
                verbose_name='Щит',
            ),
        ),
    ]
