# Generated by Django 5.1.4 on 2025-01-27 19:05

from django.db import migrations


def fill_default_powers(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Power = apps.get_model('base', 'Power')
    Class = apps.get_model('base', 'Class')
    for klass in Class.objects.all():
        klass.default_powers.add(*Power.objects.filter(klass=klass))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_bonus_power'),
    ]

    operations = [migrations.RunPython(fill_default_powers)]
