# Generated by Django 5.1.7 on 2025-03-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_class_default_powers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterparticipants',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
