# Generated by Django 5.1.6 on 2025-02-23 07:58

from django.db import migrations

from base.constants.constants import ClassRoleIntEnum


def fill_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('base', 'Class')
    for c in Class.objects.all():
        c.role_int = ClassRoleIntEnum[c.role].value
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_class_role_int'),
    ]

    operations = [migrations.RunPython(fill_data)]
