# Generated by Django 3.0.5 on 2020-11-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20201108_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Описание'),
                ),
                (
                    'npcs',
                    models.ManyToManyField(
                        to='base.NPC', verbose_name='Мастерские персонажи'
                    ),
                ),
            ],
        ),
    ]
