# Generated by Django 5.2.1 on 2025-05-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_monster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Name'
            ),
        ),
    ]
