# Generated by Django 5.1.2 on 2024-11-19 15:24

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_magicarmortype_remove_armor_bonus_armor_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicArmItemType',
            fields=[
                (
                    'magicitemtype_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='base.magicitemtype',
                    ),
                ),
                (
                    'shield_slots',
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            (0, '----------'),
                            (1, 'Лёгкий щит'),
                            (2, 'Тяжелый щит'),
                        ],
                        default=base.constants.constants.ShieldTypeIntEnum['NONE'],
                        max_length=5,
                        verbose_name='Shield slots',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Magic shield/arms slot item type',
                'verbose_name_plural': 'Magic shield/arms slot item types',
            },
            bases=('base.magicitemtype',),
        ),
        migrations.AlterModelOptions(
            name='simplemagicitem',
            options={
                'verbose_name': 'Magic item',
                'verbose_name_plural': 'Magic items',
            },
        ),
    ]
