# Generated by Django 5.1.4 on 2024-12-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_race_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='size_int',
            new_name='size',
        ),
    ]
