# Generated by Django 4.0.2 on 2022-02-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_race_name_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='var_bonus_attr',
            new_name='var_bonus_ability',
        ),
        migrations.AddField(
            model_name='magicitemtype',
            name='max_level',
            field=models.PositiveSmallIntegerField(
                default=30, verbose_name='Максимальный уровень'
            ),
        ),
    ]
