# Generated by Django 5.1.4 on 2025-01-27 19:17

from django.db import migrations


def fill_power_subclass(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Power = apps.get_model('base', 'Power')
    Subclass = apps.get_model('base', 'Subclass')
    for power in Power.objects.filter(klass__isnull=False):
        power.subclass_obj = Subclass.objects.get(
            klass=power.klass, subclass_id=power.subclass
        )
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20250127_1905'),
    ]

    operations = [migrations.RunPython(fill_power_subclass)]
