# Generated by Django 4.0.2 on 2022-02-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_hands_slot_npc_gloves_slot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='simplemagicitem',
            unique_together={('magic_item_type', 'level')},
        ),
    ]
