# Generated by Django 5.1.4 on 2024-12-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_condition_content_type_propertiescondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertiescondition',
            name='type',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                    ('SURGE', 'Значение исцеления'),
                    ('INITIATIVE', 'Инициатива'),
                    ('SURGES', 'Количество исцелений'),
                    ('SPEED', 'Скорость'),
                ],
                max_length=12,
                verbose_name='Property type',
            ),
        ),
    ]
