# Generated by Django 3.1.3 on 2021-02-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210202_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
