# Generated by Django 5.1.6 on 2025-02-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_armortype_book_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armortype',
            name='book_source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.booksource',
                verbose_name='Source',
            ),
        ),
    ]
