# Generated by Django 5.1.4 on 2024-12-09 20:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_available_armor_types_class_armor_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclass',
            name='shields',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[(1, 'Лёгкий щит'), (2, 'Тяжелый щит')],
                max_length=3,
                null=True,
                verbose_name='Available shields',
            ),
        ),
        migrations.AddField(
            model_name='subclass',
            name='weapon_categories',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                max_length=13,
                null=True,
                verbose_name='Available weapon categories',
            ),
        ),
    ]
