# Generated by Django 5.1.4 on 2024-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_race_const_ability_bonus_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='const_ability_bonus',
        ),
    ]
