# Generated by Django 4.0 on 2021-12-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_magicitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitem',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
