# Generated by Django 5.1.4 on 2024-12-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_race_const_ability_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='const_ability_bonus_new',
            new_name='const_ability_bonus',
        ),
    ]
