# Generated by Django 4.0 on 2021-12-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_magicitem_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicitem',
            name='restrictions',
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='picture',
            field=models.ImageField(
                null=True, upload_to='media/items', verbose_name='Картинка'
            ),
        ),
    ]
