# Generated by Django 5.1.4 on 2024-12-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_bonus_item_condition_remove_weapontype_is_big_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='distance',
        ),
    ]
