# Generated by Django 3.1.3 on 2021-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210202_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='requirement',
            field=models.TextField(blank=True, null=True, verbose_name='Триггер'),
        ),
        migrations.AddField(
            model_name='power',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Триггер'),
        ),
        migrations.AlterField(
            model_name='power',
            name='frequency',
            field=models.CharField(
                choices=[
                    ('PASSIVE', 'Пассивный'),
                    ('AT_WILL', 'Неограниченный'),
                    ('ENCOUNTER', 'На сцену'),
                    ('DAYLY', 'На день'),
                ],
                max_length=9,
                verbose_name='Частота использования',
            ),
        ),
    ]
