# Generated by Django 5.1.4 on 2024-12-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_subclass_shields_subclass_weapon_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='weapon_types',
            field=models.ManyToManyField(
                to='base.weapontype', verbose_name='Available weapon types'
            ),
        ),
        migrations.AddField(
            model_name='subclass',
            name='weapon_types',
            field=models.ManyToManyField(
                to='base.weapontype', verbose_name='Available weapon types'
            ),
        ),
    ]
