# Generated by Django 5.2.1 on 2025-05-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_monster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='hit_points',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Hit points'
            ),
        ),
        migrations.AddField(
            model_name='monster',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='monster',
            name='role',
            field=models.CharField(
                default='Солдат', max_length=20, verbose_name='Role'
            ),
        ),
        migrations.AddField(
            model_name='monster',
            name='size',
            field=models.SmallIntegerField(
                choices=[
                    (-1, 'Крошечный'),
                    (0, 'Маленький'),
                    (1, 'Средний'),
                    (2, 'Большой'),
                    (3, 'Огромный'),
                    (4, 'Гигантский'),
                ],
                default=1,
                verbose_name='Size',
            ),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='armor_class',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Armor class'
            ),
        ),
        migrations.AlterField(
            model_name='monster',
            name='fortitude',
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name='Fortitude'
            ),
        ),
        migrations.AlterField(
            model_name='monster',
            name='initiative',
            field=models.SmallIntegerField(default=0, verbose_name='Initiative'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='reflex',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Reflex'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='will',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Will'),
        ),
    ]
