# Generated by Django 3.0.5 on 2020-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_encounter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encounter',
            options={'verbose_name': 'Сцена', 'verbose_name_plural': 'Сцены'},
        ),
        migrations.AddField(
            model_name='encounter',
            name='short_description',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Краткое описание'
            ),
        ),
    ]
