# Generated by Django 5.1.4 on 2025-01-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20250127_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='subclass',
        ),
    ]
