# Generated by Django 5.1.2 on 2024-11-19 15:51

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_magicarmitemtype_alter_simplemagicitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicarmitemtype',
            name='shield_slots',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[(1, 'Лёгкий щит'), (2, 'Тяжелый щит')],
                max_length=3,
                null=True,
                verbose_name='Shield slots',
            ),
        ),
    ]
