# Generated by Django 3.2.9 on 2021-11-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211110_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='power_source',
        ),
    ]
