# Generated by Django 5.1.6 on 2025-02-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20250223_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='role',
        ),
    ]
