# Generated by Django 4.0.2 on 2022-02-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_var_bonus_attr_npc_var_bonus_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='level14_bonus_attrs',
            new_name='level14_bonus_abilities',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level18_bonus_attrs',
            new_name='level18_bonus_abilities',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level24_bonus_attrs',
            new_name='level24_bonus_abilities',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level28_bonus_attrs',
            new_name='level28_bonus_abilities',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level4_bonus_attrs',
            new_name='level4_bonus_abilities',
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='level8_bonus_attrs',
            new_name='level8_bonus_abilities',
        ),
    ]
