# Generated by Django 4.0.2 on 2022-02-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'base',
            '0012_rename_level14_bonus_attrs_npc_level14_bonus_abilities_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='base_attack_ability',
            field=models.CharField(
                max_length=12, null=True, verbose_name='Атакующая характеристика'
            ),
        ),
    ]
