# Generated by Django 4.0 on 2021-12-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_magicitem_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitem',
            name='source',
            field=models.CharField(
                blank=True,
                help_text='Книга и страница',
                max_length=20,
                null=True,
                verbose_name='Источник',
            ),
        ),
        migrations.AlterField(
            model_name='magicitem',
            name='picture',
            field=models.ImageField(
                null=True, upload_to='items', verbose_name='Картинка'
            ),
        ),
    ]
