# Generated by Django 5.1.4 on 2025-01-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_power_subclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='subclass_obj',
            new_name='subclass',
        ),
    ]
