# Generated by Django 5.1.4 on 2024-12-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_propertiescondition_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='min_level',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='Minimal level'
            ),
        ),
    ]
