# Generated by Django 5.1.4 on 2024-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_class_weapon_types_subclass_weapon_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='available_weapon_types',
            new_name='weapon_types',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='available_weapon_types',
            new_name='weapon_types',
        ),
        migrations.AlterField(
            model_name='class',
            name='weapon_types',
            field=models.ManyToManyField(
                limit_choices_to={'primary_end__isnull': True},
                to='base.weapontype',
                verbose_name='Available weapon types',
            ),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='weapon_types',
            field=models.ManyToManyField(
                limit_choices_to={'primary_end__isnull': True},
                to='base.weapontype',
                verbose_name='Available weapon types',
            ),
        ),
    ]
