# Generated by Django 5.1.2 on 2024-11-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_magicarmitemtype_shield_slots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armsslotitem',
            options={
                'verbose_name': 'Hand item/shield',
                'verbose_name_plural': 'Hand items/shields',
            },
        ),
    ]
