# Generated by Django 3.2.9 on 2021-11-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_class_power_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='fortitude_bonus',
        ),
        migrations.RemoveField(
            model_name='class',
            name='hit_points_per_level',
        ),
        migrations.RemoveField(
            model_name='class',
            name='reflex_bonus',
        ),
        migrations.RemoveField(
            model_name='class',
            name='trained_skills',
        ),
        migrations.RemoveField(
            model_name='class',
            name='will_bonus',
        ),
    ]
