# Generated by Django 5.1.6 on 2025-02-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_class_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='role_int',
            new_name='role',
        ),
    ]
