# Generated by Django 5.1.4 on 2024-12-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_weapontype_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='distance',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='Additional distance for melee weapons, "reach".',
                verbose_name='Distance',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='hit_points_per_level',
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name='Hits per level'
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='hit_points_per_level_npc',
            field=models.PositiveSmallIntegerField(
                default=8, verbose_name='Hits per level'
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='var_ability_bonus',
            field=models.ManyToManyField(
                related_name='races',
                to='base.ability',
                verbose_name='Selective ability bonus',
            ),
        ),
    ]
