# Generated by Django 4.0.2 on 2022-02-03 15:01

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_npc_base_attack_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='base_attack_ability',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('INTELLIGENCE', 'Интеллект'),
                    ('DEXTERITY', 'Ловкость'),
                    ('WISDOM', 'Мудрость'),
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Атакующие характеристики',
            ),
        ),
    ]
