# Generated by Django 5.1.4 on 2024-12-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_race_var_ability_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='var_ability_bonus_new',
            new_name='var_ability_bonus',
        ),
    ]
