# Generated by Django 5.1.4 on 2024-12-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_feat_min_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
