# Generated by Django 5.1.4 on 2025-02-03 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_subclass_obj_power_subclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityLevelBonus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'level',
                    models.PositiveSmallIntegerField(
                        choices=[(4, 4), (8, 8), (14, 14), (18, 18), (24, 24), (28, 28)]
                    ),
                ),
                (
                    'ability',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='base.ability'
                    ),
                ),
                (
                    'npc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='base.npc'
                    ),
                ),
            ],
            options={
                'unique_together': {('ability', 'npc', 'level')},
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='level_ability_bonuses',
            field=models.ManyToManyField(
                blank=True,
                related_name='npcs_for_level_bonuses',
                through='base.AbilityLevelBonus',
                to='base.ability',
            ),
        ),
    ]
