# Generated by Django 3.2.9 on 2021-11-10 20:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211110_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('CROSSBOW', 'Арбалет'),
                    ('UNARMED', 'Безоружное'),
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('BOW', 'Лук'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('SLING', 'Праща'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=97,
                verbose_name='Группа оружия',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='handedness',
            field=models.CharField(
                choices=[
                    ('ONE', 'Одноручное'),
                    ('TWO', 'Двуручное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                default='ONE',
                max_length=9,
                verbose_name='Одноручное/Двуручное',
            ),
        ),
    ]
