# Generated by Django 3.0.5 on 2020-11-08 14:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_class_trained_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='trained_skills',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('INSIGHT', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('PERCEPTION', 'Восприятие'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                ],
                max_length=154,
                null=True,
                verbose_name='Тренированные навыки',
            ),
        ),
    ]
