# Generated by Django 5.1.2 on 2024-11-19 21:59

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_armsslotitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicWeaponType',
            fields=[
                (
                    'magicitemtype_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='base.magicitemtype',
                    ),
                ),
                (
                    'weapon_type_slots',
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ('BastardSword', 'Полуторный меч'),
                            ('Battleaxe', 'Боевой топор'),
                            ('Broadsword', 'Широкий меч'),
                            ('Club', 'Дубинка'),
                            ('Craghammer', 'Скальный молот'),
                            ('Crossbow', 'Арбалет'),
                            ('Dagger', 'Кинжал'),
                            ('ExecutionAxe', 'Топор палача'),
                            ('Falchion', 'Фальшион'),
                            ('Flail', 'Цеп'),
                            ('Fullblade', 'Большой клинок'),
                            ('Glaive', 'Глефа'),
                            ('Greataxe', 'Секира'),
                            ('Greatbow', 'Большой лук'),
                            ('Greatclub', 'Палица'),
                            ('Greatspear', 'Большое копьё'),
                            ('Greatsword', 'Двуручный меч'),
                            ('Halberg', 'Алебарда'),
                            ('HandCrossbow', 'Ручной арбалет'),
                            ('Handaxe', 'Ручной топор'),
                            ('HeavyFlail', 'Тяжелый цеп'),
                            ('HeavyWarPick', 'Тяжелая кирка'),
                            ('Javelin', 'Метательное копьё'),
                            ('Katar', 'Катар'),
                            ('Khopesh', 'Хопеш'),
                            ('Kukri', 'Кукри'),
                            ('LightMace', 'Лёгкая булава'),
                            ('LightWarPick', 'Лёгкая боевая кирка'),
                            ('LongSword', 'Длинный меч'),
                            ('Longbow', 'Длинный лук'),
                            ('Longspear', 'Длинное копьё'),
                            ('Mace', 'Булава'),
                            ('Maul', 'Кувалда'),
                            ('Mordenkrad', 'Морденкрад'),
                            ('Morningstar', 'Моргенштерн'),
                            ('ParryingDagger', 'Защитный кинжал (сай)'),
                            ('Quaterstaff', 'Посох'),
                            ('Rapier', 'Рапира'),
                            ('RepeatingCrossbow', 'Самозарядный арбалет'),
                            ('Scimitar', 'Ятаган'),
                            ('Scourge', 'Плеть'),
                            ('Scythe', 'Коса'),
                            ('ShortSpear', 'Короткое копьё'),
                            ('ShortSword', 'Короткий меч'),
                            ('Shortbow', 'Короткий лук'),
                            ('Shuriken', 'Сюрикен'),
                            ('Sickle', 'Серп'),
                            ('Sling', 'Праща'),
                            ('Spear', 'Копьё'),
                            ('SpikedChain', 'Шипованная цепь'),
                            ('SpikedGauntlet', 'Шипованная рукавица'),
                            ('SuperiorCrossbow', 'Превосходный арбалет'),
                            ('ThrowingHammer', 'Метательный молот'),
                            ('Tratnyr', 'Тратнир'),
                            ('Trident', 'Трезубец'),
                            ('TrippleHeadedFlail', 'Тройной цеп'),
                            ('WarPick', 'Боевая кирка'),
                            ('Waraxe', 'Боевой топор'),
                            ('Warhammer', 'Боевой молот'),
                            (
                                'WinterMourningBlade',
                                'Клинок зимней скорби (Оружие договора)',
                            ),
                            ('holy_symbol', 'Символ веры'),
                            ('ki_focus', 'Фокусировка ци'),
                            ('rod', 'Жезл'),
                            ('sphere', 'Сфера'),
                            ('totem', 'Тотем'),
                            ('wand', 'Волшебная палочка'),
                        ],
                        max_length=642,
                        verbose_name='Weapon type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Magic weapon type',
                'verbose_name_plural': 'Magic weapon types',
            },
            bases=('base.magicitemtype',),
        ),
    ]
