# Generated by Django 5.1.6 on 2025-02-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_role_int_class_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='role',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Атакующий'),
                    (2, 'Защитник'),
                    (3, 'Контроллер'),
                    (4, 'Лидер'),
                ],
                verbose_name='Role',
            ),
        ),
    ]
