# Generated by Django 4.0 on 2021-12-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_magicitem_source_alter_magicitem_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armor',
            old_name='armor_class',
            new_name='bonus_armor_class',
        ),
        migrations.AlterField(
            model_name='armor',
            name='armor_type',
            field=models.SmallIntegerField(
                choices=[
                    (0, 'Тканевый'),
                    (2, 'Кожаный'),
                    (3, 'Шкурный'),
                    (6, 'Кольчуга'),
                    (7, 'Чешуйчатый'),
                    (8, 'Латный'),
                ],
                verbose_name='Тип',
            ),
        ),
    ]
