# Generated by Django 5.1.6 on 2025-02-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_class_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='power_source_int',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Воинский'),
                    (2, 'Духовный'),
                    (3, 'Магический'),
                    (4, 'Первородный'),
                    (5, 'Теневой'),
                    (6, 'Псионический'),
                ],
                null=True,
                verbose_name='Power source',
            ),
        ),
    ]
