# Generated by Django 5.1.4 on 2025-02-03 20:28

from django.db import migrations


def fill_level_ability_bonuses(apps, schema_editor):
    NPC = apps.get_model('base', 'NPC')
    Ability = apps.get_model('base', 'Ability')
    AbilityLevelBonus = apps.get_model('base', 'AbilityLevelBonus')
    for npc in NPC.objects.all():
        l4b = list(map(str, npc.level4_bonus_abilities))
        l8b = list(map(str, npc.level8_bonus_abilities))
        l14b = list(map(str, npc.level14_bonus_abilities))
        l18b = list(map(str, npc.level18_bonus_abilities))
        l24b = list(map(str, npc.level24_bonus_abilities))
        l28b = list(map(str, npc.level28_bonus_abilities))
        for lnb, level in (
            (l4b, 4),
            (l8b, 8),
            (l14b, 14),
            (l18b, 18),
            (l24b, 24),
            (l28b, 28),
        ):
            if not lnb:
                continue
            for ab in lnb:
                alb = AbilityLevelBonus(
                    npc=npc, ability=Ability.objects.get(title=ab), level=level
                )
                alb.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_abilitylevelbonus_npc_level_ability_bonuses'),
    ]

    operations = [migrations.RunPython(fill_level_ability_bonuses)]
