# Generated by Django 4.0.2 on 2022-02-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0014_abilities_ordering'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='AbilityModel',
        ),
        migrations.AlterModelOptions(
            name='abilitymodel',
            options={'ordering': ('ordering',)},
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                (
                    'title',
                    models.CharField(
                        choices=[
                            ('acrobatics', 'Акробатика'),
                            ('athletics', 'Атлетика'),
                            ('perception', 'Внимательность'),
                            ('thievery', 'Воровство'),
                            ('endurance', 'Выносливость'),
                            ('intimidate', 'Запугивание'),
                            ('streetwise', 'Знание улиц'),
                            ('history', 'История'),
                            ('arcana', 'Магия'),
                            ('bluff', 'Обман'),
                            ('diplomacy', 'Переговоры'),
                            ('dungeoneering', 'Подземелья'),
                            ('nature', 'Природа'),
                            ('insight', 'Проницательность'),
                            ('religion', 'Религия'),
                            ('stealth', 'Скрытность'),
                            ('heal', 'Целительство'),
                        ],
                        max_length=13,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
                (
                    'based_on',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.abilitymodel',
                    ),
                ),
            ],
        ),
    ]
