# Generated by Django 5.1.6 on 2025-02-20 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_combatants_avatar_alter_encounter_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'base_shield_type',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, '----------'),
                            (1, 'Лёгкий щит'),
                            (2, 'Тяжелый щит'),
                        ],
                        verbose_name='Armor type',
                    ),
                ),
                (
                    'skill_penalty',
                    models.SmallIntegerField(default=0, verbose_name='Skills penalty'),
                ),
            ],
            options={
                'verbose_name': 'Shield type',
                'verbose_name_plural': 'Shield types',
            },
        ),
        migrations.AlterField(
            model_name='armortype',
            name='base_armor_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'Тканевый'),
                    (2, 'Кожаный'),
                    (3, 'Шкурный'),
                    (6, 'Кольчуга'),
                    (7, 'Чешуйчатый'),
                    (8, 'Латный'),
                ],
                verbose_name='Armor type',
            ),
        ),
        migrations.AlterField(
            model_name='armortype',
            name='bonus_armor_class',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Additional armor class'
            ),
        ),
        migrations.AlterField(
            model_name='armortype',
            name='minimal_enhancement',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Minimal enhancement'
            ),
        ),
        migrations.AddField(
            model_name='armsslotitem',
            name='shield_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.shieldtype',
                verbose_name='Shield',
            ),
        ),
    ]
