# Generated by Django 4.0 on 2021-12-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_armor_class_armor_bonus_armor_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='bonus_armor_class',
            field=models.SmallIntegerField(
                default=0,
                help_text='Для магических доспехов высоких уровней',
                verbose_name='Дополнительный класс доспеха',
            ),
        ),
        migrations.AlterField(
            model_name='armor',
            name='magic_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.magicitem',
                verbose_name='Магический предмет',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='subclass',
            field=models.SmallIntegerField(default=0, verbose_name='Подкласс'),
        ),
    ]
