# Generated by Django 5.1.4 on 2024-12-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_feat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='min_level',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (11, 11), (21, 21)],
                default=1,
                verbose_name='Minimal level',
            ),
        ),
    ]
