# Generated by Django 5.1.4 on 2024-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_feat_min_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='feats',
            field=models.ManyToManyField(
                blank=True, to='base.feat', verbose_name='Feats'
            ),
        ),
    ]
