# Generated by Django 4.0.2 on 2022-02-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_abilitymodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSkill',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='trainable_skills',
            field=models.ManyToManyField(
                through='base.ClassSkill', to='base.SkillModel'
            ),
        ),
        migrations.AddField(
            model_name='classskill',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='base.class'
            ),
        ),
        migrations.AddField(
            model_name='classskill',
            name='skill',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='base.skillmodel'
            ),
        ),
    ]
