# Generated by Django 5.1.6 on 2025-02-23 08:11

from django.db import migrations

from base.constants.constants import PowerSourceIntEnum


def fill_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Class = apps.get_model('base', 'Class')
    for c in Class.objects.all():
        c.power_source_int = PowerSourceIntEnum[c.power_source].value
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_class_power_source_int'),
    ]

    operations = [migrations.RunPython(fill_data)]
