# Generated by Django 5.1.4 on 2025-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20250203_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='level14_bonus_abilities',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level18_bonus_abilities',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level24_bonus_abilities',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level28_bonus_abilities',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level4_bonus_abilities',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='level8_bonus_abilities',
        ),
        migrations.AlterField(
            model_name='npc',
            name='level_ability_bonuses',
            field=models.ManyToManyField(
                blank=True,
                related_name='npcs_for_level_bonuses',
                through='base.AbilityLevelBonus',
                to='base.ability',
                verbose_name='Ability level bonuses',
            ),
        ),
    ]
