# Generated by Django 5.1.2 on 2024-11-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_magicweapontype_weapon_type_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitemtype',
            name='slot',
            field=models.CharField(
                choices=[
                    ('armor', 'Броня'),
                    ('head', 'Голова'),
                    ('ring', 'Кольца'),
                    ('feet', 'Обувь'),
                    ('weapon', 'Оружие'),
                    ('hands', 'Перчатки'),
                    ('waist', 'Пояс'),
                    ('arms', 'Предплечья/Щит'),
                    ('tatoo', 'Татуировка'),
                    ('wondrous_items', 'Чудесный предмет'),
                    ('neck', 'Шея'),
                ],
                max_length=14,
                null=True,
                verbose_name='Slot',
            ),
        ),
    ]
