# Generated by Django 4.0 on 2021-12-14 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_armor_bonus_armor_class_alter_armor_magic_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='enchantment',
            new_name='enchantment_old',
        ),
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='magic_item',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.magicitem',
                verbose_name='Магический предмет',
            ),
        ),
    ]
