# Generated by Django 4.0.2 on 2022-02-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_npc_base_attack_ability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Armor', 'verbose_name_plural': 'Armors'},
        ),
    ]
