# Generated by Django 5.1.4 on 2024-12-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_npc_var_bonus_ability_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='var_bonus_ability',
        ),
    ]
