# Generated by Django 5.1.6 on 2025-02-20 07:20

from django.db import migrations


def fill_shield(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ArmsSlotItem = apps.get_model('base', 'ArmsSlotItem')
    ShieldType = apps.get_model('base', 'ShieldType')
    ShieldType.objects.bulk_create(
        (
            ShieldType(base_shield_type=1),
            ShieldType(base_shield_type=2, skill_penalty=-2),
        )
    )
    for asi in ArmsSlotItem.objects.all():
        try:
            st = ShieldType.objects.get(base_shield_type=asi.shield)
        except ShieldType.DoesNotExist:
            continue
        asi.shield_type = st
        asi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_shieldtype_alter_armortype_base_armor_type_and_more'),
    ]

    operations = [migrations.RunPython(fill_shield)]
