# Generated by Django 3.2.9 on 2021-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_weapontype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='slug',
            field=models.CharField(max_length=20, unique=True, verbose_name='Slug'),
        ),
    ]
