# Generated by Django 5.1.6 on 2025-02-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20250220_0720'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='armsslotitem',
            unique_together={('magic_item_type', 'level', 'shield_type')},
        ),
        migrations.RemoveField(
            model_name='armsslotitem',
            name='shield',
        ),
    ]
