# Generated by Django 3.0.5 on 2020-11-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20201108_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('LEATHER', 'Кожаный'),
                            ('CHAINMAIL', 'Кольчуга'),
                            ('PLATE', 'Латный'),
                            ('CLOTH', 'Тканевый'),
                            ('SCALE', 'Чешуйчатый'),
                            ('HIDE', 'Шкурный'),
                        ],
                        max_length=9,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'enchantment',
                    models.SmallIntegerField(default=0, verbose_name='Улучшение'),
                ),
            ],
        ),
    ]
