# Generated by Django 5.1.4 on 2025-02-05 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_npc_level14_bonus_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilitylevelbonus',
            name='ability',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='level_bonuses',
                to='base.ability',
            ),
        ),
    ]
