# Generated by Django 5.1.2 on 2024-11-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_magicitemtype_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magicitemtype',
            name='slots',
        ),
    ]
