# Generated by Django 3.1.3 on 2021-02-11 09:38

import multiselectfield.db.fields
from django.db import migrations, models

import base.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210206_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='effect_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('NONE', ''),
                    ('ZONE', 'Зона'),
                    ('CONJURATION', 'Иллюзия'),
                    ('HEALING', 'Исцеление'),
                    ('RELIABLE', 'Надежный'),
                    ('CHARM', 'Очарование'),
                    ('POLYMORPH', 'Превращение'),
                    ('SLEEP', 'Сон'),
                    ('STANCE', 'Стойка'),
                    ('FEAR', 'Страх'),
                    ('TELEPORTATION', 'Телепортация'),
                    ('RATTLING', 'Ужасающий'),
                    ('INVIGORATING', 'Укрепляющий'),
                ],
                default=base.constants.constants.PowerEffectTypeEnum['NONE'],
                max_length=108,
                verbose_name='Тип эффекта',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(
                choices=[
                    ('BUGBEAR', 'Багбир'),
                    ('HAMADRYAD', 'Гамадриада'),
                    ('GITHZERAI', 'Гитзерай'),
                    ('GNOLL', 'Гнолл'),
                    ('GNOME', 'Гном'),
                    ('GOBLIN', 'Гоблин'),
                    ('GOLIATH', 'Голиаф'),
                    ('DWARF', 'Дварф'),
                    ('DEVA', 'Дев'),
                    ('WILDEN', 'Дикарь'),
                    ('DOPPELGANGER', 'Доппельгангер'),
                    ('DRAGONBORN', 'Драконорожденный'),
                    ('TREANT', 'Древень'),
                    ('DROW', 'Дроу'),
                    ('DUERGAR', 'Дуэргар'),
                    ('KALASHTAR', 'Калаштар'),
                    ('KOBOLD', 'Кобольд'),
                    ('WARFORGED', 'Кованый'),
                    ('MINOTAUR', 'Минотавр'),
                    ('ORC', 'Орк'),
                    ('PIXIE', 'Пикси'),
                    ('HALFORC', 'Полуорк'),
                    ('HALFLING', 'Полурослик'),
                    ('HALFELF', 'Полуэльф'),
                    ('SATYR', 'Сатир'),
                    ('TIEFLING', 'Тифлинг'),
                    ('HUMAN', 'Человек'),
                    ('SHADAR_KAI', 'Шадар-Кай'),
                    ('SHIFTER_RAZORCLAW', 'Шифтер, бритволапый'),
                    ('SHIFTER_LONGTEETH', 'Шифтер, длиннозубый'),
                    ('ELADRIN', 'Эладрин'),
                    ('ELF', 'Эльф'),
                ],
                max_length=17,
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
