# Generated by Django 5.1.6 on 2025-02-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20250223_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='power_source',
        ),
        migrations.AlterField(
            model_name='class',
            name='power_source_int',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Воинский'),
                    (2, 'Духовный'),
                    (3, 'Магический'),
                    (4, 'Первородный'),
                    (5, 'Теневой'),
                    (6, 'Псионический'),
                ],
                verbose_name='Power source',
            ),
        ),
    ]
