# Generated by Django 4.0.2 on 2022-02-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_armor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='bonus_armor_class',
            field=models.SmallIntegerField(
                default=0,
                help_text='Для магических доспехов высоких уровней',
                verbose_name='Additional armor class',
            ),
        ),
    ]
