# Generated by Django 5.1.4 on 2024-12-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_npc_feats'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='feat',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bonuses',
                related_query_name='bonus',
                to='base.feat',
            ),
        ),
    ]
