# Generated by Django 3.0.5 on 2020-11-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_armor'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='armor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.Armor',
                verbose_name='Доспехи',
            ),
        ),
    ]
