# Generated by Django 5.1.2 on 2024-11-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_magicitemtype_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='weapons',
        ),
    ]
