# Generated by Django 3.2.9 on 2021-11-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211111_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaltemplate',
            options={
                'verbose_name': 'Функциональный шаблон',
                'verbose_name_plural': 'Функциональные шаблоны',
            },
        ),
        migrations.RemoveField(
            model_name='class',
            name='available_weapon_categories',
        ),
        migrations.RemoveField(
            model_name='class',
            name='available_weapon_types',
        ),
        migrations.RemoveField(
            model_name='class',
            name='subclasses',
        ),
        migrations.RemoveField(
            model_name='race',
            name='available_weapon_types',
        ),
    ]
