# Generated by Django 4.0.2 on 2022-02-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_abilitymodel_ability_rename_skillmodel_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='trainable_skills',
        ),
        migrations.DeleteModel(
            name='ClassSkill',
        ),
    ]
