# Generated by Django 5.1.4 on 2024-12-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_var_bonus_ability_new_npc_var_bonus_ability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
