# Generated by Django 5.1.6 on 2025-02-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_class_power_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='power_source_int',
            new_name='power_source',
        ),
    ]
