# Generated by Django 5.1.4 on 2025-02-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_abilitylevelbonus_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='base_attack_ability',
        ),
    ]
