# Generated by Django 3.1.3 on 2021-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210211_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='level',
            field=models.SmallIntegerField(default=0, verbose_name='Уровень'),
        ),
    ]
