# Generated by Django 4.0.2 on 2022-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_weapon_options_alter_weapontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Race', 'verbose_name_plural': 'Races'},
        ),
        migrations.AlterField(
            model_name='race',
            name='is_sociable',
            field=models.BooleanField(
                default=True,
                help_text='Social races are used for random npc generation',
                verbose_name='Is race social?',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(
                choices=[
                    ('BUGBEAR', 'Багбир'),
                    ('VRYLOKA', 'Врылока'),
                    ('HAMADRYAD', 'Гамадриада'),
                    ('GITHZERAI', 'Гитзерай'),
                    ('GNOLL', 'Гнолл'),
                    ('GNOME', 'Гном'),
                    ('GOBLIN', 'Гоблин'),
                    ('GOLIATH', 'Голиаф'),
                    ('DWARF', 'Дварф'),
                    ('DEVA', 'Дев'),
                    ('GENASI_WINDSOUL', 'Дженази, ветер'),
                    ('GENASI_WATERSOUL', 'Дженази, вода'),
                    ('GENASI_EARTHSOUL', 'Дженази, земля'),
                    ('GENASI_FIRESOUL', 'Дженази, огонь'),
                    ('GENASI_STORMSOUL', 'Дженази, шторм'),
                    ('WILDEN', 'Дикарь'),
                    ('DOPPELGANGER', 'Доппельгангер'),
                    ('DRAGONBORN', 'Драконорожденный'),
                    ('DROW', 'Дроу'),
                    ('DUERGAR', 'Дуэргар'),
                    ('KALASHTAR', 'Калаштар'),
                    ('KENKU', 'Кенку'),
                    ('KOBOLD', 'Кобольд'),
                    ('WARFORGED', 'Кованый'),
                    ('BLADELING', 'Мечерождённый'),
                    ('MINOTAUR', 'Минотавр'),
                    ('MUL', 'Мул'),
                    ('ORC', 'Орк'),
                    ('PIXIE', 'Пикси'),
                    ('HALFORC', 'Полуорк'),
                    ('HALFLING', 'Полурослик'),
                    ('HALFELF', 'Полуэльф'),
                    ('SATYR', 'Сатир'),
                    ('TIEFLING', 'Тифлинг'),
                    ('THRI_KREEN', 'Три-крин'),
                    ('HOBGOBLIN', 'Хобгоблин'),
                    ('HUMAN', 'Человек'),
                    ('SHADAR_KAI', 'Шадар-Кай'),
                    ('SHIFTER_RAZORCLAW', 'Шифтер, бритволапый'),
                    ('SHIFTER_LONGTEETH', 'Шифтер, длиннозубый'),
                    ('ELADRIN', 'Эладрин'),
                    ('ELF', 'Эльф'),
                ],
                max_length=17,
                unique=True,
                verbose_name='Title',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='name_display',
            field=models.CharField(max_length=19, verbose_name='Title'),
        ),
    ]
