# Generated by Django 4.0.2 on 2022-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0018_remove_class_trainable_skills_delete_classskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='trainable_skills',
            field=models.ManyToManyField(to='base.Skill'),
        ),
    ]
