# Generated by Django 3.0.5 on 2020-11-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_npc_armor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Доспех', 'verbose_name_plural': 'Доспехи'},
        ),
        migrations.AddField(
            model_name='armor',
            name='armor_class',
            field=models.SmallIntegerField(default=0, verbose_name='Класс доспеха'),
        ),
    ]
