# Generated by Django 5.1.6 on 2025-02-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_shield_type_armsslotitem_shield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='armsslotitem',
            old_name='shield',
            new_name='shield_type',
        ),
        migrations.AlterUniqueTogether(
            name='armsslotitem',
            unique_together={('magic_item_type', 'level', 'shield_type')},
        ),
    ]
