# Generated by Django 5.1.4 on 2024-12-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_delete_ability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbilityNew',
            new_name='Ability',
        ),
    ]
