# Generated by Django 5.1.2 on 2024-11-21 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_npc_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='skill',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.skill',
                verbose_name='Skill',
            ),
        ),
    ]
