# Generated by Django 5.1.6 on 2025-02-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_power_source_int_class_power_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('effect_type', models.CharField(max_length=20, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Effect type',
                'verbose_name_plural': 'Effect types',
            },
        ),
        migrations.AddField(
            model_name='power',
            name='effects',
            field=models.ManyToManyField(
                blank=True, to='base.effect', verbose_name='Effects'
            ),
        ),
    ]
