# Generated by Django 5.1.2 on 2024-11-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_power_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='base_attack_ability',
            field=models.CharField(
                blank=True,
                choices=[
                    ('strength', 'Сила'),
                    ('constitution', 'Телосложение'),
                    ('dexterity', 'Ловкость'),
                    ('intelligence', 'Интеллект'),
                    ('wisdom', 'Мудрость'),
                    ('charisma', 'Харизма'),
                ],
                max_length=12,
                null=True,
                verbose_name='Base attack ability',
            ),
        ),
    ]
