# Generated by Django 3.2.9 on 2021-11-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementtype',
            name='slug',
            field=models.CharField(max_length=20, null=True, verbose_name='slug'),
        ),
    ]
