# Generated by Django 5.1.6 on 2025-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_shield_armsslotitem_shield_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponGroup',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[
                            ('CROSSBOW', 'Арбалет'),
                            ('UNARMED', 'Безоружное'),
                            ('MACE', 'Булава'),
                            ('POLEARM', 'Древковое'),
                            ('PICK', 'Кирка'),
                            ('SPEAR', 'Копьё'),
                            ('BOW', 'Лук'),
                            ('LIGHT_BLADE', 'Лёгкий клинок'),
                            ('HAMMER', 'Молот'),
                            ('STAFF', 'Посох'),
                            ('SLING', 'Праща'),
                            ('AXE', 'Топор'),
                            ('HEAVY_BLADE', 'Тяжелый клинок'),
                            ('FLAIL', 'Цеп'),
                        ],
                        max_length=11,
                        unique=True,
                        verbose_name='Name',
                    ),
                ),
                (
                    'is_ranged',
                    models.BooleanField(default=False, verbose_name='Ranged'),
                ),
            ],
            options={
                'verbose_name': 'Weapon group',
                'verbose_name_plural': 'Weapon group',
            },
        ),
        migrations.AddField(
            model_name='weapontype',
            name='groups',
            field=models.ManyToManyField(to='base.weapongroup', verbose_name='Groups'),
        ),
    ]
