# Generated by Django 4.0 on 2021-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_npc_var_bonus_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='var_bonus_attr',
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                verbose_name='Выборочный бонус характеристики',
            ),
        ),
    ]
