# Generated by Django 3.0.5 on 2020-11-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20201108_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='type',
            field=models.CharField(
                choices=[
                    ('CLOTH', 'Тканевый'),
                    ('LEATHER', 'Кожаный'),
                    ('HIDE', 'Шкурный'),
                    ('CHAINMAIL', 'Кольчуга'),
                    ('SCALE', 'Чешуйчатый'),
                    ('PLATE', 'Латный'),
                ],
                max_length=9,
                verbose_name='Тип',
            ),
        ),
    ]
