# Generated by Django 4.0.2 on 2022-02-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0019_class_trainable_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('ordering',)},
        ),
        migrations.AddField(
            model_name='npc',
            name='tained_skills_key',
            field=models.ManyToManyField(
                to='base.Skill', verbose_name='Trained skills'
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='trainable_skills',
            field=models.ManyToManyField(
                to='base.Skill', verbose_name='Выборочно тренируемые навыки'
            ),
        ),
    ]
