# Generated by Django 4.0.2 on 2022-02-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_race_options_alter_race_is_sociable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={
                'ordering': ('name_display',),
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.AlterModelOptions(
            name='functionaltemplate',
            options={
                'ordering': ('title',),
                'verbose_name': 'Functional template',
                'verbose_name_plural': 'Functional templates',
            },
        ),
        migrations.AlterField(
            model_name='class',
            name='name_display',
            field=models.CharField(max_length=24, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='action_points_bonus',
            field=models.SmallIntegerField(default=1, verbose_name='Action points'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='armor_class_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Armor class bonus'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='fortitude_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Fortitude bonus'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='hit_points_per_level',
            field=models.SmallIntegerField(default=8, verbose_name='Hits per level'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='min_level',
            field=models.SmallIntegerField(default=0, verbose_name='Minimal level'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='reflex_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Reflex bonus'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='save_bonus',
            field=models.SmallIntegerField(
                default=2, verbose_name='Saving throws bonus'
            ),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='functionaltemplate',
            name='will_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Will bonus'),
        ),
    ]
