# Generated by Django 5.1.4 on 2024-12-23 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_abilitynew_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNew',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        choices=[
                            ('ACROBATICS', 'Акробатика'),
                            ('ATHLETICS', 'Атлетика'),
                            ('PERCEPTION', 'Внимательность'),
                            ('THIEVERY', 'Воровство'),
                            ('ENDURANCE', 'Выносливость'),
                            ('INTIMIDATE', 'Запугивание'),
                            ('STREETWISE', 'Знание улиц'),
                            ('HISTORY', 'История'),
                            ('ARCANA', 'Магия'),
                            ('BLUFF', 'Обман'),
                            ('DIPLOMACY', 'Переговоры'),
                            ('DUNGEONEERING', 'Подземелья'),
                            ('NATURE', 'Природа'),
                            ('INSIGHT', 'Проницательность'),
                            ('RELIGION', 'Религия'),
                            ('STEALTH', 'Скрытность'),
                            ('HEAL', 'Целительство'),
                        ],
                        max_length=13,
                        unique=True,
                    ),
                ),
                (
                    'based_on',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='base.ability'
                    ),
                ),
            ],
        ),
    ]
