# Generated by Django 3.0.5 on 2020-11-08 19:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20201108_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='level14_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 14 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level18_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 18 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level24_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 24 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level28_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 28 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level4_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 4 уровне',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level8_bonus_attrs',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Бонус характеристики на 8 уровне',
            ),
        ),
    ]
