# Generated by Django 4.0.2 on 2022-02-15 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0020_alter_skill_options_npc_tained_skills_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='trained_skills',
        ),
    ]
