# Generated by Django 3.2.9 on 2021-11-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_implementtype_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementtype',
            name='inherited_weapon_type',
        ),
        migrations.AlterField(
            model_name='implementtype',
            name='slug',
            field=models.CharField(max_length=20, verbose_name='slug'),
        ),
    ]
