# Generated by Django 5.1.4 on 2024-12-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_skillnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='mandatory_skills_new',
            field=models.ManyToManyField(
                to='base.skill', verbose_name='Mandatory skills'
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='trainable_skills_new',
            field=models.ManyToManyField(
                related_name='classes',
                to='base.skill',
                verbose_name='Selective trainable skills',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='mandatory_skills',
            field=models.ManyToManyField(
                related_name='classesm',
                to='base.skill',
                verbose_name='Mandatory skills',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='trainable_skills',
            field=models.ManyToManyField(
                related_name='classest',
                to='base.skill',
                verbose_name='Выборочно тренируемые навыки',
            ),
        ),
    ]
