# Generated by Django 4.0 on 2021-12-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_npc_var_bonus_attr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicitem',
            name='picture',
            field=models.ImageField(
                blank=True, null=True, upload_to='items', verbose_name='Картинка'
            ),
        ),
    ]
