# Generated by Django 4.0.2 on 2022-02-06 11:39

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_class_options_alter_functionaltemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='armor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.armor',
                verbose_name='Armor',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='functional_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.functionaltemplate',
                verbose_name='Functional template',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.class',
                verbose_name='Class',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='level',
            field=models.PositiveSmallIntegerField(verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='powers',
            field=models.ManyToManyField(
                blank=True, to='base.Power', verbose_name='Powers'
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='primary_hand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='in_primary_hands',
                to='base.weapon',
                verbose_name='Primary hand',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='race',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.race',
                verbose_name='Race',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='secondary_hand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='in_secondary_hands',
                to='base.weapon',
                verbose_name='Secondary hand',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='sex',
            field=models.CharField(
                choices=[('M', 'Муж'), ('F', 'Жен'), ('N', 'Н/Д')],
                max_length=1,
                verbose_name='Sex',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='shield',
            field=models.CharField(
                blank=True,
                choices=[('LIGHT', 'Лёгкий щит'), ('HEAVY', 'Тяжелый щит')],
                max_length=5,
                null=True,
                verbose_name='Shield',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='subclass',
            field=models.SmallIntegerField(default=0, verbose_name='Subclass'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='trained_skills',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('PERCEPTION', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('INSIGHT', 'Проницательность'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                ],
                max_length=154,
                null=True,
                verbose_name='Trained skills',
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(
                blank=True,
                help_text='Armament posessed by character. If list is not empty, weapons in hands are choose from it.',
                to='base.Weapon',
                verbose_name='Armament',
            ),
        ),
    ]
