# Generated by Django 5.1.4 on 2024-12-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_class_mandatory_skills_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='mandatory_skills_new',
            field=models.ManyToManyField(
                to='base.skillnew', verbose_name='Mandatory skills'
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='trainable_skills_new',
            field=models.ManyToManyField(
                related_name='classes',
                to='base.skillnew',
                verbose_name='Selective trainable skills',
            ),
        ),
    ]
