# Generated by Django 3.2.9 on 2021-11-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20211114_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementtype',
            name='name',
        ),
    ]
