# Generated by Django 3.0.5 on 2020-11-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20201108_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='var_bonus_attr',
            field=models.CharField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=12,
                null=True,
                verbose_name='Выборочный бонус характеристики',
            ),
        ),
    ]
