# Generated by Django 4.0 on 2021-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_magicitem_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicitem',
            name='category',
            field=models.CharField(
                choices=[
                    ('COMMON', 'Обычный'),
                    ('UNCOMMON', 'Необычный'),
                    ('RARE', 'Редкий'),
                ],
                default='UNCOMMON',
                max_length=8,
                verbose_name='Категория',
            ),
        ),
    ]
