# Generated by Django 4.0.2 on 2022-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_npc_trained_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='tained_skills_key',
            new_name='trained_skills',
        ),
    ]
