# Generated by Django 3.1.3 on 2021-02-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20210214_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='subclass',
            field=models.SmallIntegerField(default=0, verbose_name='Подкласс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapontype',
            name='category_int',
            field=models.SmallIntegerField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                ],
                default=2,
                verbose_name='Категория',
            ),
            preserve_default=False,
        ),
    ]
