# Generated by Django 4.0.2 on 2022-02-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_magicitemtype_options_alter_power_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicitemtype',
            name='properties',
            field=models.JSONField(null=True),
        ),
    ]
