# Generated by Django 3.0.5 on 2020-11-08 19:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20201108_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='available_armor_type',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('LEATHER', 'Кожаный'),
                    ('CHAINMAIL', 'Кольчуга'),
                    ('PLATE', 'Латный'),
                    ('CLOTH', 'Тканевый'),
                    ('SCALE', 'Чешуйчатый'),
                    ('HIDE', 'Шкурный'),
                ],
                default='CLOTH',
                max_length=40,
                verbose_name='Ношение доспехов',
            ),
        ),
    ]
