# Generated by Django 5.1.4 on 2024-12-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_class_mandatory_skills_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='mandatory_skills',
        ),
        migrations.RemoveField(
            model_name='class',
            name='trainable_skills',
        ),
    ]
