# Generated by Django 4.0.2 on 2022-02-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_tained_skills_key_npc_trained_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='trainable_skills',
            field=models.ManyToManyField(
                related_name='classes',
                to='base.Skill',
                verbose_name='Выборочно тренируемые навыки',
            ),
        ),
    ]
