# Generated by Django 3.2.9 on 2021-11-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_implementtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='implement',
            name='slug',
            field=models.CharField(default='temp', max_length=20, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
