# Generated by Django 5.1.3 on 2024-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_magicweapontype_weapon_type_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicweapontype',
            name='crit_dice',
            field=models.SmallIntegerField(
                blank=True,
                choices=[(4, 'k4'), (6, 'k6'), (8, 'k8'), (10, 'k10'), (12, 'k12')],
                null=True,
                verbose_name='Damage dice',
            ),
        ),
        migrations.AddField(
            model_name='magicweapontype',
            name='crit_property',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Crit property'
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='accessory_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('TWO_WEAPONS', 'Два оружия'),
                    ('IMPLEMENT', 'Инструмент'),
                    ('WEAPON', 'Оружие'),
                    ('WEAPON_AND_IMPLEMENT', 'Оружие и инструмент'),
                ],
                max_length=20,
                null=True,
                verbose_name='Accessory type',
            ),
        ),
    ]
