# Generated by Django 4.0 on 2021-12-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_magicitem_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='attack_attribute',
            new_name='attack_ability',
        ),
    ]
