# Generated by Django 3.1.3 on 2021-02-15 09:32

from django.db import migrations, models

from base.constants.constants import WeaponCategoryIntEnum


def category_migrate(apps, schema_editor):
    WeaponType = apps.get_model('base', 'WeaponType')
    for w_type in WeaponType.objects.all():
        w_type.category_int = WeaponCategoryIntEnum[w_type.category]
        w_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20210215_0932'),
    ]

    operations = [migrations.RunPython(category_migrate)]
