# Generated by Django 4.0.2 on 2022-02-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_magicitemtype_properties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magicitemtype',
            options={
                'verbose_name': 'Magic item type',
                'verbose_name_plural': 'Типы магических предметов',
            },
        ),
        migrations.AlterModelOptions(
            name='simplemagicitem',
            options={
                'verbose_name': 'Магический предмет',
                'verbose_name_plural': 'Магические предметы',
            },
        ),
    ]
