# Generated by Django 5.1.4 on 2024-12-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_class_mandatory_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='mandatory_skills_new',
            new_name='mandatory_skills',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='trainable_skills_new',
            new_name='trainable_skills',
        ),
    ]
