# Generated by Django 3.2.9 on 2021-11-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_implement_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implement',
            name='implement_type',
        ),
    ]
