# Generated by Django 4.0 on 2021-12-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_attack_attribute_power_attack_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(
                blank=True,
                help_text='Имеющееся у персонажа вооружение. Если список не пустой, то оружие в руки выбирается из него.',
                to='base.Weapon',
                verbose_name='Вооружение',
            ),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(
                choices=[
                    ('BUGBEAR', 'Багбир'),
                    ('VRYLOKA', 'Врылока'),
                    ('HAMADRYAD', 'Гамадриада'),
                    ('GITHZERAI', 'Гитзерай'),
                    ('GNOLL', 'Гнолл'),
                    ('GNOME', 'Гном'),
                    ('GOBLIN', 'Гоблин'),
                    ('GOLIATH', 'Голиаф'),
                    ('DWARF', 'Дварф'),
                    ('DEVA', 'Дев'),
                    ('GENASI_WINDSOUL', 'Дженази, ветер'),
                    ('GENASI_WATERSOUL', 'Дженази, вода'),
                    ('GENASI_EARTHSOUL', 'Дженази, земля'),
                    ('GENASI_FIRESOUL', 'Дженази, огонь'),
                    ('GENASI_STORMSOUL', 'Дженази, шторм'),
                    ('WILDEN', 'Дикарь'),
                    ('DOPPELGANGER', 'Доппельгангер'),
                    ('DRAGONBORN', 'Драконорожденный'),
                    ('DROW', 'Дроу'),
                    ('DUERGAR', 'Дуэргар'),
                    ('KALASHTAR', 'Калаштар'),
                    ('KENKU', 'Кенку'),
                    ('KOBOLD', 'Кобольд'),
                    ('WARFORGED', 'Кованый'),
                    ('BLADELING', 'Мечерождённый'),
                    ('MINOTAUR', 'Минотавр'),
                    ('MUL', 'Мул'),
                    ('ORC', 'Орк'),
                    ('PIXIE', 'Пикси'),
                    ('HALFORC', 'Полуорк'),
                    ('HALFLING', 'Полурослик'),
                    ('HALFELF', 'Полуэльф'),
                    ('SATYR', 'Сатир'),
                    ('TIEFLING', 'Тифлинг'),
                    ('THRI_KREEN', 'Три-крин'),
                    ('HOBGOBLIN', 'Хобгоблин'),
                    ('HUMAN', 'Человек'),
                    ('SHADAR_KAI', 'Шадар-Кай'),
                    ('SHIFTER_RAZORCLAW', 'Шифтер, бритволапый'),
                    ('SHIFTER_LONGTEETH', 'Шифтер, длиннозубый'),
                    ('ELADRIN', 'Эладрин'),
                    ('ELF', 'Эльф'),
                ],
                max_length=17,
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
