# Generated by Django 4.0.2 on 2022-02-15 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_race_var_ability_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='var_bonus_ability',
            new_name='var_bonus_ability_old',
        ),
    ]
