# Generated by Django 5.1.4 on 2024-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_mandatory_skills_new_class_mandatory_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='trained_skills_new',
            field=models.ManyToManyField(
                blank=True, to='base.skillnew', verbose_name='Trained skills'
            ),
        ),
    ]
