# Generated by Django 3.1.3 on 2021-02-15 09:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20210215_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='category',
        ),
        migrations.AddField(
            model_name='class',
            name='available_weapon_categories_int',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                ],
                max_length=11,
                null=True,
                verbose_name='Владение категориями оружия',
            ),
        ),
    ]
