# Generated by Django 4.0.2 on 2022-02-12 09:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_magicitemtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='trained_skills',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('acrobatics', 'Акробатика'),
                    ('athletics', 'Атлетика'),
                    ('perception', 'Внимательность'),
                    ('thievery', 'Воровство'),
                    ('endurance', 'Выносливость'),
                    ('intimidate', 'Запугивание'),
                    ('streetwise', 'Знание улиц'),
                    ('history', 'История'),
                    ('arcana', 'Магия'),
                    ('bluff', 'Обман'),
                    ('diplomacy', 'Переговоры'),
                    ('dungeoneering', 'Подземелья'),
                    ('nature', 'Природа'),
                    ('insight', 'Проницательность'),
                    ('religion', 'Религия'),
                    ('stealth', 'Скрытность'),
                    ('heal', 'Целительство'),
                ],
                max_length=154,
                null=True,
                verbose_name='Trained skills',
            ),
        ),
    ]
