# Generated by Django 3.0.5 on 2020-11-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20201108_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='shield',
            field=models.CharField(
                blank=True,
                choices=[('LIGHT', 'Лёгкий'), ('HEAVY', 'Тяжелый')],
                max_length=5,
                null=True,
                verbose_name='Щит',
            ),
        ),
    ]
