# Generated by Django 4.0 on 2022-01-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_npc_weapons_alter_race_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='enchantment_old',
        ),
    ]
