# Generated by Django 3.2.9 on 2021-11-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_implement_implement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implement',
            old_name='slug',
            new_name='implement_type',
        ),
    ]
