# Generated by Django 4.0 on 2022-01-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_weapon_enchantment_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterParticipants',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50)),
                ('initiative', models.FloatField()),
                ('ac', models.PositiveSmallIntegerField()),
                ('fortitude', models.PositiveSmallIntegerField()),
                ('reflex', models.PositiveSmallIntegerField()),
                ('will', models.PositiveSmallIntegerField()),
                ('number', models.SmallIntegerField()),
                (
                    'encounter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='base.encounter',
                    ),
                ),
            ],
        ),
    ]
