# Generated by Django 3.0.5 on 2020-11-08 20:02

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_npc_shield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='available_armor_type',
            new_name='available_armor_types',
        ),
        migrations.AddField(
            model_name='class',
            name='available_shield_types',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[('LIGHT', 'Лёгкий'), ('HEAVY', 'Тяжелый')],
                max_length=11,
                null=True,
                verbose_name='Ношение щитов',
            ),
        ),
    ]
