# Generated by Django 3.2.9 on 2021-11-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_slug_implement_implement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='implement',
            old_name='implement_type',
            new_name='slug',
        ),
    ]
