# Generated by Django 4.0.2 on 2022-02-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0025_rename_var_bonus_ability_npc_var_bonus_ability_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='var_bonus_ability',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.ability',
                verbose_name='Выборочный бонус характеристики',
            ),
        ),
    ]
