# Generated by Django 5.1.3 on 2024-11-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_weapontype_handedness'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                null=True,
                verbose_name='Category',
            ),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='group',
            field=models.CharField(
                choices=[
                    ('crossbow', 'Арбалет'),
                    ('unarmed', 'Безоружное'),
                    ('mace', 'Булава'),
                    ('polearm', 'Древковое'),
                    ('pick', 'Кирка'),
                    ('spear', 'Копьё'),
                    ('bow', 'Лук'),
                    ('light_blade', 'Лёгкий клинок'),
                    ('hammer', 'Молот'),
                    ('staff', 'Посох'),
                    ('sling', 'Праща'),
                    ('axe', 'Топор'),
                    ('heavy_blade', 'Тяжелый клинок'),
                    ('flail', 'Цеп'),
                ],
                max_length=11,
                null=True,
                verbose_name='Group',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='handedness',
            field=models.CharField(
                choices=[
                    ('one', 'Одноручное'),
                    ('two', 'Двуручное'),
                    ('versatile', 'Универсальное'),
                    ('free', 'Не занимает руки'),
                ],
                max_length=9,
                null=True,
                verbose_name='Handedness',
            ),
        ),
    ]
