# Generated by Django 3.0.5 on 2020-11-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20201108_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='attack_bonus',
            field=models.SmallIntegerField(
                default=0, verbose_name='Бонус атаки (Оружие, инструменты + заточка'
            ),
        ),
    ]
