# Generated by Django 4.0.2 on 2022-02-15 20:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0026_npc_var_bonus_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='var_bonus_ability_old',
        ),
    ]
