# Generated by Django 4.0 on 2022-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_encounterparticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounterparticipants',
            name='number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
