# Generated by Django 5.1.3 on 2024-11-27 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_weapontype_category_weapontype_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='group',
        ),
    ]
