# Generated by Django 3.1.3 on 2021-02-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20210215_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='available_weapon_categories',
        ),
    ]
