# Generated by Django 3.2.9 on 2021-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_implement_type_implement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementtype',
            name='slug',
            field=models.CharField(max_length=20, verbose_name='Тип инструмента'),
        ),
    ]
