# Generated by Django 4.0 on 2022-01-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_encounterparticipants_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='name',
        ),
    ]
