# Generated by Django 5.1.3 on 2024-11-27 20:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_weapontype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('crossbow', 'Арбалет'),
                    ('unarmed', 'Безоружное'),
                    ('mace', 'Булава'),
                    ('polearm', 'Древковое'),
                    ('pick', 'Кирка'),
                    ('spear', 'Копьё'),
                    ('bow', 'Лук'),
                    ('light_blade', 'Лёгкий клинок'),
                    ('hammer', 'Молот'),
                    ('staff', 'Посох'),
                    ('sling', 'Праща'),
                    ('axe', 'Топор'),
                    ('heavy_blade', 'Тяжелый клинок'),
                    ('flail', 'Цеп'),
                ],
                max_length=97,
                null=True,
                verbose_name='Group',
            ),
        ),
    ]
