# Generated by Django 3.0.5 on 2020-11-08 20:27

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_npc_attack_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='attack_attributes',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default='STRENGTH',
                max_length=60,
                verbose_name='Атакующие характеристики',
            ),
        ),
    ]
