# Generated by Django 5.1.4 on 2024-12-23 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_trained_skills_new_npc_trained_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='skill',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.skillnew',
                verbose_name='Skill',
            ),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
