# Generated by Django 3.1.3 on 2021-02-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_class_available_weapon_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapontype',
            old_name='category_int',
            new_name='category',
        ),
    ]
