# Generated by Django 4.0.3 on 2022-04-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_ability_title_alter_npc_base_attack_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Сцена сыграна'),
        ),
    ]
