# Generated by Django 4.0 on 2022-01-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_weapon_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weapon',
            unique_together={('magic_item', 'level', 'weapon_type')},
        ),
    ]
