# Generated by Django 3.2.9 on 2021-11-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20211114_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='available_implement_types',
        ),
    ]
