# Generated by Django 3.1.3 on 2021-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20210215_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='available_weapon_categories_int',
            new_name='available_weapon_categories',
        ),
        migrations.AddField(
            model_name='power',
            name='damage_dice_int',
            field=models.SmallIntegerField(
                choices=[
                    (4, 'k4'),
                    (6, 'k6'),
                    (8, 'k8'),
                    (10, 'k10'),
                    (12, 'k12'),
                    (20, 'k20'),
                    (100, 'k100'),
                ],
                null=True,
                verbose_name='Кость урона',
            ),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='damage_dice_int',
            field=models.SmallIntegerField(
                choices=[
                    (4, 'k4'),
                    (6, 'k6'),
                    (8, 'k8'),
                    (10, 'k10'),
                    (12, 'k12'),
                    (20, 'k20'),
                    (100, 'k100'),
                ],
                null=True,
                verbose_name='Кость урона',
            ),
        ),
    ]
