# Generated by Django 5.1.4 on 2024-12-23 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_power_skill_delete_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillNew',
            new_name='Skill',
        ),
    ]
