# Generated by Django 5.1.3 on 2024-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_weapontype_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='group',
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='category',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Простое рукопашное'),
                    (2, 'Воинское рукопашное'),
                    (3, 'Превосходное рукопашное'),
                    (4, 'Простое дальнобойное'),
                    (5, 'Воинское дальнобойное'),
                    (6, 'Превосходное дальнобойное'),
                    (7, 'Инструмент'),
                ],
                default=0,
                verbose_name='Category',
            ),
            preserve_default=False,
        ),
    ]
