# Generated by Django 3.1.3 on 2021-02-15 10:42

from django.db import migrations

from base.constants.constants import DiceIntEnum


def category_migrate(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    WeaponType = apps.get_model('base', 'WeaponType')
    for power in Power.objects.all():
        power.damage_dice_int = (
            DiceIntEnum[power.damage_dice] if power.damage_dice else None
        )
        power.save()
    for weapon_type in WeaponType.objects.all():
        weapon_type.damage_dice_int = (
            DiceIntEnum[weapon_type.damage_dice] if weapon_type.damage_dice else None
        )
        weapon_type.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20210215_1042'),
    ]

    operations = [migrations.RunPython(category_migrate)]
