# Generated by Django 5.1.3 on 2024-11-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_weapontype_group_alter_weapontype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCParty',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(default='', max_length=20, verbose_name='Name'),
                ),
                (
                    'members',
                    models.ManyToManyField(
                        to='base.playercharacters', verbose_name='Members'
                    ),
                ),
            ],
        ),
    ]
