# Generated by Django 3.2.9 on 2021-11-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_class_available_implement_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='available_armor_types',
        ),
    ]
