# Generated by Django 4.0 on 2022-01-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_class_name_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name_new',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('ARTIFICER', 'Артефактор'),
                    ('BARD', 'Бард'),
                    ('VAMPIRE', 'Вампир'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('WARPRIEST', 'Военный священник (жрец)'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('SEEKER', 'Ловчий'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('SWORDMAGE', 'Мечник-маг'),
                    ('MONK', 'Монах'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER_MARKSMAN', 'Следопыт (Дальнобойный)'),
                    ('RANGER_MELEE', 'Следопыт (Рукопашник)'),
                    ('HEXBLADE', 'Хексблэйд (колдун)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=15,
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
