# Generated by Django 3.2.9 on 2021-11-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_class_available_armor_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttackPowerProperty',
        ),
    ]
