# Generated by Django 5.1.3 on 2024-11-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_pcparty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pcparty',
            options={'verbose_name': 'Party', 'verbose_name_plural': 'Parties'},
        ),
    ]
