# Generated by Django 4.0.4 on 2022-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0030_npc_is_bonus_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='is_bonus_applied',
            field=models.BooleanField(
                default=True,
                help_text='Бонус за уровень уменьшает количество исцелений',
                verbose_name='Применять бонус за уровень?',
            ),
        ),
    ]
