# Generated by Django 3.0.5 on 2020-11-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20201108_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='skill_penalty',
            field=models.SmallIntegerField(default=0, verbose_name='Штраф навыков'),
        ),
        migrations.AddField(
            model_name='armor',
            name='speed_penalty',
            field=models.SmallIntegerField(default=0, verbose_name='Штраф скорости'),
        ),
    ]
