# Generated by Django 3.1.3 on 2021-02-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20210215_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='damage_dice_int',
        ),
        migrations.AlterField(
            model_name='power',
            name='damage_dice',
            field=models.SmallIntegerField(
                choices=[
                    (4, 'k4'),
                    (6, 'k6'),
                    (8, 'k8'),
                    (10, 'k10'),
                    (12, 'k12'),
                    (20, 'k20'),
                    (100, 'k100'),
                ],
                null=True,
                verbose_name='Кость урона',
            ),
        ),
    ]
