# Generated by Django 4.0 on 2022-01-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_class_name_new_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name_new',
            field=models.CharField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('ARTIFICER', 'Артефактор'),
                    ('BARD', 'Бард'),
                    ('VAMPIRE', 'Вампир'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('WARPRIEST', 'Военный священник (жрец)'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('SEEKER', 'Ловчий'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('SWORDMAGE', 'Мечник-маг'),
                    ('MONK', 'Монах'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER_MARKSMAN', 'Следопыт (Дальнобойный)'),
                    ('RANGER_MELEE', 'Следопыт (Рукопашник)'),
                    ('HEXBLADE', 'Хексблэйд (колдун)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=15,
                null=True,
                verbose_name='Название',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.SmallIntegerField(
                choices=[
                    (10, 'Апостол'),
                    (20, 'Артефактор'),
                    (30, 'Бард'),
                    (35, 'Вампир'),
                    (40, 'Варвар'),
                    (50, 'Военачальник'),
                    (55, 'Военный священник (жрец)'),
                    (60, 'Воин'),
                    (70, 'Волшебник'),
                    (80, 'Друид'),
                    (90, 'Жрец'),
                    (95, 'Ловчий'),
                    (100, 'Каратель'),
                    (110, 'Колдун'),
                    (120, 'Мечник-маг'),
                    (125, 'Монах'),
                    (130, 'Паладин'),
                    (140, 'Плут'),
                    (150, 'Рунный жрец'),
                    (160, 'Следопыт (Дальнобойный)'),
                    (170, 'Следопыт (Рукопашник)'),
                    (175, 'Хексблэйд (колдун)'),
                    (180, 'Хранитель'),
                    (190, 'Чародей'),
                    (200, 'Шаман'),
                ],
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
