# Generated by Django 3.0.5 on 2020-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20201109_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='vision',
            field=models.CharField(
                choices=[
                    ('NORMAL', 'Обычное'),
                    ('TWILIGHT', 'Сумеречное'),
                    ('DARK', 'Тёмное'),
                ],
                default='TWILIGHT',
                max_length=8,
                verbose_name='Зрение',
            ),
        ),
    ]
