# Generated by Django 5.1.3 on 2024-11-29 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_pcparty_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='party',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.pcparty',
                verbose_name='Party',
            ),
        ),
        migrations.AlterField(
            model_name='pcparty',
            name='name',
            field=models.CharField(
                blank=True, default='', max_length=20, verbose_name='Name'
            ),
        ),
    ]
