# Generated by Django 3.2.9 on 2021-11-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_delete_attackpowerproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
