# Generated by Django 5.1.3 on 2024-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_encounter_party_alter_pcparty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='armortype',
            name='fortitude_bonus',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Fortitude bonus'
            ),
        ),
        migrations.AddField(
            model_name='armortype',
            name='reflex_bonus',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Reflex bonus'
            ),
        ),
        migrations.AddField(
            model_name='armortype',
            name='will_bonus',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Will bonus'
            ),
        ),
    ]
