# Generated by Django 3.2.9 on 2021-11-17 20:23

from django.db import migrations

property_title_to_power_attr = {
    # 'ATTACK': '',
    # 'HIT': 'hit_effect',
    'MISS': 'miss_effect',
    'EFFECT': 'effect',
    'REQUIREMENT': 'requirement',
    'TRIGGER': 'trigger',
    # 'TARGET': 'target',
    # 'SPECIAL': 'special',
}

abilities = ('str', 'con', 'dex', 'int', 'wis', 'cha')

kwargs = {}
for attr in abilities:
    modifier = f'{attr}_mod'
    kwargs.update(
        {
            modifier: f'${attr}',
            f'half_{modifier}': f'${attr}/2',
            f'{modifier}_add1': f'${attr}+1',
            f'{modifier}_add2': f'${attr}+2',
            f'{modifier}_add3': f'${attr}+3',
            f'{modifier}_add4': f'${attr}+4',
            f'{modifier}_add5': f'${attr}+5',
            f'{modifier}_add6': f'${attr}+6',
            f'{modifier}_add9': f'${attr}+9',
            f'{modifier}_add10': f'${attr}+10',
            f'{modifier}_add_halflevel': f'$lvl/2+{attr}',
        }
    )
kwargs.update(
    {
        'halflevel': '$lvl',
        'halflevel_add3': '$lvl+3',
        'halflevel_add5': '$lvl+5',
        'level_add2': '$lvl+2',
    }
)


def migrate_power_properties(apps, schema_editor):
    PowerProperty = apps.get_model('base', 'PowerProperty')
    Power = apps.get_model('base', 'Power')
    pps = []
    for power in Power.objects.all():
        if power.dice_number and power.attack_attribute:
            pps.append(
                PowerProperty(
                    power=power,
                    title='ATTACK',
                    level=power.level,
                    subclass=power.subclass,
                    description=f'${power.attack_attribute[:3].lower()}+atk+{power.attack_bonus}. {power.hit_effect or ""}',
                )
            )
        if power.accessory_type == 'WEAPON':
            pps.append(
                PowerProperty(
                    power=power,
                    title='HIT',
                    level=power.level,
                    subclass=power.subclass,
                    description=f'$wpn*{power.dice_number}+{power.attack_attribute[:3].lower()}+dmg. {power.hit_effect}',
                )
            )
        if power.accessory_type == 'IMPLEMENT':
            pps.append(
                PowerProperty(
                    power=power,
                    title='HIT',
                    level=power.level,
                    subclass=power.subclass,
                    description=f'{power.dice_number}{power.get_damage_dice_display()}+${power.attack_attribute[:3].lower()}+dmg. {power.hit_effect}',
                )
            )
        pps.append(
            PowerProperty(
                power=power,
                title='TARGET',
                level=power.level,
                subclass=power.subclass,
                description=power.target.target,
            )
        )
        for title, attr in property_title_to_power_attr.items():
            pps.append(
                PowerProperty(
                    power=power,
                    title=title,
                    level=power.level,
                    subclass=power.subclass,
                    description=getattr(power, attr),
                )
            )
    PowerProperty.objects.bulk_create(pps)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_powerproperty_description'),
    ]

    operations = [migrations.RunPython(migrate_power_properties)]
