# Generated by Django 4.0 on 2022-01-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_class_name_new_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
    ]
