# Generated by Django 3.1.3 on 2021-02-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20210215_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='armor_type_int',
            field=models.SmallIntegerField(
                choices=[
                    (10, 'Тканевый'),
                    (20, 'Кожаный'),
                    (30, 'Шкурный'),
                    (40, 'Кольчуга'),
                    (50, 'Чешуйчатый'),
                    (60, 'Латный'),
                ],
                default=0,
                verbose_name='Тип',
            ),
            preserve_default=False,
        ),
    ]
