# Generated by Django 4.1 on 2022-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_magicitemtype_slots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounterparticipants',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
