# Generated by Django 5.1.3 on 2024-11-29 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_armortype_fortitude_bonus_armortype_reflex_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='second_end',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='Second end',
            ),
        ),
    ]
