# Generated by Django 3.2.9 on 2021-11-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20211117_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='power',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='properties',
                to='base.power',
                verbose_name='Талант',
            ),
        ),
        migrations.AlterField(
            model_name='powerproperty',
            name='title',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ATTACK', 'Атака'),
                    ('SPECIAL', 'Особенность'),
                    ('HIT', 'Попадание'),
                    ('MISS', 'Промах'),
                    ('REQUIREMENT', 'Требование'),
                    ('TRIGGER', 'Триггер'),
                    ('TARGET', 'Цель'),
                    ('EFFECT', 'Эффект'),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
