# Generated by Django 4.1.6 on 2023-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0033_encounterparticipants_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.SlugField(
                choices=[
                    ('invoker', 'Апостол'),
                    ('artificer', 'Артефактор'),
                    ('bard', 'Бард'),
                    ('bladesinger', 'Блэйдсингер'),
                    ('vampire', 'Вампир'),
                    ('barbarian', 'Варвар'),
                    ('warlord', 'Военачальник'),
                    ('warpriest', 'Военный священник (жрец)'),
                    ('fighter', 'Воин'),
                    ('wizard', 'Волшебник'),
                    ('druid', 'Друид'),
                    ('priest', 'Жрец'),
                    ('seeker', 'Ловчий'),
                    ('avenger', 'Каратель'),
                    ('warlock', 'Колдун'),
                    ('swordmage', 'Мечник-маг'),
                    ('monk', 'Монах'),
                    ('paladin', 'Паладин'),
                    ('rogue', 'Плут'),
                    ('runepriest', 'Рунный жрец'),
                    ('ranger', 'Следопыт'),
                    ('ranger_melee', 'Следопыт (Рукопашник)'),
                    ('hexblade', 'Хексблэйд (колдун)'),
                    ('warden', 'Хранитель'),
                    ('sorcerer', 'Чародей'),
                    ('shaman', 'Шаман'),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='frequency',
            field=models.CharField(
                choices=[
                    ('PASSIVE', 'Пассивный'),
                    ('AT_WILL', 'Неограниченный'),
                    ('ENCOUNTER', 'На сцену'),
                    ('DAILY', 'На день'),
                ],
                max_length=9,
                verbose_name='Usage frequency',
            ),
        ),
    ]
