# Generated by Django 4.0 on 2022-01-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_class_options_remove_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name_new',
            new_name='name',
        ),
    ]
