# Generated by Django 3.2.9 on 2021-11-19 07:11

from django.db import migrations, models

property_title_to_order = {
    'ATTACK': 2,
    'HIT': 3,
    'MISS': 4,
    'EFFECT': 5,
    'REQUIREMENT': -1,
    'TRIGGER': 0,
    'TARGET': 1,
    'SPECIAL': 6,
}


def migrate_power_properties(apps, schema_editor):
    PowerProperty = apps.get_model('base', 'PowerProperty')
    for power_property in PowerProperty.objects.all():
        power_property.order = property_title_to_order[power_property.title]
        power_property.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20211119_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerproperty',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(migrate_power_properties),
    ]
