# Generated by Django 5.1.3 on 2024-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_magicweapontype_weapon_type_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Title'),
        ),
    ]
