# Generated by Django 4.0 on 2022-01-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_class_options_class_slug_alter_class_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='name_display',
        ),
    ]
