# Generated by Django 3.1.3 on 2021-02-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20210215_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='armor_type_int',
        ),
        migrations.AlterField(
            model_name='armor',
            name='armor_type',
            field=models.SmallIntegerField(
                choices=[
                    (10, 'Тканевый'),
                    (20, 'Кожаный'),
                    (30, 'Шкурный'),
                    (40, 'Кольчуга'),
                    (50, 'Чешуйчатый'),
                    (60, 'Латный'),
                ],
                verbose_name='Тип',
            ),
        ),
    ]
