# Generated by Django 4.2.4 on 2023-08-19 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0035_npc_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagonPath',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Description'),
                ),
                (
                    'klass',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.class',
                        verbose_name='Class',
                    ),
                ),
            ],
        ),
    ]
