# Generated by Django 4.0 on 2022-01-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_class_options_rename_name_class_name_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={
                'ordering': ('name',),
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.RenameField(
            model_name='class',
            old_name='slug',
            new_name='name',
        ),
    ]
