# Generated by Django 5.1.6 on 2025-03-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'base',
            '0036_rename_armor_types_m2m_availabilitycondition_armor_types_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstate',
            name='armor_m2m',
            field=models.ManyToManyField(
                blank=True, to='base.basearmortype', verbose_name='Armor type'
            ),
        ),
    ]
