# Generated by Django 3.1.3 on 2021-02-15 11:38

import multiselectfield.db.fields
from django.db import migrations

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20210215_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='available_armor_types_int',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    (10, 'Тканевый'),
                    (20, 'Кожаный'),
                    (30, 'Шкурный'),
                    (40, 'Кольчуга'),
                    (50, 'Чешуйчатый'),
                    (60, 'Латный'),
                ],
                default=base.constants.constants.ArmorTypeIntEnum['CLOTH'],
                max_length=17,
                verbose_name='Ношение доспехов',
            ),
        ),
    ]
