# Generated by Django 4.2.4 on 2023-08-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0036_paragonpath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paragonpath',
            options={
                'verbose_name': 'Paragon path',
                'verbose_name_plural': 'Paragon paths',
            },
        ),
        migrations.AddField(
            model_name='paragonpath',
            name='powers',
            field=models.ManyToManyField(
                blank=True, to='base.power', verbose_name='Powers'
            ),
        ),
    ]
