# Generated by Django 3.0.5 on 2020-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20201109_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='sex',
            field=models.CharField(
                choices=[('M', 'Муж'), ('F', 'Жен'), ('N', 'Н/Д')],
                max_length=1,
                verbose_name='Пол',
            ),
        ),
    ]
