# Generated by Django 5.1.3 on 2024-11-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_weapontype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='second_end',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='Second end',
            ),
        ),
    ]
