# Generated by Django 3.1.3 on 2020-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20201110_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='racebonus',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='racebonus',
            name='name',
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name='Название'
            ),
        ),
        migrations.AlterField(
            model_name='racebonus',
            name='bonus',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
