# Generated by Django 5.1.6 on 2025-03-05 20:26

from django.db import migrations


def fill_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ItemState = apps.get_model('base', 'ItemState')
    BaseArmorType = apps.get_model('base', 'BaseArmorType')
    for its in ItemState.objects.all():
        for armor in its.armor or []:
            its.armor_m2m.add(BaseArmorType.objects.get(armor_class=int(armor)))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_itemstate_armor_m2m'),
    ]

    operations = [migrations.RunPython(fill_data)]
