# Generated by Django 4.2.4 on 2023-08-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0037_alter_paragonpath_options_paragonpath_powers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragonpath',
            name='powers',
        ),
        migrations.AddField(
            model_name='power',
            name='paragon_path',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='paragon_path',
                to='base.paragonpath',
                verbose_name='Paragon path',
            ),
        ),
    ]
