# Generated by Django 3.2.9 on 2021-11-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='powerproperty',
            name='title',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ATTACK', 'Атака'),
                    ('SPECIAL', 'Особенность'),
                    ('SUSTAIN_MINOR', 'Поддержка малым'),
                    ('SUSTAIN_STANDARD', 'Поддержка стандартным'),
                    ('HIT', 'Попадание'),
                    ('MISS', 'Промах'),
                    ('REQUIREMENT', 'Требование'),
                    ('TRIGGER', 'Триггер'),
                    ('TARGET', 'Цель'),
                    ('EFFECT', 'Эффект'),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
