# Generated by Django 3.2.9 on 2021-11-22 14:53

from django.db import migrations

# MELEE_WEAPON = 'Рукопашное оружие'
# MELEE_DISTANCE = 'Рукопашное (дистанция)'
# MELEE_TOUCH = 'Рукопашное касание'
# MELEE_RANGED_WEAPON = 'Рукопашное или дальнобойное оружие'
# PERSONAL = 'Персональный'
# RANGED_WEAPON = 'Дальнобойное оружие'
# RANGED_DISTANCE = 'Дальнобойное (дистанция)'
# RANGED_SIGHT = 'Дальнобойное (видимость)'
# CLOSE_BURST = 'Ближняя вспышка'
# CLOSE_BLAST = 'Ближняя волна'
# AREA_BURST = 'Зональная вспышка'
# AREA_WALL = 'Стена'


def migrate_power_properties(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    for power in Power.objects.all():
        if power.range_type in (
            'CLOSE_BURST',
            'CLOSE_BLAST',
            'PERSONAL',
            'MELEE_WEAPON',
            'MELEE_TOUCH',
            'MELEE_RANGED_WEAPON',
            'RANGED_WEAPON',
            'RANGED_SIGHT',
        ):
            power.range = 0
        if power.range_type in (
            'MELEE_WEAPON',
            'MELEE_DISTANCE',
            'MELEE_TOUCH',
            'MELEE_RANGED_WEAPON',
            'PERSONAL',
            'RANGED_WEAPON',
            'RANGED_SIGHT',
        ):
            power.burst = 0
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20211121_2020'),
    ]

    operations = []
