# Generated by Django 4.2.4 on 2023-08-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0038_remove_paragonpath_powers_power_paragon_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerproperty',
            options={
                'verbose_name': 'PowerProperty',
                'verbose_name_plural': 'PowersProperties',
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='paragon_path',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.paragonpath',
                verbose_name='Paragon path',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='paragon_path',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.paragonpath',
                verbose_name='Paragon path',
            ),
        ),
    ]
