# Generated by Django 3.1.3 on 2020-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20201110_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racebonus',
            options={
                'verbose_name': 'Расовый бонус',
                'verbose_name_plural': 'Расовые бонусы',
            },
        ),
        migrations.AlterField(
            model_name='racebonus',
            name='name',
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name='Название'
            ),
        ),
    ]
