# Generated by Django 5.1.3 on 2024-11-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_weapontype_second_end_weapontype_primary_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='primary_end',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='secondary_end',
                to='base.weapontype',
                verbose_name='Primary end',
            ),
        ),
    ]
