# Generated by Django 5.1.6 on 2025-03-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20250305_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armortype',
            name='base_armor_type',
        ),
        migrations.RemoveField(
            model_name='itemstate',
            name='armor',
        ),
    ]
