# Generated by Django 3.1.3 on 2021-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_class_name_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('ARTIFICER', 'Артефактор'),
                    ('BARD', 'Бард'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('SWORDMAGE', 'Мечник-маг'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER_MARKSMAN', 'Следопыт (Дальнобойный)'),
                    ('RANGER_MELEE', 'Следопыт (Рукопашник)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=15,
                verbose_name='Название_deprecated',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='name_int',
            field=models.SmallIntegerField(
                choices=[
                    (10, 'Апостол'),
                    (20, 'Артефактор'),
                    (30, 'Бард'),
                    (40, 'Варвар'),
                    (50, 'Военачальник'),
                    (60, 'Воин'),
                    (70, 'Волшебник'),
                    (80, 'Друид'),
                    (90, 'Жрец'),
                    (100, 'Каратель'),
                    (110, 'Колдун'),
                    (120, 'Мечник-маг'),
                    (130, 'Паладин'),
                    (140, 'Плут'),
                    (150, 'Рунный жрец'),
                    (160, 'Следопыт (Дальнобойный)'),
                    (170, 'Следопыт (Рукопашник)'),
                    (180, 'Хранитель'),
                    (190, 'Чародей'),
                    (200, 'Шаман'),
                ],
                unique=True,
                verbose_name='Название',
            ),
        ),
    ]
