# Generated by Django 4.1.6 on 2023-08-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0039_alter_powerproperty_options_npc_paragon_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='trained_weapons',
            field=models.ManyToManyField(
                help_text='Weapon training in addition to training by race and class',
                to='base.weapontype',
                verbose_name='Trained weapon',
            ),
        ),
    ]
