# Generated by Django 4.0 on 2022-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_class_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name_display',
            field=models.CharField(max_length=24, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='race',
            name='is_sociable',
            field=models.BooleanField(
                default=True,
                help_text='Социальные расы используются для случайной генерации NPC',
                verbose_name='Социальная раса',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='slug',
            field=models.CharField(max_length=30, unique=True, verbose_name='Slug'),
        ),
    ]
