# Generated by Django 5.1.3 on 2024-11-30 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_magicweapontype_weapon_type_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='armor_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.armortype',
                verbose_name='Armor type',
            ),
        ),
    ]
