# Generated by Django 4.1.6 on 2023-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0040_npc_trained_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='trained_weapons',
            field=models.ManyToManyField(
                blank=True,
                help_text='Weapon training in addition to training by race and class',
                to='base.weapontype',
                verbose_name='Trained weapon',
            ),
        ),
    ]
