# Generated by Django 3.2.9 on 2021-11-23 09:06
import enum

from django.db import migrations


class PowerRangeTypeEnum(str, enum.Enum):
    MELEE_WEAPON = 'Рукопашное оружие'
    MELEE = 'Рукопашное'
    RANGED = 'Дальнобойное'
    BURST = 'Вспышка'
    BLAST = 'Волна'
    WALL = 'Стена'
    MELEE_RANGED_WEAPON = 'Рукопашное или дальнобойное оружие'
    PERSONAL = 'Персональный'
    RANGED_WEAPON = 'Дальнобойное оружие'

    MELEE_DISTANCE = 'Рукопашное (дистанция)'
    MELEE_TOUCH = 'Рукопашное касание'
    RANGED_DISTANCE = 'Дальнобойное (дистанция)'
    RANGED_SIGHT = 'Дальнобойное (видимость)'
    CLOSE_BURST = 'Ближняя вспышка'
    CLOSE_BLAST = 'Ближняя волна'
    AREA_BURST = 'Зональная вспышка'
    AREA_WALL = 'Стена'


def migrate_power_properties(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    for power in Power.objects.all():
        if power.range_type in ('MELEE_DISTANCE', 'MELEE_TOUCH'):
            power.range_type = 'MELEE'
        if power.range_type in ('RANGED_DISTANCE', 'RANGED_SIGHT'):
            power.range_type = 'RANGED'
        if power.range_type in ('CLOSE_BURST', 'AREA_BURST'):
            power.range_type = 'BURST'
        if power.range_type == 'AREA_WALL':
            power.range_type = 'WALL'
        if power.range_type == 'CLOSE_BLAST':
            power.range_type = 'BLAST'
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20211122_1937'),
    ]

    operations = [migrations.RunPython(migrate_power_properties)]
