# Generated by Django 5.1.3 on 2024-11-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_armor_armor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
