# Generated by Django 3.1.3 on 2020-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20201110_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='other_bonuses',
            field=models.ImageField(
                blank=True, null=True, upload_to='images/', verbose_name='Картинка'
            ),
        ),
    ]
