# Generated by Django 3.1.3 on 2020-11-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_race_other_bonuses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaceBonus',
        ),
    ]
