# Generated by Django 3.1.3 on 2021-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20210215_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='target',
            field=models.CharField(
                default='Одно существо', max_length=50, null=True, verbose_name='Цель'
            ),
        ),
    ]
