# Generated by Django 5.1.3 on 2024-11-12 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_npc_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragonpath',
            name='race',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.race',
                verbose_name='Race',
            ),
        ),
        migrations.AlterField(
            model_name='paragonpath',
            name='klass',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.class',
                verbose_name='Class',
            ),
        ),
    ]
