# Generated by Django 5.1.3 on 2024-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_powerproperty_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
