# Generated by Django 3.2.9 on 2021-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20211123_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='range_type',
            field=models.CharField(
                choices=[
                    ('MELEE_WEAPON', 'Рукопашное оружие'),
                    ('MELEE', 'Рукопашное'),
                    ('RANGED', 'Дальнобойное'),
                    ('BURST', 'Вспышка'),
                    ('BLAST', 'Волна'),
                    ('WALL', 'Стена'),
                    ('MELEE_RANGED_WEAPON', 'Рукопашное или дальнобойное оружие'),
                    ('PERSONAL', 'Персональный'),
                    ('RANGED_WEAPON', 'Дальнобойное оружие'),
                    ('MELEE_DISTANCE', 'Рукопашное (дистанция)'),
                    ('MELEE_TOUCH', 'Рукопашное касание'),
                    ('RANGED_DISTANCE', 'Дальнобойное (дистанция)'),
                    ('RANGED_SIGHT', 'Дальнобойное (видимость)'),
                    ('CLOSE_BURST', 'Ближняя вспышка'),
                    ('CLOSE_BLAST', 'Ближняя волна'),
                    ('AREA_BURST', 'Зональная вспышка'),
                ],
                default='PERSONAL',
                max_length=19,
                verbose_name='Дальность',
            ),
        ),
    ]
