# Generated by Django 3.1.3 on 2021-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20210216_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='subclass',
            field=models.SmallIntegerField(choices=[], verbose_name='Подкласс'),
        ),
    ]
