# Generated by Django 5.1.2 on 2024-11-13 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_paragonpath_race_alter_paragonpath_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragonpath',
            name='klass',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.class',
                verbose_name='Class',
            ),
        ),
        migrations.AlterField(
            model_name='paragonpath',
            name='race',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.race',
                verbose_name='Race',
            ),
        ),
    ]
