# Generated by Django 3.2.9 on 2021-11-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_power_range_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='range_type',
            field=models.CharField(
                choices=[
                    ('MELEE_WEAPON', 'Рукопашное оружие'),
                    ('MELEE', 'Рукопашное'),
                    ('RANGED', 'Дальнобойное'),
                    ('BURST', 'Вспышка'),
                    ('BLAST', 'Волна'),
                    ('WALL', 'Стена'),
                    ('MELEE_RANGED_WEAPON', 'Рукопашное или дальнобойное оружие'),
                    ('PERSONAL', 'Персональный'),
                    ('RANGED_WEAPON', 'Дальнобойное оружие'),
                ],
                default='PERSONAL',
                max_length=19,
                verbose_name='Дальность',
            ),
        ),
    ]
