# Generated by Django 3.1.3 on 2020-11-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20201111_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='other_bonuses',
        ),
    ]
