# Generated by Django 5.1.2 on 2024-11-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_alter_paragonpath_klass_alter_paragonpath_race'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('CLASS', 'Бонус класса'),
                            ('ITEM', 'Бонус предмета'),
                            ('POWER', 'Бонус таланта'),
                            ('FEAT', 'Бонус черты'),
                            ('RACE', 'Расовый бонус'),
                        ],
                        max_length=5,
                        verbose_name='Bonus type',
                    ),
                ),
                (
                    'min_level',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Minimal level'
                    ),
                ),
                (
                    'value',
                    models.PositiveSmallIntegerField(default=0, verbose_name='Value'),
                ),
                (
                    'text_value',
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name='Text value'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuses',
            },
        ),
        migrations.AddField(
            model_name='armor',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
        migrations.AddField(
            model_name='armsslotitem',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
        migrations.AddField(
            model_name='simplemagicitem',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
        migrations.AddField(
            model_name='weapon',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
    ]
