# Generated by Django 5.1.3 on 2024-12-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_magicitemtype_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.SlugField(
                choices=[
                    ('INVOKER', 'Апостол'),
                    ('ARTIFICER', 'Артефактор'),
                    ('BARD', 'Бард'),
                    ('BLADESINGER', 'Блэйдсингер'),
                    ('VAMPIRE', 'Вампир'),
                    ('BARBARIAN', 'Варвар'),
                    ('WARLORD', 'Военачальник'),
                    ('WARPRIEST', 'Военный священник (жрец)'),
                    ('FIGHTER', 'Воин'),
                    ('WIZARD', 'Волшебник'),
                    ('DRUID', 'Друид'),
                    ('PRIEST', 'Жрец'),
                    ('SEEKER', 'Ловчий'),
                    ('AVENGER', 'Каратель'),
                    ('WARLOCK', 'Колдун'),
                    ('SWORDMAGE', 'Мечник-маг'),
                    ('MONK', 'Монах'),
                    ('PALADIN', 'Паладин'),
                    ('ROGUE', 'Плут'),
                    ('RUNEPRIEST', 'Рунный жрец'),
                    ('RANGER', 'Следопыт'),
                    ('RANGER_MELEE', 'Следопыт (Рукопашник)'),
                    ('HEXBLADE', 'Хексблэйд (колдун)'),
                    ('WARDEN', 'Хранитель'),
                    ('SORCERER', 'Чародей'),
                    ('SHAMAN', 'Шаман'),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(
                choices=[
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('PERCEPTION', 'Внимательность'),
                    ('THIEVERY', 'Воровство'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('HISTORY', 'История'),
                    ('ARCANA', 'Магия'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('INSIGHT', 'Проницательность'),
                    ('RELIGION', 'Религия'),
                    ('STEALTH', 'Скрытность'),
                    ('HEAL', 'Целительство'),
                ],
                max_length=13,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='handedness',
            field=models.CharField(
                choices=[
                    ('ONE', 'Одноручное'),
                    ('TWO', 'Двуручное'),
                    ('VERSATILE', 'Универсальное'),
                    ('FREE', 'Не занимает руки'),
                    ('DOUBLE', 'Двойное'),
                ],
                max_length=9,
                null=True,
                verbose_name='Handedness',
            ),
        ),
    ]
