# Generated by Django 3.2.9 on 2021-11-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_alter_power_range_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='available_weapon_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='Требования к оружию (для талантов с оружием)',
            ),
        ),
    ]
