# Generated by Django 5.1.2 on 2024-11-14 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_bonus_armor_bonus_armsslotitem_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
    ]
