# Generated by Django 3.1.3 on 2020-11-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_race_other_bonuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceBonus',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        blank=True, max_length=30, verbose_name='Название'
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                (
                    'race',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='base.race'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Бонус',
                'verbose_name_plural': 'Бонусы',
            },
        ),
    ]
