# Generated by Django 5.1.2 on 2024-11-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_power_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='type',
        ),
        migrations.AddField(
            model_name='bonus',
            name='bonus_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ACROBATICS', 'Акробатика'),
                    ('ATHLETICS', 'Атлетика'),
                    ('PERCEPTION', 'Внимательность'),
                    ('WILL', 'Воля'),
                    ('THIEVERY', 'Воровство'),
                    ('ENDURANCE', 'Выносливость'),
                    ('INTIMIDATE', 'Запугивание'),
                    ('STREETWISE', 'Знание улиц'),
                    ('INITIATIVE', 'Инициатива'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('HISTORY', 'История'),
                    ('ARMOR_CLASS', 'КД'),
                    ('DEXTERITY', 'Ловкость'),
                    ('ARCANA', 'Магия'),
                    ('WISDOM', 'Мудрость'),
                    ('BLUFF', 'Обман'),
                    ('DIPLOMACY', 'Переговоры'),
                    ('DUNGEONEERING', 'Подземелья'),
                    ('NATURE', 'Природа'),
                    ('INSIGHT', 'Проницательность'),
                    ('REFLEX', 'Реакция'),
                    ('RELIGION', 'Религия'),
                    ('STRENGTH', 'Сила'),
                    ('SPEED', 'Скорость'),
                    ('STEALTH', 'Скрытность'),
                    ('FORTITUDE', 'Стойкость'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('CHARISMA', 'Харизма'),
                    ('HEAL', 'Целительство'),
                ],
                max_length=13,
                null=True,
                verbose_name='Bonus type',
            ),
        ),
        migrations.AddField(
            model_name='bonus',
            name='source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CLASS', 'Бонус класса'),
                    ('ITEM', 'Бонус предмета'),
                    ('POWER', 'Бонус таланта'),
                    ('FEAT', 'Бонус черты'),
                    ('RACE', 'Расовый бонус'),
                ],
                max_length=5,
                null=True,
                verbose_name='Bonus source',
            ),
        ),
    ]
