# Generated by Django 3.1.3 on 2021-02-18 10:22

from django.db import migrations, models

import base.constants.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_auto_20210217_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='range_type',
            field=models.CharField(
                choices=[
                    ('MELEE_WEAPON', 'Рукопашное оружие'),
                    ('MELEE_DISTANCE', 'Рукопашное (дистанция)'),
                    ('MELEE_TOUCH', 'Рукопашное касание'),
                    ('MELEE_RANGED_WEAPON', 'Рукопашное или дальнобойное оружие'),
                    ('PERSONAL', 'Персональный'),
                    ('RANGED_WEAPON', 'Дальнобойное оружие'),
                    ('RANGED_DISTANCE', 'Дальнобойное (дистанция)'),
                    ('RANGED_SIGHT', 'Дальнобойное (видимость)'),
                    ('CLOSE_BURST', 'Ближняя вспышка'),
                    ('CLOSE_BLAST', 'Ближняя волна'),
                    ('AREA_BURST', 'Зональная вспышка'),
                    ('AREA_WALL', 'Стена'),
                ],
                default=base.constants.constants.PowerRangeTypeEnum['MELEE_WEAPON'],
                max_length=19,
                verbose_name='Дальность',
            ),
        ),
    ]
