# Generated by Django 3.2.9 on 2021-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_power_available_weapon_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='available_weapon_type',
        ),
        migrations.AddField(
            model_name='power',
            name='available_weapon_types',
            field=models.ManyToManyField(
                help_text='для талантов с оружием',
                null=True,
                to='base.WeaponType',
                verbose_name='Требования к оружию',
            ),
        ),
    ]
