# Generated by Django 3.2.9 on 2021-11-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20211123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='available_weapon_types',
            field=models.ManyToManyField(
                help_text='для талантов с оружием',
                to='base.WeaponType',
                verbose_name='Требования к оружию',
            ),
        ),
    ]
