# Generated by Django 3.1.3 on 2021-02-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20210218_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='target',
            field=models.CharField(
                blank=True,
                default='Одно существо',
                max_length=50,
                null=True,
                verbose_name='Цель',
            ),
        ),
    ]
