# Generated by Django 3.2.9 on 2021-11-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_power_available_weapon_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combatants',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=50, verbose_name='Участники сцены'),
                ),
                (
                    'initiative',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Инициатива'
                    ),
                ),
                (
                    'number',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Количество однотипных'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='encounter',
            name='other_combatants',
            field=models.ManyToManyField(
                to='base.Combatants', verbose_name='Другие участники сцены'
            ),
        ),
    ]
