# Generated by Django 5.1.2 on 2024-11-14 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_bonus_bonus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='bonus',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.bonus',
                verbose_name='Bonus',
            ),
        ),
    ]
