# Generated by Django 3.1.3 on 2020-11-13 14:40

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20201113_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='available_implement_type',
            field=models.ManyToManyField(to='base.ImplementType'),
        ),
        migrations.AddField(
            model_name='class',
            name='available_weapon_category',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('MILITARY', 'Воинское'),
                    ('SUPERIOR', 'Превосходное'),
                    ('SIMPLE', 'Простое'),
                ],
                max_length=24,
                null=True,
                verbose_name='Доступные категории оружия',
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='available_weapon_type',
            field=models.ManyToManyField(
                to='base.WeaponType', verbose_name='Доступные типы оружия'
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='is_weapon_implement',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='npc',
            name='implements',
            field=models.ManyToManyField(
                to='base.Implement', verbose_name='Инструменты'
            ),
        ),
        migrations.AddField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(to='base.Weapon', verbose_name='Оружия'),
        ),
    ]
