# Generated by Django 3.2.9 on 2021-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20211124_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatants',
            name='is_player',
            field=models.BooleanField(default=False, verbose_name='Игровой персонаж?'),
        ),
        migrations.AlterField(
            model_name='combatants',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Участник сцены'),
        ),
    ]
