# Generated by Django 3.1.3 on 2020-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20201113_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='implements',
            field=models.ManyToManyField(
                to='base.Implement', verbose_name='Инструменты'
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='weapons',
            field=models.ManyToManyField(to='base.Weapon', verbose_name='Оружия'),
        ),
        migrations.AlterField(
            model_name='class',
            name='is_weapon_implement',
            field=models.BooleanField(
                default=False, verbose_name='Оружие как инструмент'
            ),
        ),
    ]
