# Generated by Django 5.1.2 on 2024-11-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_race_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='name',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Title'
            ),
        ),
    ]
