# Generated by Django 3.1.3 on 2020-11-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20201113_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='available_implement_type',
            field=models.ManyToManyField(
                to='base.ImplementType', verbose_name='Доступные инструменты'
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='weapons',
            field=models.ManyToManyField(to='base.Weapon', verbose_name='Оружиe'),
        ),
    ]
