# Generated by Django 5.1.2 on 2024-11-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_bonus_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='bonus',
        ),
        migrations.AddField(
            model_name='race',
            name='bonus',
            field=models.ManyToManyField(
                blank=True, to='base.bonus', verbose_name='Bonus'
            ),
        ),
    ]
