# Generated by Django 3.2.9 on 2021-11-24 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20211124_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='other_combatants',
        ),
        migrations.AddField(
            model_name='combatants',
            name='encounter',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.encounter',
                verbose_name='Сцена',
            ),
        ),
    ]
