# Generated by Django 3.1.3 on 2020-11-13 16:09

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20201113_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружие'},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={
                'verbose_name': 'Тип оружия',
                'verbose_name_plural': 'Типы оружия',
            },
        ),
        migrations.AlterField(
            model_name='class',
            name='available_weapon_category',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('SIMPLE', 'Простое'),
                    ('MILITARY', 'Воинское'),
                    ('SUPERIOR', 'Превосходное'),
                ],
                max_length=24,
                null=True,
                verbose_name='Владение категориями оружия',
            ),
        ),
        migrations.AlterField(
            model_name='class',
            name='available_weapon_type',
            field=models.ManyToManyField(
                blank=True, to='base.WeaponType', verbose_name='Владение оружием'
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(to='base.Weapon', verbose_name='Оружие'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
