# Generated by Django 3.1.3 on 2020-11-13 16:13

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20201113_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='properties',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('HIGH_CRIT', 'Высококритичное'),
                    ('OFF_HAND', 'Дополнительное'),
                    ('REACH', 'Досягаемость'),
                    ('LIGHT_THROWN', 'Лёгкое метательное'),
                    ('HEAVY_THROWN', 'Тяжелое метательное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                default='VERSATILE',
                max_length=60,
                verbose_name='Свойства',
            ),
            preserve_default=False,
        ),
    ]
