# Generated by Django 3.1.3 on 2020-11-13 16:16

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_weapontype_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='damage',
            field=models.CharField(
                choices=[
                    ('D4', '1k4'),
                    ('D6', '1k6'),
                    ('D8', '1k8'),
                    ('D10', '1k10'),
                    ('D12', '1k12'),
                    ('D2_4', '2k4'),
                    ('D2_6', '2k6'),
                    ('D2_8', '2k8'),
                    ('D2_10', '2k10'),
                ],
                max_length=5,
                verbose_name='Кость урона',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='properties',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('HIGH_CRIT', 'Высококритичное'),
                    ('OFF_HAND', 'Дополнительное'),
                    ('REACH', 'Досягаемость'),
                    ('LIGHT_THROWN', 'Лёгкое метательное'),
                    ('HEAVY_THROWN', 'Тяжелое метательное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                max_length=60,
                null=True,
                verbose_name='Свойства',
            ),
        ),
    ]
