# Generated by Django 3.1.3 on 2021-02-19 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20210219_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerProperty',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('ATTACK', 'Атака'),
                            ('SPECIAL', 'Особенность'),
                            ('HIT', 'Попадание'),
                            ('MISS', 'Промах'),
                            ('REQUIREMENT', 'Требование'),
                            ('TRIGGER', 'Триггер'),
                            ('EFFECT', 'Эффект'),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    'subclass_title',
                    models.SmallIntegerField(
                        choices=[], default=0, verbose_name='Подкласс'
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'power',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.power',
                        verbose_name='Талант',
                    ),
                ),
            ],
        ),
    ]
