# Generated by Django 3.2.9 on 2021-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_auto_20211126_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='subclass',
            field=models.SmallIntegerField(default=0, verbose_name='Подкласс'),
        ),
    ]
