# Generated by Django 3.1.3 on 2020-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20201113_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='handedness',
            field=models.CharField(
                choices=[('ONE', 'Одноручное'), ('TWO', 'Двуручное')],
                default='ONE',
                max_length=3,
                verbose_name='Одноручное/Двуручное',
            ),
        ),
    ]
