# Generated by Django 3.2.9 on 2021-11-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_power_subclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacters',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('armor_class', models.PositiveSmallIntegerField(verbose_name='КД')),
                (
                    'fortitude',
                    models.PositiveSmallIntegerField(verbose_name='Стойкость'),
                ),
                ('reflex', models.PositiveSmallIntegerField(verbose_name='Реакция')),
                ('will', models.PositiveSmallIntegerField(verbose_name='Воля')),
                (
                    'initiative',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Инициатива'
                    ),
                ),
                (
                    'passive_perception',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Пассивная внимательность'
                    ),
                ),
                (
                    'passive_insight',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Пассивная проницательность'
                    ),
                ),
            ],
        ),
    ]
