# Generated by Django 3.1.3 on 2021-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_powerproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalTemplate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                (
                    'min_level',
                    models.SmallIntegerField(
                        default=0, verbose_name='Минимальный уровень'
                    ),
                ),
                (
                    'armor_class_bonus',
                    models.SmallIntegerField(default=0, verbose_name='Бонус КД'),
                ),
                (
                    'fortitude_bonus',
                    models.SmallIntegerField(default=0, verbose_name='Бонус стойкости'),
                ),
                (
                    'reflex_bonus',
                    models.SmallIntegerField(default=0, verbose_name='Бонус реакции'),
                ),
                (
                    'will_bonus',
                    models.SmallIntegerField(default=0, verbose_name='Бонус воли'),
                ),
                (
                    'save_bonus',
                    models.SmallIntegerField(
                        default=2, verbose_name='Бонус спасбросков'
                    ),
                ),
                (
                    'action_points_bonus',
                    models.SmallIntegerField(
                        default=1, verbose_name='Дополнительные очки действия'
                    ),
                ),
                (
                    'hit_points_per_level',
                    models.SmallIntegerField(default=8, verbose_name='Хиты за уровень'),
                ),
            ],
        ),
        migrations.RenameField(
            model_name='powerproperty',
            old_name='subclass_title',
            new_name='subclass',
        ),
    ]
