# Generated by Django 3.1.3 on 2020-11-13 16:36

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_weapontype_handedness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='group',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('MACE', 'Булава'),
                    ('POLEARM', 'Древковое'),
                    ('PICK', 'Кирка'),
                    ('SPEAR', 'Копьё'),
                    ('LIGHT_BLADE', 'Лёгкий клинок'),
                    ('HAMMER', 'Молот'),
                    ('STAFF', 'Посох'),
                    ('AXE', 'Топор'),
                    ('HEAVY_BLADE', 'Тяжелый клинок'),
                    ('FLAIL', 'Цеп'),
                ],
                max_length=70,
                verbose_name='Группа оружия',
            ),
        ),
    ]
