# Generated by Django 3.2.9 on 2021-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_playercharacters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playercharacters',
            options={
                'verbose_name': 'Игровой персонаж',
                'verbose_name_plural': 'Игровые персонажи',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='pcs',
            field=models.ManyToManyField(
                to='base.PlayerCharacters', verbose_name='Игровые персонажи'
            ),
        ),
    ]
