# Generated by Django 3.1.3 on 2020-11-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20201113_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='Тип оружия',
            ),
        ),
    ]
