# Generated by Django 3.1.3 on 2021-02-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_power_functional_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaltemplate',
            options={
                'verbose_name': 'Функциональный шаблон',
                'verbose_name_plural': 'Фунециональные шаблоны',
            },
        ),
    ]
