# Generated by Django 3.2.9 on 2021-11-28 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20211128_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combatants',
            name='is_player',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='pcs',
        ),
        migrations.AddField(
            model_name='combatants',
            name='armor_class',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='КД'),
        ),
        migrations.AddField(
            model_name='combatants',
            name='fortitude',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Стойкость'),
        ),
        migrations.AddField(
            model_name='combatants',
            name='reflex',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Реакция'),
        ),
        migrations.AddField(
            model_name='combatants',
            name='will',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Воля'),
        ),
        migrations.CreateModel(
            name='CombatantsPC',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'initiative',
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name='Инициатива'
                    ),
                ),
                (
                    'encounter',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='combatants_pcs',
                        to='base.encounter',
                        verbose_name='Сцена',
                    ),
                ),
                (
                    'pc',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.playercharacters',
                        verbose_name='Игровой персонаж',
                    ),
                ),
            ],
        ),
    ]
