# Generated by Django 3.1.3 on 2020-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20201113_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='available_weapon_category',
            new_name='available_weapon_categories',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='available_weapon_type',
            new_name='available_weapon_types',
        ),
        migrations.AddField(
            model_name='race',
            name='available_weapon_types',
            field=models.ManyToManyField(
                blank=True, to='base.WeaponType', verbose_name='Владение оружием'
            ),
        ),
        migrations.AlterField(
            model_name='npc',
            name='weapons',
            field=models.ManyToManyField(
                blank=True, to='base.Weapon', verbose_name='Оружие'
            ),
        ),
    ]
