# Generated by Django 3.2.9 on 2021-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20211128_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerproperty',
            name='title',
            field=models.CharField(
                blank=True,
                choices=[
                    ('OTHER', ''),
                    ('ATTACK', 'Атака'),
                    ('SPECIAL', 'Особенность'),
                    ('SUSTAIN_MINOR', 'Поддержка малым'),
                    ('SUSTAIN_STANDARD', 'Поддержка стандартным'),
                    ('HIT', 'Попадание'),
                    ('MISS', 'Промах'),
                    ('REQUIREMENT', 'Требование'),
                    ('TRIGGER', 'Триггер'),
                    ('TARGET', 'Цель'),
                    ('EFFECT', 'Эффект'),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
