# Generated by Django 3.1.3 on 2020-11-16 17:32

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20201116_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='available_weapon_categories',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('SIMPLE', 'Простое рукопашное'),
                    ('MILITARY', 'Воинское рукопашное'),
                    ('SUPERIOR', 'Превосходное рукопашное'),
                    ('SIMPLE_RANGED', 'Простое дальнобойное'),
                    ('MILITARY_RANGED', 'Воинское дальнобойное'),
                    ('SUPERIOR_RANGED', 'Превосходное дальнобойное'),
                ],
                max_length=70,
                null=True,
                verbose_name='Владение категориями оружия',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='category',
            field=models.CharField(
                choices=[
                    ('MILITARY_RANGED', 'Воинское дальнобойное'),
                    ('MILITARY', 'Воинское рукопашное'),
                    ('SUPERIOR_RANGED', 'Превосходное дальнобойное'),
                    ('SUPERIOR', 'Превосходное рукопашное'),
                    ('SIMPLE_RANGED', 'Простое дальнобойное'),
                    ('SIMPLE', 'Простое рукопашное'),
                ],
                max_length=15,
                verbose_name='Категория',
            ),
        ),
    ]
