# Generated by Django 3.1.3 on 2021-02-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20210221_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='functional_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.functionaltemplate',
                verbose_name='Функциональный шаблон',
            ),
        ),
    ]
