# Generated by Django 3.2.9 on 2021-12-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_powerproperty_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={
                'ordering': ('name',),
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
