# Generated by Django 3.1.3 on 2021-02-24 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_npc_functional_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='functional_template',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.functionaltemplate',
                verbose_name='Функциональный шаблон',
            ),
        ),
    ]
