# Generated by Django 3.1.3 on 2020-11-16 17:43

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_auto_20201116_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implement',
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
            },
        ),
        migrations.AlterModelOptions(
            name='implementtype',
            options={
                'verbose_name': 'Тип инструмента',
                'verbose_name_plural': 'Типы инструментов',
            },
        ),
        migrations.AlterField(
            model_name='class',
            name='available_weapon_categories',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('SIMPLE', 'Простое рукопашное'),
                    ('MILITARY', 'Воинское рукопашное'),
                    ('SUPERIOR', 'Превосходное рукопашное'),
                    ('SIMPLE_RANGED', 'Простое дальнобойное'),
                    ('MILITARY_RANGED', 'Воинское дальнобойное'),
                    ('SUPERIOR_RANGED', 'Превосходное дальнобойное'),
                ],
                max_length=70,
                null=True,
                verbose_name='Владение категориями оружия',
            ),
        ),
    ]
