# Generated by Django 3.1.3 on 2020-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20201116_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='range',
            field=models.SmallIntegerField(default=0, verbose_name='Дальность'),
        ),
    ]
