# Generated by Django 3.2.9 on 2021-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_class_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaltemplate',
            options={
                'ordering': ('title',),
                'verbose_name': 'Функциональный шаблон',
                'verbose_name_plural': 'Функциональные шаблоны',
            },
        ),
        migrations.AlterField(
            model_name='powerproperty',
            name='title',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ATTACK', 'Атака'),
                    ('OTHER', 'Другое'),
                    ('SPECIAL', 'Особенность'),
                    ('HIT', 'Попадание'),
                    ('MISS', 'Промах'),
                    ('REQUIREMENT', 'Требование'),
                    ('TRIGGER', 'Триггер'),
                    ('TARGET', 'Цель'),
                    ('EFFECT', 'Эффект'),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
