# Generated by Django 3.2.9 on 2021-12-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20211203_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combatants',
            options={
                'verbose_name': 'Участник сцены (Монстрятник)',
                'verbose_name_plural': 'Участники сцены (Монстрятник)',
            },
        ),
        migrations.AlterModelOptions(
            name='combatantspc',
            options={
                'verbose_name': 'Участник сцены (ИП)',
                'verbose_name_plural': 'Участники сцены (ИП)',
            },
        ),
    ]
