# Generated by Django 3.1.3 on 2020-11-16 18:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_weapontype_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='properties',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('HIGH_CRIT', 'Высококритичное'),
                    ('OFF_HAND', 'Дополнительное'),
                    ('REACH', 'Досягаемость'),
                    ('LOAD_MINOR', 'Зарядка малым'),
                    ('LOAD_FREE', 'Зарядка свободным'),
                    ('LIGHT_THROWN', 'Лёгкое метательное'),
                    ('SMALL', 'Маленький'),
                    ('HEAVY_THROWN', 'Тяжелое метательное'),
                    ('VERSATILE', 'Универсальное'),
                ],
                max_length=87,
                null=True,
                verbose_name='Свойства',
            ),
        ),
    ]
