# Generated by Django 3.1.3 on 2021-02-24 09:24

from django.db import migrations


def migrate(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    Power.objects.filter(frequency='PASSIVE').update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_auto_20210224_0924'),
    ]

    operations = [migrations.RunPython(migrate)]
