# Generated by Django 3.1.3 on 2021-02-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20210224_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='is_active',
        ),
    ]
