# Generated by Django 3.2.9 on 2021-12-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20211205_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='available_shield_types',
        ),
    ]
