# Generated by Django 3.1.3 on 2020-11-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20201116_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='damage',
            field=models.CharField(
                choices=[
                    ('D4', '1'),
                    ('D6', '1'),
                    ('D8', '1'),
                    ('D10', '1'),
                    ('D12', '1'),
                    ('D2_4', '2'),
                    ('D2_6', '2'),
                    ('D2_8', '2'),
                    ('D2_10', '2'),
                ],
                max_length=5,
                verbose_name='Кость урона',
            ),
        ),
    ]
