# Generated by Django 3.1.3 on 2021-02-24 09:44

from django.db import migrations, models


def migrate(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    Power.objects.filter(frequency='PASSIVE').update(description=models.F('effect'))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_remove_power_is_active'),
    ]

    operations = [migrations.RunPython(migrate)]
