# Generated by Django 3.1.3 on 2021-02-24 09:46

from django.db import migrations


def migrate(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    ClassBonus = apps.get_model('base', 'ClassBonus')
    RaceBonus = apps.get_model('base', 'RaceBonus')
    for cb in ClassBonus.objects.all():
        power = Power(
            name=cb.name,
            description=cb.description,
            frequency='PASSIVE',
            klass=cb.klass,
        )
        power.save()
    for rb in RaceBonus.objects.all():
        power = Power(
            name=rb.name, description=rb.description, frequency='PASSIVE', race=rb.race
        )
        power.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20210224_0944'),
    ]

    operations = [migrations.RunPython(migrate)]
