# Generated by Django 5.1.7 on 2025-03-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_alter_npc_no_hand_alter_npc_primary_hand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effect',
            name='effect_type',
        ),
        migrations.AddField(
            model_name='effect',
            name='is_damage',
            field=models.BooleanField(
                default=False,
                help_text='Shows if damage can have this effect',
                verbose_name='Is damage?',
            ),
        ),
        migrations.AlterField(
            model_name='effect',
            name='name',
            field=models.CharField(
                choices=[
                    ('UNTYPED', 'Без типа'),
                    ('THUNDER', 'Звук'),
                    ('RADIANT', 'Излучение'),
                    ('ACID', 'Кислота'),
                    ('NECROTIC', 'Некротическая энергия'),
                    ('FIRE', 'Огонь'),
                    ('PSYCHIC', 'Психическая энергия'),
                    ('FORCE', 'Силовое поле'),
                    ('COLD', 'Холод'),
                    ('LIGHTNING', 'Электричество'),
                    ('POISON', 'Яд'),
                    ('ZONE', 'Зона'),
                    ('CONJURATION', 'Иллюзия'),
                    ('HEALING', 'Исцеление'),
                    ('RELIABLE', 'Надежный'),
                    ('CHARM', 'Очарование'),
                    ('POLYMORPH', 'Превращение'),
                    ('SLEEP', 'Сон'),
                    ('STANCE', 'Стойка'),
                    ('FEAR', 'Страх'),
                    ('TELEPORTATION', 'Телепортация'),
                    ('RATTLING', 'Ужасающий'),
                    ('INVIGORATING', 'Укрепляющий'),
                    ('RAGE', 'Ярость'),
                ],
                max_length=13,
                verbose_name='Name',
            ),
        ),
    ]
