# Generated by Django 3.1.3 on 2020-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20201116_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='damage',
            field=models.CharField(
                choices=[
                    ('D10', '1k10'),
                    ('D12', '1k12'),
                    ('D4', '1k4'),
                    ('D6', '1k6'),
                    ('D8', '1k8'),
                    ('D2_10', '2k10'),
                    ('D2_4', '2k4'),
                    ('D2_6', '2k6'),
                    ('D2_8', '2k8'),
                ],
                max_length=5,
                verbose_name='Кость урона',
            ),
        ),
    ]
