# Generated by Django 3.2.9 on 2021-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_remove_class_available_shield_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combatantspc',
            name='initiative',
            field=models.FloatField(default=0, verbose_name='Инициатива'),
        ),
    ]
