# Generated by Django 3.1.3 on 2020-11-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20201116_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='attack_attributes',
            new_name='weapon_attack_attributes',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='attack_bonus',
        ),
    ]
