# Generated by Django 3.1.3 on 2020-11-17 07:38

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20201117_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='available_implement_type',
            new_name='available_implement_types',
        ),
        migrations.AddField(
            model_name='npc',
            name='implement_attack_attributes',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Атакующие характеристики',
            ),
        ),
    ]
