# Generated by Django 5.1.7 on 2025-03-06 15:54

from django.db import migrations

from base.constants.constants import PowerDamageTypeEnum, PowerEffectTypeEnum


def fill_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Effect = apps.get_model('base', 'Effect')
    # Power = apps.get_model('base', 'Power')
    effects = []
    for e in PowerDamageTypeEnum:
        effects.append(Effect(name=e.value, is_damage=True))
    for e in PowerEffectTypeEnum:
        if e == PowerEffectTypeEnum.NONE:
            continue
        effects.append(Effect(name=e.value))
    Effect.objects.bulk_create(effects)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_alter_effect_name'),
    ]

    operations = [migrations.RunPython(fill_data)]
