# Generated by Django 5.1.7 on 2025-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20250306_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='damage_types',
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={'is_damage': True},
                related_name='powers',
                to='base.effect',
                verbose_name='Damage type',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='effects',
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={'is_damage': False},
                to='base.effect',
                verbose_name='Effects',
            ),
        ),
    ]
