# Generated by Django 3.1.3 on 2020-11-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_auto_20201117_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='implement',
            name='name',
            field=models.CharField(
                default='Волшебная палочка', max_length=20, verbose_name='Название'
            ),
            preserve_default=False,
        ),
    ]
