# Generated by Django 5.1.7 on 2025-03-06 16:08

from django.db import migrations


def fill_data(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    Effect = apps.get_model('base', 'Effect')
    Power = apps.get_model('base', 'Power')
    for p in Power.objects.all():
        for dt in p.damage_type or []:
            p.damage_types.add(Effect.objects.get(name=dt))
        for et in p.effect_type or []:
            if not et or et == 'NONE':
                continue
            p.effects.add(Effect.objects.get(name=et))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_power_damage_types_alter_power_effects'),
    ]

    operations = [migrations.RunPython(fill_data)]
