# Generated by Django 3.1.3 on 2021-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20210224_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
