# Generated by Django 5.1.7 on 2025-03-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_auto_20250306_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='power',
            name='effect_type',
        ),
    ]
