# Generated by Django 5.1.7 on 2025-03-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_remove_power_damage_type_remove_power_effect_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionaltemplate',
            name='min_level',
            field=models.SmallIntegerField(
                choices=[(1, 1), (11, 11), (21, 21)],
                default=1,
                verbose_name='Minimal level',
            ),
        ),
    ]
