# Generated by Django 3.1.3 on 2021-02-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20210224_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='power_source',
            field=models.CharField(
                choices=[
                    ('MARTIAL', 'Воинский'),
                    ('DIVINE', 'Духовный'),
                    ('ARCANE', 'Магический'),
                    ('PRIMAL', 'Первородный'),
                    ('PSIONIC', 'Псионический'),
                    ('SHADOW', 'Теневой'),
                ],
                max_length=7,
                null=True,
                verbose_name='Источник силы',
            ),
        ),
    ]
