# Generated by Django 3.1.3 on 2020-11-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_npc_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='attributes',
        ),
    ]
