# Generated by Django 3.1.3 on 2021-02-24 13:35

from django.db import migrations


def migrate(apps, schema_editor):
    Power = apps.get_model('base', 'Power')
    Power.objects.filter(frequency='PASSIVE').update(target=None)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20210224_1226'),
    ]

    operations = [migrations.RunPython(migrate)]
