# Generated by Django 5.1.7 on 2025-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_alter_functionaltemplate_min_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magicitemtype',
            name='step',
            field=models.PositiveSmallIntegerField(
                choices=[(5, 5), (10, 10)], default=5, verbose_name='Level step'
            ),
        ),
    ]
