# Generated by Django 3.1.3 on 2020-11-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_remove_npc_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementtype',
            name='inherited_weapon_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='На основании оружия',
            ),
        ),
    ]
