# Generated by Django 3.1.3 on 2020-11-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_implementtype_inherited_weapon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementtype',
            name='inherited_weapon_type',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='На основании оружия',
            ),
        ),
        migrations.AlterField(
            model_name='implementtype',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Название'),
        ),
    ]
