# Generated by Django 5.1.6 on 2025-03-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_alter_magicitemtype_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='arms_slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='npc_hands',
                to='base.armsslotitem',
                verbose_name='Arms slot/shield',
            ),
        ),
    ]
