# Generated by Django 3.1.3 on 2020-11-18 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20201118_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='is_weapon_implement',
        ),
        migrations.AlterField(
            model_name='implementtype',
            name='inherited_weapon_type',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.weapontype',
                verbose_name='На основании оружия',
            ),
        ),
    ]
