# Generated by Django 3.1.3 on 2021-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_auto_20210227_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='target',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Цель'
            ),
        ),
    ]
