# Generated by Django 3.1.3 on 2020-11-18 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20201118_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementtype',
            name='inherited_weapon_type',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='implement_type',
                to='base.weapontype',
                verbose_name='На основании оружия',
            ),
        ),
    ]
