# Generated by Django 3.1.3 on 2020-11-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_classbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subclasses',
            field=models.SmallIntegerField(
                default=0, verbose_name='Количество подклассов'
            ),
        ),
    ]
