# Generated by Django 3.1.3 on 2020-11-20 17:17

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_class_subclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='implement_attack_attributes',
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                max_length=60,
                null=True,
                verbose_name='Атакующие характеристики (инструмент)',
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='power_source',
            field=models.CharField(
                choices=[
                    ('MARTIAL', 'Воинский'),
                    ('DIVINE', 'Духовный'),
                    ('ARCANE', 'Магический'),
                    ('PRIMAL', 'Первородный'),
                ],
                max_length=7,
                null=True,
                verbose_name='Источник силы',
            ),
        ),
        migrations.AddField(
            model_name='class',
            name='weapon_attack_attributes',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default='STRENGTH',
                max_length=60,
                verbose_name='Атакующие характеристики (оружие)',
            ),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                (
                    'frequency',
                    models.CharField(
                        choices=[
                            ('DAYLY', 'На день'),
                            ('ENCOUNTER', 'На сцену'),
                            ('AT_WILL', 'Неограниченный'),
                        ],
                        max_length=9,
                        verbose_name='Частота использования',
                    ),
                ),
                (
                    'attack_attribute',
                    models.CharField(
                        choices=[
                            ('STRENGTH', 'Сила'),
                            ('CONSTITUTION', 'Телосложение'),
                            ('DEXTERITY', 'Ловкость'),
                            ('INTELLIGENCE', 'Интеллект'),
                            ('WISDOM', 'Мудрость'),
                            ('CHARISMA', 'Харизма'),
                        ],
                        default='STRENGTH',
                        max_length=12,
                        verbose_name='Атакующий аттрибут',
                    ),
                ),
                (
                    'defence',
                    models.CharField(
                        choices=[
                            ('WILL', 'Воля'),
                            ('ARMOR_CLASS', 'КД'),
                            ('REFLEX', 'Реакция'),
                            ('FORTITUDE', 'Стойкость'),
                        ],
                        default='ARMOR_CLASS',
                        max_length=11,
                        verbose_name='Против защиты',
                    ),
                ),
                (
                    'damage_type',
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ('NONE', 'Без типа'),
                            ('RADIANT', 'Излучение'),
                            ('ACID', 'Кислота'),
                            ('NECROTIC', 'Некротическая энергия'),
                            ('FIRE', 'Огонь'),
                            ('COLD', 'Холод'),
                            ('LIGHTNING', 'Электричество'),
                            ('POISON', 'Яд'),
                        ],
                        default='NONE',
                        max_length=53,
                        verbose_name='Тип урона',
                    ),
                ),
                (
                    'accessory_type',
                    models.CharField(
                        choices=[('IMPLEMENT', 'Инструмент'), ('WEAPON', 'Оружие')],
                        max_length=9,
                        verbose_name='',
                    ),
                ),
                (
                    'range',
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name='Дальность'
                    ),
                ),
                (
                    'hit_effect',
                    models.TextField(blank=True, null=True, verbose_name='Попадание'),
                ),
                (
                    'miss_effect',
                    models.TextField(blank=True, null=True, verbose_name='Попадание'),
                ),
                (
                    'effect',
                    models.TextField(blank=True, null=True, verbose_name='Попадание'),
                ),
                (
                    'klass',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='base.class'
                    ),
                ),
                (
                    'parent_power',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='base.power',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Таланты',
            },
        ),
    ]
