# Generated by Django 3.1.3 on 2020-11-20 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20201120_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='base.class',
                verbose_name='Класс',
            ),
        ),
    ]
