# Generated by Django 3.1.3 on 2020-11-20 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_power_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='defence',
            field=models.CharField(
                choices=[
                    ('ARMOR_CLASS', 'КД'),
                    ('FORTITUDE', 'Стойкость'),
                    ('REFLEX', 'Реакция'),
                    ('WILL', 'Воля'),
                ],
                default='ARMOR_CLASS',
                max_length=11,
                verbose_name='Против защиты',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='effect',
            field=models.TextField(blank=True, null=True, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='power',
            name='frequency',
            field=models.CharField(
                choices=[
                    ('AT_WILL', 'Неограниченный'),
                    ('ENCOUNTER', 'На сцену'),
                    ('DAYLY', 'На день'),
                ],
                max_length=9,
                verbose_name='Частота использования',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='miss_effect',
            field=models.TextField(blank=True, null=True, verbose_name='Промах'),
        ),
        migrations.AlterField(
            model_name='power',
            name='parent_power',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='base.power',
                verbose_name='Родительский талант',
            ),
        ),
    ]
