# Generated by Django 3.1.3 on 2020-11-23 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20201120_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbonus',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bonuses',
                to='base.class',
            ),
        ),
        migrations.AlterField(
            model_name='racebonus',
            name='race',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='bonuses',
                to='base.race',
            ),
        ),
    ]
