# Generated by Django 3.1.3 on 2020-11-26 07:43

from django.db import migrations, models

import base.constants


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20201123_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='attack_bonus',
            field=models.SmallIntegerField(default=0, verbose_name='Бонус атаки'),
        ),
        migrations.AddField(
            model_name='power',
            name='burst',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Площадь'),
        ),
        migrations.AddField(
            model_name='power',
            name='dice',
            field=models.CharField(
                blank=True,
                choices=[
                    ('D10', 'k10'),
                    ('D100', 'k100'),
                    ('D12', 'k12'),
                    ('D20', 'k20'),
                    ('D4', 'k4'),
                    ('D6', 'k6'),
                    ('D8', 'k8'),
                ],
                max_length=4,
                null=True,
                verbose_name='Куб',
            ),
        ),
        migrations.AddField(
            model_name='power',
            name='dices_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='power',
            name='range_type',
            field=models.CharField(
                choices=[
                    ('MELEE_WEAPON', 'Рукопашное оружие'),
                    ('MELEE_DISTANCE', 'Рукопашное (дистанция)'),
                    ('MELEE_TOUCH', 'Рукопашное касание'),
                    ('RANGED_WEAPON', 'Дальнобойное оружие'),
                    ('RANGED_DISTANCE', 'Дальнобойное (дистанция)'),
                    ('RANGED_SIGHT', 'Дальнобойное (видимость)'),
                    ('CLOSE_BURST', 'Ближняя вспышка'),
                    ('CLOSE_BLAST', 'Ближняя волна'),
                    ('AREA_BURST', 'Зональная вспышка'),
                    ('AREA_WALL', 'Стена'),
                ],
                default=base.constants.PowerRangeType['MELEE_WEAPON'],
                max_length=15,
                verbose_name='Дальность',
            ),
        ),
        migrations.AddField(
            model_name='weapontype',
            name='dice_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='power',
            name='accessory_type',
            field=models.CharField(
                choices=[('IMPLEMENT', 'Инструмент'), ('WEAPON', 'Оружие')],
                max_length=9,
                verbose_name='Тип вооружения',
            ),
        ),
        migrations.AlterField(
            model_name='power',
            name='attack_attribute',
            field=models.CharField(
                choices=[
                    ('STRENGTH', 'Сила'),
                    ('CONSTITUTION', 'Телосложение'),
                    ('DEXTERITY', 'Ловкость'),
                    ('INTELLIGENCE', 'Интеллект'),
                    ('WISDOM', 'Мудрость'),
                    ('CHARISMA', 'Харизма'),
                ],
                default='STRENGTH',
                max_length=12,
                verbose_name='Атакующая характеристика',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='damage',
            field=models.CharField(
                choices=[
                    ('D10', 'k10'),
                    ('D100', 'k100'),
                    ('D12', 'k12'),
                    ('D20', 'k20'),
                    ('D4', 'k4'),
                    ('D6', 'k6'),
                    ('D8', 'k8'),
                ],
                max_length=4,
                verbose_name='Кость урона',
            ),
        ),
    ]
