# Generated by Django 3.1.3 on 2020-11-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20201126_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power',
            name='dice',
        ),
        migrations.RemoveField(
            model_name='power',
            name='dices_number',
        ),
        migrations.AddField(
            model_name='power',
            name='damage_dice',
            field=models.CharField(
                blank=True,
                choices=[
                    ('D4', 'k4'),
                    ('D6', 'k6'),
                    ('D8', 'k8'),
                    ('D10', 'k10'),
                    ('D12', 'k12'),
                    ('D20', 'k20'),
                    ('D100', 'k100'),
                ],
                max_length=4,
                null=True,
                verbose_name='Кость урона',
            ),
        ),
        migrations.AddField(
            model_name='power',
            name='dice_number',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='Количество кубов'
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='damage',
            field=models.CharField(
                choices=[
                    ('D4', 'k4'),
                    ('D6', 'k6'),
                    ('D8', 'k8'),
                    ('D10', 'k10'),
                    ('D12', 'k12'),
                    ('D20', 'k20'),
                    ('D100', 'k100'),
                ],
                max_length=4,
                verbose_name='Кость урона',
            ),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='dice_number',
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name='Количество кубов'
            ),
        ),
    ]
