# Generated by Django 3.1.3 on 2020-11-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20201126_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapontype',
            old_name='damage',
            new_name='damage_dice',
        ),
    ]
