# Generated by Django 3.1.3 on 2020-11-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_auto_20201126_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='klass',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='powers',
                to='base.class',
                verbose_name='Класс',
            ),
        ),
    ]
