# Generated by Django 5.2.1 on 2025-05-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPower',
            fields=[],
            options={
                'verbose_name': 'Class power',
                'verbose_name_plural': 'Class powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[],
            options={
                'verbose_name': 'Feat',
                'verbose_name_plural': 'Feats',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.feat',),
        ),
        migrations.CreateModel(
            name='FunctionalTemplatePower',
            fields=[],
            options={
                'verbose_name': 'Functional template power',
                'verbose_name_plural': 'Functional template powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='MagicItemTypePower',
            fields=[],
            options={
                'verbose_name': 'Magic item type power',
                'verbose_name_plural': 'Magic item type powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='ParagonPathPower',
            fields=[],
            options={
                'verbose_name': 'Paragon path power',
                'verbose_name_plural': 'Paragon path powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='Power',
            fields=[],
            options={
                'verbose_name': 'Power',
                'verbose_name_plural': 'Powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='RacePower',
            fields=[],
            options={
                'verbose_name': 'Race power',
                'verbose_name_plural': 'Race powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='SkillPower',
            fields=[],
            options={
                'verbose_name': 'Skill power',
                'verbose_name_plural': 'Skill powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
        migrations.CreateModel(
            name='SubclassPower',
            fields=[],
            options={
                'verbose_name': 'Subclass power',
                'verbose_name_plural': 'Subclass powers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.power',),
        ),
    ]
